/** Nomes de exibição (PT) dos tipos de monstro. */
export const MONSTER_LABELS = {
  imp: 'imp',
  slime: 'slime',
  wraith: 'espectro',
  goblin: 'goblin',
  orc: 'orc',
  skeleton: 'esqueleto',
  skeleton_archer: 'esqueleto arqueiro',
  wolf: 'lobo',
  giant_spider: 'aranha gigante',
  bat: 'morcego',
  elf: 'elfo',
  beholder: 'beholder',
  dragon: 'dragão',
  lich: 'lich',
  fire_elemental: 'elemental de fogo',
  demon: 'demônio',
  grim_reaper: 'ceifador',
  bruxo: 'bruxo',
  cyclops: 'ciclope',
  minotaur: 'minotauro',
  harpy: 'harpía',
  kobold: 'kobold',
  zombie: 'zumbi',
  mummy: 'múmia',
  ghoul: 'carniçal',
  ratman: 'homem-rato',
  scorpion: 'escorpião',
  venom_snake: 'serpente venenosa',
  cultist: 'cultista',
  gargoyle: 'gárgula',
  pixie: 'pixie',
  dwarf_guard: 'anão guardião',
  bandit: 'bandido',
  pirate: 'pirata',
  giant_toad: 'sapo gigante',
  wasp: 'vespa',
  crab: 'caranguejo',
  yeti_cub: 'yeti jovem',
  shadow_wolf: 'lobo sombrio',
  cave_troll: 'troll das cavernas',
  swamp_slug: 'lesma do pântano',
  desert_scavenger: 'necrófago do deserto',
  gnoll: 'gnoll',
  ice_imp: 'imp de gelo',
  ancient_scarab: 'escaravelho antigo',
  death_knight: 'cavaleiro da morte',
  frost_mage: 'mago do gelo',
  venom_hydra: 'hidra venenosa',
  stone_golem: 'golem de pedra',
  blood_succubus: 'súcubo de sangue',
  nightmare_steed: 'corcel do pesadelo',
  bone_whelp: 'filhote ósseo',
  abyss_watcher: 'vigia do abismo',
  crystal_elemental: 'elemental de cristal',
  plague_doctor: 'médico da praga',
  war_troll: 'troll de guerra',
  shadow_assassin: 'assassino sombrio',
  storm_elemental: 'elemental da tempestade',
  magma_golem: 'golem de magma',
  forest_guardian: 'guardião da floresta',
  void_stalker: 'caçador do vazio',
  ice_wyrm: 'serpe de gelo',
  necromancer: 'necromante',
  frost_dragon: 'dragão de gelo',
  bone_dragon: 'dragão ósseo',
  kraken: 'kraken',
  hydra_boss: 'hidra ancestral',
  medusa: 'medusa',
  phoenix: 'fênix',
  titan: 'titã',
  void_lord: 'senhor do vazio',
  ancient_treant: 'treant ancestral',
  sand_worm: 'verme das areias',
  flame_lord: 'senhor das chamas',
  frost_lich: 'lich glacial',
  plague_queen: 'rainha da praga',
  storm_giant: 'gigante da tempestade',
  cerberus: 'cérbero',
  basilisk: 'basilisco',
  djinn: 'djinn',
  archdemon: 'arquidemônio',
  world_serpent: 'serpente do mundo',
  frogman: 'homem-sapo',
  porcupine: 'porco-espinho',
  dune_viper: 'víbora das dunas',
  moss_sprite: 'sprite do musgo',
  scrap_golem: 'golem de sucata',
  raven_scout: 'corvo batedor',
  bog_witch_apprentice: 'aprendiz do pântano',
  crystal_bat: 'morcego de cristal',
  iron_boar: 'javali de ferro',
  sand_archer: 'arqueiro das areias',
  frost_sprite: 'sprite glacial',
  cave_crawler: 'rastejante das cavernas',
  marsh_lurker: 'espreitador do pântano',
  ember_whelp: 'filhote de brasa',
  bone_picker: 'catador de ossos',
  thorn_bush: 'arbusto espinhoso',
  ash_rat: 'rato de cinzas',
  coral_crab: 'caranguejo de coral',
  wind_sylph: 'sílfide do vento',
  tomb_guard: 'guardião do túmulo',
  spore_fungus: 'fungo esporado',
  glacier_cub: 'filhote glacial',
  night_owl: 'coruja noturna',
  brimstone_imp: 'imp de enxofre',
  reed_stalker: 'espreitador dos juncos',
  thunder_hawk: 'falcão do trovão',
  blood_ogre: 'ogro sangrento',
  mirage_dancer: 'dançarina da miragem',
  frost_berserker: 'berserker glacial',
  venom_alchemist: 'alquimista venenoso',
  obsidian_guardian: 'guardião de obsidiana',
  soul_harvester: 'ceifador de almas',
  lava_serpent: 'serpente de lava',
  mirror_wraith: 'espectro espelhado',
  plague_rat_king: 'rei dos ratos da praga',
  storm_rider: 'cavaleiro da tempestade',
  ironbark_treant: 'treant de casca-ferro',
  crimson_cultist: 'cultista carmesim',
  void_imp_lord: 'senhor dos imps do vazio',
  sapphire_drake: 'dragão de safira',
  eclipse_sphinx: 'esfinge do eclipse',
  magma_colossus: 'colosso de magma',
  arctic_leviathan: 'leviatã ártico',
  blight_emperor: 'imperador da praga',
  chronomancer: 'cronomante',
  dread_naga: 'naga do pavor',
  solar_phoenix: 'fênix solar',
  abyssal_kraken: 'kraken abissal',
  bone_emperor: 'imperador ósseo',
  world_ender: 'fim do mundo',
  mushroom_brute: 'ogro-cogumelo',
  salt_golem: 'golem de sal',
  fox_trickster: 'raposa trapaceira',
  quill_hunter: 'caçador de espinhos',
  peat_zombie: 'zumbi de turfa',
  lantern_spirit: 'espírito da lanterna',
  cliff_goat: 'cabra do penhasco',
  reef_shark: 'tubarão do recife',
  dust_mephit: 'mefite de pó',
  bark_spider: 'aranha-casca',
  snow_hare: 'lebre da neve',
  torch_bearer: 'portador da tocha',
  bog_mosquito: 'mosquito do pântano',
  rune_scribe: 'escriba rúnico',
  clay_soldier: 'soldado de barro',
  pearl_diver: 'mergulhador de pérolas',
  night_panther: 'pantera noturna',
  hive_drone: 'zangão da colmeia',
  frost_toad: 'sapo glacial',
  scrap_bandit: 'bandido de sucata',
  vine_creeper: 'cipó rastejante',
  cinder_sprite: 'sprite de cinzas',
  tunnel_mole: 'toupeira de túnel',
  glass_imp: 'imp de vidro',
  thunder_boar: 'javali do trovão',
  blood_knight: 'cavaleiro sangrento',
  sand_djinni: 'djinn das areias',
  poison_archer: 'arqueiro venenoso',
  jade_golem: 'golem de jade',
  shadow_priest: 'sacerdote das sombras',
  bladed_mantis: 'louva-a-deus laminado',
  storm_witch: 'bruxa da tempestade',
  furnace_beast: 'fera da fornalha',
  crystal_archer: 'arqueiro de cristal',
  void_hound: 'cão do vazio',
  plague_swarm: 'enxame da praga',
  iron_sentinel: 'sentinela de ferro',
  aurora_mage: 'mago da aurora',
  ash_wyvern: 'wyvern de cinzas',
  bone_reaver: 'ceifador ósseo',
  tempest_queen: 'rainha da tempestade',
  forge_titan: 'titã da forja',
  coral_empress: 'imperatriz de coral',
  nightmare_king: 'rei do pesadelo',
  elder_beholder: 'beholder ancião',
  doom_hydra: 'hidra da perdição',
  astral_serpent: 'serpente astral',
  war_god_avatar: 'avatar do deus da guerra',
  necrotic_colossus: 'colosso necrótico',
  chaos_primordial: 'primordial do caos',
  pebble_sprite: 'sprite de pedra',
  reed_rat: 'rato dos juncos',
  tide_urchin: 'ouriço da maré',
  cinder_moth: 'mariposa de cinzas',
  pine_sprite: 'sprite do pinheiro',
  copper_goblin: 'goblin de cobre',
  mist_wisp: 'fogo-fátuo da névoa',
  brine_crab: 'caranguejo salgado',
  soot_imp: 'imp de fuligem',
  thistle_boar: 'javali de cardos',
  kelp_strider: 'caminhante de algas',
  ember_gnat: 'mosquito de brasas',
  chalk_golem_cub: 'golem de giz jovem',
  dusk_ferret: 'furão do crepúsculo',
  bog_newt: 'tritão do pântano',
  crystal_mite: 'ácaro de cristal',
  rust_scorpion: 'escorpião enferrujado',
  pollen_pixie: 'pixie de pólen',
  shale_basher: 'espancador de xisto',
  frost_vole: 'arganaz glacial',
  tar_slug: 'lesma de piche',
  spark_sprite: 'sprite de faísca',
  dune_jackal: 'chacal das dunas',
  lichen_troll_cub: 'troll de líquen jovem',
  ivory_skeleton: 'esqueleto de marfim',
  mangrove_croco: 'crocodilo do mangue',
  storm_finch: 'tentilhão da tempestade',
  ash_cult_initiate: 'iniciado do culto das cinzas',
  prism_moth: 'mariposa prismática',
  geyser_toad: 'sapo do gêiser',
  carrion_vulture: 'abutre carniceiro',
  magma_grub: 'larva de magma',
  void_mote: 'partícula do vazio',
  salt_wraith: 'espectro de sal',
  iron_tick: 'carrapato de ferro',
  glacier_imp: 'imp glacial',
  thorn_imp: 'imp de espinhos',
  cave_bat_swarm: 'enxame de morcegos',
  scrap_wolf: 'lobo de sucata',
  coral_snake: 'serpente de coral',
  rune_imp: 'imp rúnico',
  peat_slime: 'slime de turfa',
  wind_razor: 'lâmina do vento',
  blood_leech: 'sanguessuga',
  frost_archer_novice: 'arqueiro glacial novato',
  shade_larva: 'larva das sombras',
  pyre_cultist: 'cultista da pira',
  quartz_beetle: 'besouro de quartzo',
  acid_alchemist: 'alquimista ácido',
  frost_wyvern: 'wyvern glacial',
  bone_chanter: 'encantador ósseo',
  hex_witch: 'bruxa do hex',
  magma_brute: 'bruto de magma',
  storm_centurion: 'centurião da tempestade',
  obsidian_raptor: 'raptor de obsidiana',
  venom_naga: 'naga venenosa',
  crystal_guardian: 'guardião de cristal',
  shadow_duelist: 'duelista sombrio',
  pyre_drake: 'drake da pira',
  glacier_knight: 'cavaleiro glacial',
  plague_harpy: 'harpía da praga',
  rune_golem: 'golem rúnico',
  blood_panther: 'pantera sangrenta',
  arcane_archer: 'arqueiro arcano',
  furnace_golem: 'golem da fornalha',
  void_serpent: 'serpente do vazio',
  jade_monk: 'monge de jade',
  thunder_drake: 'drake do trovão',
  mirror_knight: 'cavaleiro espelhado',
  blight_treant: 'treant da praga',
  ash_assassin: 'assassino de cinzas',
  sapphire_witch: 'bruxa de safira',
  iron_hydra: 'hidra de ferro',
  soul_thief: 'ladrão de almas',
  cinder_titan_spawn: 'cria do titã de brasas',
  aurora_serpent: 'serpente da aurora',
  grave_sentinel: 'sentinela da sepultura',
  night_reaver: 'ceifador noturno',
  ember_witch: 'bruxa de brasas',
  toxin_archer: 'arqueiro tóxico',
  acid_sovereign: 'soberano ácido',
  frost_empress: 'imperatriz glacial',
  bone_overlord: 'suserano ósseo',
  hex_archon: 'arconte do hex',
  magma_tyrant: 'tirano de magma',
  storm_colossus: 'colosso da tempestade',
  void_matriarch: 'matriarca do vazio',
  plague_sovereign: 'soberano da praga',
  solar_phoenix_lord: 'senhor da fênix solar',
  abyss_leviathan: 'leviatã abissal',
  jade_emperor: 'imperador de jade',
  crimson_warlord: 'senhor da guerra carmesim',
  necrotic_queen: 'rainha necrótica',
  entropy_dragon: 'dragão da entropia',
  iron_behemoth: 'beemote de ferro',
  mire_hydra_king: 'rei hidra do lodo',
  astral_tyrant: 'tirano astral',
  forge_emperor: 'imperador da forja',
  shadow_primordial: 'primordial das sombras',
  tide_kraken_lord: 'senhor kraken das marés',
  amber_mite: 'ácaro âmbar',
  fog_hare: 'lebre da névoa',
  driftwood_crab: 'caranguejo de madeira',
  pollen_moth: 'mariposa de pólen',
  basalt_cub: 'filhote de basalto',
  reed_imp: 'imp de junco',
  snow_finch: 'tentilhão da neve',
  salt_scorpion: 'escorpião de sal',
  moss_newt: 'tritão de musgo',
  copper_tick: 'carrapato de cobre',
  tide_sprite: 'sprite das marés',
  ash_vole: 'arganaz de cinzas',
  bramble_boar: 'javali de sarças',
  chalk_imp: 'imp de giz',
  mire_slug: 'lesma do lodo',
  gust_sylph: 'sylph da rajada',
  onyx_beetle: 'besouro de ônix',
  peat_rat: 'rato de turfa',
  glint_pixie: 'pixie reluzente',
  dune_scarab: 'escaravelho das dunas',
  frost_gnat: 'mosquito glacial',
  root_crawler: 'rastejante de raízes',
  cinder_toad: 'sapo de brasas',
  pearl_slug: 'lesma de pérola',
  rune_mite: 'ácaro rúnico',
  shadow_vole: 'arganaz sombrio',
  coral_urchin: 'ouriço de coral',
  pine_imp: 'imp de pinheiro',
  slag_imp: 'imp de escória',
  ice_tick: 'carrapato de gelo',
  bog_finch: 'tentilhão do pântano',
  quartz_mite: 'ácaro de quartzo',
  dust_jackal: 'chacal de pó',
  kelp_newt: 'tritão de algas',
  ember_vole: 'arganaz de brasas',
  thorn_mite: 'ácaro de espinhos',
  mist_imp: 'imp da névoa',
  shale_tick: 'carrapato de xisto',
  aurora_moth: 'mariposa da aurora',
  blood_mite: 'ácaro de sangue',
  salt_newt: 'tritão de sal',
  vine_imp: 'imp de vinhas',
  glacier_mite: 'ácaro glacial',
  scrap_tick: 'carrapato de sucata',
  void_gnat: 'mosquito do vazio',
  marsh_imp: 'imp do pântano',
  crystal_finch: 'tentilhão de cristal',
  pyre_mite: 'ácaro da pira',
  amber_golem: 'golem âmbar',
  fog_wraith: 'espectro da névoa',
  drift_krakenling: 'kraken jovem',
  pollen_witch: 'bruxa de pólen',
  basalt_guardian: 'guardião de basalto',
  reed_naga: 'naga de junco',
  snow_berserker: 'berserker da neve',
  salt_goliath: 'golias de sal',
  moss_treant: 'treant de musgo',
  copper_sentinel: 'sentinela de cobre',
  tide_witch: 'bruxa das marés',
  ash_assassin_adept: 'assassino de cinzas adepto',
  bramble_hydra: 'hidra de sarças',
  chalk_mage: 'mago de giz',
  mire_hydra: 'hidra do lodo',
  gust_djinn: 'djinn da rajada',
  onyx_knight: 'cavaleiro de ônix',
  peat_necromancer: 'necromante de turfa',
  glint_sphinx: 'esfinge reluzente',
  dune_wyrm: 'serpe das dunas',
  frost_centurion: 'centurião glacial',
  root_guardian: 'guardião de raízes',
  cinder_drake: 'drake de brasas',
  pearl_siren: 'sereia de pérola',
  rune_archon_adept: 'adepto arconte rúnico',
  shadow_duelist_elite: 'duelista sombrio elite',
  coral_hydra: 'hidra de coral',
  pine_treant: 'treant de pinheiro',
  slag_golem: 'golem de escória',
  ice_wyvern_adept: 'wyvern glacial adepto',
  bog_alchemist: 'alquimista do pântano',
  quartz_guardian: 'guardião de quartzo',
  amber_sovereign: 'soberano âmbar',
  fog_matriarch: 'matriarca da névoa',
  drift_kraken_king: 'rei kraken das correntes',
  pollen_empress: 'imperatriz de pólen',
  basalt_colossus: 'colosso de basalto',
  reed_hydra_queen: 'rainha hidra de junco',
  snow_emperor: 'imperador da neve',
  salt_tyrant: 'tirano de sal',
  moss_world_tree: 'árvore-mundo de musgo',
  copper_behemoth: 'beemote de cobre',
  tide_leviathan: 'leviatã das marés',
  ash_warlord: 'senhor da guerra de cinzas',
  bramble_primordial: 'primordial de sarças',
  chalk_archon: 'arconte de giz',
  mire_sovereign: 'soberano do lodo',
  gust_storm_lord: 'senhor da rajada',
  onyx_overlord: 'suserano de ônix',
  peat_bone_king: 'rei ósseo de turfa',
  glint_astral_lord: 'senhor astral reluzente',
  dune_sand_emperor: 'imperador das areias',
  orc_recruit: 'orc recruta',
  goblin_scout: 'goblin batedor',
  slime_spawn: 'slime cria',
  wolf_pup: 'filhote de lobo',
  skeleton_recruit: 'esqueleto recruta',
  bat_hatchling: 'morcego filhote',
  imp_whelp: 'imp filhote',
  elf_apprentice: 'elfo aprendiz',
  zombie_thrall: 'zumbi servo',
  mummy_servant: 'múmia serva',
  ghoul_scavenger: 'carniçal necrófago',
  kobold_miner: 'kobold mineiro',
  bandit_thug: 'bandido capanga',
  pirate_deckhand: 'pirata grumete',
  cyclops_youth: 'ciclope jovem',
  minotaur_calf: 'minotauro jovem',
  harpy_fledgling: 'harpía filhote',
  scorpion_nymph: 'escorpião ninfa',
  cultist_initiate: 'cultista iniciado',
  gargoyle_shard: 'gárgula fragmento',
  pixie_spark: 'pixie faísca',
  gnoll_pup: 'gnoll filhote',
  ratman_squeaker: 'homem-rato chiador',
  crab_hatchling: 'caranguejo filhote',
  wasp_drone: 'vespa zangão',
  toad_tadpole: 'sapo girino',
  dwarf_squire: 'anão escudeiro',
  wraith_shade: 'espectro sombra',
  frogman_poliwog: 'homem-sapo girino',
  porcupine_kit: 'porco-espinho filhote',
  raven_chick: 'corvo filhote',
  boar_piglet: 'javali leitão',
  owl_fledgling: 'coruja filhote',
  fox_kit: 'raposa filhote',
  shark_pup: 'tubarão filhote',
  hive_larva: 'larva da colmeia',
  yeti_whelp: 'yeti filhote',
  spiderling: 'aranha filhote',
  snake_hatchling: 'serpente filhote',
  desert_jackal_pup: 'chacal filhote',
  troll_runt: 'troll nanico',
  slug_nymph: 'lesma ninfa',
  ice_imp_spark: 'imp de gelo faísca',
  scarab_larva: 'escaravelho larva',
  bone_shardling: 'fragmento ósseo',
  ember_spark: 'faísca de brasa',
  ash_rat_pup: 'rato de cinzas filhote',
  coral_crab_hatch: 'caranguejo de coral filhote',
  orc_war_chief: 'orc chefe da guerra',
  goblin_raid_captain: 'goblin capitão de raid',
  slime_overseer: 'slime supervisor',
  wolf_alpha: 'lobo alfa',
  skeleton_captain: 'esqueleto capitão',
  bat_matriarch: 'morcego matriarca',
  imp_taskmaster: 'imp feitor',
  elf_blademaster: 'elfo mestre das lâminas',
  zombie_warlord: 'zumbi senhor da guerra',
  mummy_pharaoh_guard: 'guarda do faraó',
  ghoul_packleader: 'carniçal líder da matilha',
  kobold_trapmaster: 'kobold mestre das armadilhas',
  bandit_kingpin: 'bandido chefão',
  pirate_captain: 'pirata capitão',
  cyclops_champion: 'ciclope campeão',
  minotaur_arena_lord: 'minotauro senhor da arena',
  harpy_stormcaller: 'harpía invocadora de tempestade',
  scorpion_broodmother: 'escorpião mãe da ninhada',
  cultist_hierophant: 'cultista hierofante',
  gargoyle_sentinel: 'gárgula sentinela',
  pixie_queen_guard: 'guarda da rainha pixie',
  gnoll_packlord: 'gnoll senhor da matilha',
  ratman_warlord: 'homem-rato senhor da guerra',
  crab_shellbreaker: 'caranguejo quebracascos',
  wasp_hivequeen_guard: 'guarda da rainha vespa',
  toad_bog_king: 'sapo rei do pântano',
  dwarf_warcaptain: 'anão capitão de guerra',
  wraith_reaper: 'espectro ceifador',
  frost_mage_adept: 'mago do gelo adepto',
  death_knight_vanguard: 'cavaleiro da morte vanguarda',
  shadow_assassin_master: 'assassino sombrio mestre',
  stone_golem_warden: 'golem de pedra guardião',
  orc_warchief_king: 'orc rei chefe da guerra',
  goblin_warlord_king: 'goblin rei senhor da guerra',
  slime_emperor: 'slime imperador',
  wolf_dire_king: 'lobo rei dire',
  skeleton_bone_king: 'esqueleto rei dos ossos',
  imp_hell_overlord: 'imp suserano do inferno',
  elf_forest_sovereign: 'elfo soberano da floresta',
  zombie_plague_king: 'zumbi rei da praga',
  mummy_pharaoh: 'múmia faraó',
  cyclops_mountain_king: 'ciclope rei da montanha',
  minotaur_labyrinth_king: 'minotauro rei do labirinto',
  harpy_sky_empress: 'harpía imperatriz dos céus',
  cultist_dark_messiah: 'cultista messias sombrio',
  gargoyle_cathedral_lord: 'gárgula senhor da catedral',
  gnoll_war_khan: 'gnoll khan da guerra',
  pirate_sea_emperor: 'pirata imperador dos mares',
  bandit_crime_emperor: 'bandido imperador do crime',
  dwarf_forge_king: 'anão rei da forja',
  ratman_underking: 'homem-rato rei subterrâneo',
  scorpion_dune_emperor: 'escorpião imperador das dunas',
  amber_mite_junior: 'ácaro âmbar jovem',
  ash_rat_runt: 'rato de cinzas nanico',
  ash_vole_cadet: 'arganaz de cinzas cadete',
  aurora_moth_rookie: 'mariposa da aurora novato',
  bandit_page: 'bandido escudeiro',
  bark_spider_acolyte: 'aranha-casca acólito',
  bat_squire: 'morcego escudeiro',
  blood_leech_larva: 'sanguessuga larval',
  blood_mite_junior: 'ácaro de sangue jovem',
  boar_piglet_runt: 'javali leitão nanico',
  bog_finch_cadet: 'tentilhão do pântano cadete',
  bog_mosquito_rookie: 'mosquito do pântano novato',
  bog_newt_page: 'tritão do pântano escudeiro',
  bone_picker_acolyte: 'catador de ossos acólito',
  bone_shardling_squire: 'fragmento ósseo escudeiro',
  bramble_boar_larva: 'javali de sarças larval',
  brimstone_imp_junior: 'imp de enxofre jovem',
  brine_crab_runt: 'caranguejo salgado nanico',
  carrion_vulture_cadet: 'abutre carniceiro cadete',
  cave_bat_swarm_rookie: 'enxame de morcegos novato',
  cave_crawler_page: 'rastejante das cavernas escudeiro',
  cave_troll_acolyte: 'troll das cavernas acólito',
  chalk_imp_squire: 'imp de giz escudeiro',
  cinder_moth_larva: 'mariposa de cinzas larval',
  cinder_sprite_junior: 'sprite de cinzas jovem',
  cinder_toad_runt: 'sapo de brasas nanico',
  clay_soldier_cadet: 'soldado de barro cadete',
  cliff_goat_rookie: 'cabra do penhasco novato',
  copper_goblin_page: 'goblin de cobre escudeiro',
  copper_tick_acolyte: 'carrapato de cobre acólito',
  coral_crab_squire: 'caranguejo de coral escudeiro',
  coral_crab_hatch_larva: 'caranguejo de coral filhote larval',
  coral_snake_junior: 'serpente de coral jovem',
  coral_urchin_runt: 'ouriço de coral nanico',
  crab_cadet: 'caranguejo cadete',
  crystal_bat_rookie: 'morcego de cristal novato',
  crystal_finch_page: 'tentilhão de cristal escudeiro',
  crystal_mite_acolyte: 'ácaro de cristal acólito',
  cultist_squire: 'cultista escudeiro',
  cyclops_larva: 'ciclope larval',
  driftwood_crab_junior: 'caranguejo de madeira jovem',
  dune_jackal_runt: 'chacal das dunas nanico',
  dune_scarab_cadet: 'escaravelho das dunas cadete',
  dune_viper_rookie: 'víbora das dunas novato',
  dusk_ferret_page: 'furão do crepúsculo escudeiro',
  dust_jackal_acolyte: 'chacal de pó acólito',
  dust_mephit_squire: 'mefite de pó escudeiro',
  dwarf_guard_larva: 'anão guardião larval',
  elf_junior: 'elfo jovem',
  ember_gnat_runt: 'mosquito de brasas nanico',
  ember_vole_cadet: 'arganaz de brasas cadete',
  fog_hare_rookie: 'lebre da névoa novato',
  fox_trickster_page: 'raposa trapaceira escudeiro',
  frogman_acolyte: 'homem-sapo acólito',
  frogman_poliwog_squire: 'homem-sapo girino escudeiro',
  frost_gnat_larva: 'mosquito glacial larval',
  frost_sprite_junior: 'sprite glacial jovem',
  frost_toad_runt: 'sapo glacial nanico',
  frost_vole_cadet: 'arganaz glacial cadete',
  gargoyle_rookie: 'gárgula novato',
  geyser_toad_page: 'sapo do gêiser escudeiro',
  ghoul_acolyte: 'carniçal acólito',
  giant_toad_squire: 'sapo gigante escudeiro',
  glacier_imp_larva: 'imp glacial larval',
  glacier_mite_junior: 'ácaro glacial jovem',
  glass_imp_runt: 'imp de vidro nanico',
  glint_pixie_cadet: 'pixie reluzente cadete',
  gnoll_rookie: 'gnoll novato',
  goblin_page: 'goblin escudeiro',
  gust_sylph_acolyte: 'sylph da rajada acólito',
  harpy_squire: 'harpía escudeiro',
  ice_imp_larva: 'imp de gelo larval',
  ice_tick_junior: 'carrapato de gelo jovem',
  imp_runt: 'imp nanico',
  iron_boar_cadet: 'javali de ferro cadete',
  iron_tick_rookie: 'carrapato de ferro novato',
  ivory_skeleton_page: 'esqueleto de marfim escudeiro',
  kelp_newt_acolyte: 'tritão de algas acólito',
  kelp_strider_squire: 'caminhante de algas escudeiro',
  kobold_larva: 'kobold larval',
  lantern_spirit_junior: 'espírito da lanterna jovem',
  magma_grub_runt: 'larva de magma nanico',
  mangrove_croco_cadet: 'crocodilo do mangue cadete',
  marsh_imp_rookie: 'imp do pântano novato',
  marsh_lurker_page: 'espreitador do pântano escudeiro',
  minotaur_acolyte: 'minotauro acólito',
  mire_slug_squire: 'lesma do lodo escudeiro',
  mist_imp_larva: 'imp da névoa larval',
  mist_wisp_junior: 'fogo-fátuo da névoa jovem',
  moss_newt_runt: 'tritão de musgo nanico',
  moss_sprite_cadet: 'sprite do musgo cadete',
  mummy_rookie: 'múmia novato',
  mushroom_brute_page: 'ogro-cogumelo escudeiro',
  night_owl_acolyte: 'coruja noturna acólito',
  night_panther_squire: 'pantera noturna escudeiro',
  onyx_beetle_larva: 'besouro de ônix larval',
  aurora_moth_veteran: 'mariposa da aurora veterano',
  bandit_champion: 'bandido campeão',
  bark_spider_sentinel: 'aranha-casca sentinela',
  bat_raider: 'morcego saqueador',
  blood_leech_marshal: 'sanguessuga marechal',
  blood_mite_prime: 'ácaro de sangue élite',
  boar_piglet_guardian: 'javali leitão guardião',
  bog_finch_warder: 'tentilhão do pântano protetor',
  bog_mosquito_veteran: 'mosquito do pântano veterano',
  bog_newt_champion: 'tritão do pântano campeão',
  bone_picker_sentinel: 'catador de ossos sentinela',
  bone_shardling_raider: 'fragmento ósseo saqueador',
  bramble_boar_marshal: 'javali de sarças marechal',
  brimstone_imp_prime: 'imp de enxofre élite',
  brine_crab_guardian: 'caranguejo salgado guardião',
  carrion_vulture_warder: 'abutre carniceiro protetor',
  cave_bat_swarm_veteran: 'enxame de morcegos veterano',
  cave_crawler_champion: 'rastejante das cavernas campeão',
  cave_troll_sentinel: 'troll das cavernas sentinela',
  chalk_imp_raider: 'imp de giz saqueador',
  cinder_moth_marshal: 'mariposa de cinzas marechal',
  cinder_sprite_prime: 'sprite de cinzas élite',
  cinder_toad_guardian: 'sapo de brasas guardião',
  clay_soldier_warder: 'soldado de barro protetor',
  cliff_goat_veteran: 'cabra do penhasco veterano',
  copper_goblin_champion: 'goblin de cobre campeão',
  copper_tick_sentinel: 'carrapato de cobre sentinela',
  coral_crab_raider: 'caranguejo de coral saqueador',
  coral_crab_hatch_marshal: 'caranguejo de coral filhote marechal',
  coral_snake_prime: 'serpente de coral élite',
  coral_urchin_guardian: 'ouriço de coral guardião',
  crab_warder: 'caranguejo protetor',
  crystal_bat_veteran: 'morcego de cristal veterano',
  crystal_finch_champion: 'tentilhão de cristal campeão',
  crystal_mite_sentinel: 'ácaro de cristal sentinela',
  cultist_raider: 'cultista saqueador',
  cyclops_marshal: 'ciclope marechal',
  driftwood_crab_prime: 'caranguejo de madeira élite',
  dune_jackal_guardian: 'chacal das dunas guardião',
  dune_scarab_warder: 'escaravelho das dunas protetor',
  dune_viper_veteran: 'víbora das dunas veterano',
  dusk_ferret_champion: 'furão do crepúsculo campeão',
  dust_jackal_sentinel: 'chacal de pó sentinela',
  dust_mephit_raider: 'mefite de pó saqueador',
  dwarf_guard_marshal: 'anão guardião marechal',
  elf_prime: 'elfo élite',
  ember_gnat_guardian: 'mosquito de brasas guardião',
  ember_vole_warder: 'arganaz de brasas protetor',
  fog_hare_veteran: 'lebre da névoa veterano',
  fox_trickster_champion: 'raposa trapaceira campeão',
  frogman_sentinel: 'homem-sapo sentinela',
  frogman_poliwog_raider: 'homem-sapo girino saqueador',
  frost_gnat_marshal: 'mosquito glacial marechal',
  frost_sprite_prime: 'sprite glacial élite',
  frost_toad_guardian: 'sapo glacial guardião',
  frost_vole_warder: 'arganaz glacial protetor',
  gargoyle_veteran: 'gárgula veterano',
  geyser_toad_champion: 'sapo do gêiser campeão',
  ghoul_sentinel: 'carniçal sentinela',
  giant_toad_raider: 'sapo gigante saqueador',
  glacier_imp_marshal: 'imp glacial marechal',
  glacier_mite_prime: 'ácaro glacial élite',
  glass_imp_guardian: 'imp de vidro guardião',
  glint_pixie_warder: 'pixie reluzente protetor',
  blood_leech_tyrant: 'sanguessuga tirano',
  blood_mite_colossus: 'ácaro de sangue colosso',
  boar_piglet_patriarch: 'javali leitão patriarca',
  bog_finch_matriarch: 'tentilhão do pântano matriarca',
  bog_mosquito_duke: 'mosquito do pântano duque',
  bog_newt_baron: 'tritão do pântano barão',
  bone_picker_ascendant: 'catador de ossos ascendente',
  bone_shardling_paragon: 'fragmento ósseo paragão',
  bramble_boar_tyrant: 'javali de sarças tirano',
  brimstone_imp_colossus: 'imp de enxofre colosso',
  brine_crab_patriarch: 'caranguejo salgado patriarca',
  carrion_vulture_matriarch: 'abutre carniceiro matriarca',
  cave_bat_swarm_duke: 'enxame de morcegos duque',
  cave_crawler_baron: 'rastejante das cavernas barão',
  cave_troll_ascendant: 'troll das cavernas ascendente',
  chalk_imp_paragon: 'imp de giz paragão',
  cinder_moth_tyrant: 'mariposa de cinzas tirano',
  cinder_sprite_colossus: 'sprite de cinzas colosso',
  cinder_toad_patriarch: 'sapo de brasas patriarca',
  clay_soldier_matriarch: 'soldado de barro matriarca',
  cliff_goat_duke: 'cabra do penhasco duque',
  copper_goblin_baron: 'goblin de cobre barão',
  copper_tick_ascendant: 'carrapato de cobre ascendente',
  coral_crab_paragon: 'caranguejo de coral paragão',
  coral_crab_hatch_tyrant: 'caranguejo de coral filhote tirano',
  coral_snake_colossus: 'serpente de coral colosso',
  coral_urchin_patriarch: 'ouriço de coral patriarca',
  crab_matriarch: 'caranguejo matriarca',
  crystal_bat_duke: 'morcego de cristal duque',
  crystal_finch_baron: 'tentilhão de cristal barão',
  crystal_mite_ascendant: 'ácaro de cristal ascendente',
  cultist_paragon: 'cultista paragão',
  cyclops_tyrant: 'ciclope tirano',
  driftwood_crab_colossus: 'caranguejo de madeira colosso',
  dune_jackal_patriarch: 'chacal das dunas patriarca',
  dune_scarab_matriarch: 'escaravelho das dunas matriarca',
  dune_viper_duke: 'víbora das dunas duque',
  dusk_ferret_baron: 'furão do crepúsculo barão',
  dust_jackal_ascendant: 'chacal de pó ascendente',
  dust_mephit_paragon: 'mefite de pó paragão',
  // Expansão 7 +18
  glass_wisp: 'fogo-fátuo de vidro',
  peat_boar: 'javali de turfa',
  rust_golem: 'golem de ferrugem',
  lantern_moth: 'mariposa-lanterna',
  brine_eel: 'enguia salgada',
  spore_toad: 'sapo de esporos',
  flint_imp: 'imp de sílex',
  hail_raven: 'corvo de granizo',
  root_hound: 'cão-raiz',
  mirror_sprite: 'sprite-espelho',
  kiln_scarab: 'escaravelho do forno',
  void_newt: 'tritão do vazio',
  thunder_ibex: 'íbex do trovão',
  coral_medusa: 'medusa de coral',
  ember_knight: 'cavaleiro de brasas',
  frost_colossus: 'colosso de geada',
  nightbloom_hydra: 'hidra flor-da-noite',
  starfall_oracle: 'oráculo da queda estelar',
  // Expansão 8 +300
  furnace_snake: 'serpente fornalha',
  hail_crab: 'caranguejo granizo',
  blizzard_vole: 'arganaz nevasca',
  peat_jackal: 'chacal turfa',
  reed_ibex: 'íbex junco',
  sand_ape: 'macaco areia',
  mirage_finch: 'tentilhão miragem',
  vine_fly: 'mosca cipó',
  pine_sprite_2: 'sprite pinheiro',
  cave_gremlin: 'gremlin caverna',
  quartz_troll: 'troll quartzo',
  grave_construct: 'constructo túmulo',
  ghoul_mage: 'mago carniçal',
  tide_assassin: 'assassino maré',
  kelp_raider: 'saqueador alga',
  storm_mummy: 'múmia tempestade',
  cloud_whelp: 'filhote nuvem',
  prism_sphinx: 'esfinge prisma',
  jade_krakenling: 'krakenzinho jade',
  shadow_dryad: 'dríade sombra',
  night_cyclops_cub: 'ciclope filhote noite',
  rune_familiar: 'familiar runa',
  oracle_chanter: 'cantor oráculo',
  iron_berserker: 'berserker ferro',
  bronze_swarmer: 'enxame bronze',
  ivory_cub: 'filhote marfim',
  violet_brute: 'bruto violeta',
  scarlet_stinger: 'ferrão escarlate',
  gloom_haunter: 'assombrador treva',
  feral_piercer: 'perfurador feroz',
  fallen_freezer: 'congelador caído',
  rot_weaver: 'tecelão podridão',
  lava_diver: 'mergulhador lava',
  marble_glider: 'planador mármore',
  mist_prophet: 'profeta névoa',
  plasma_savant: 'erudito plasma',
  stellar_jailer: 'carcereiro estelar',
  blood_zealot: 'fanático sangue',
  dream_exile: 'exilado sonho',
  warp_tick: 'carrapato distorção',
  nether_slug: 'lesma nether',
  sharp_snake: 'serpente afiado',
  howling_crab: 'caranguejo uivante',
  echo_vole: 'arganaz eco',
  surge_jackal: 'chacal surto',
  rusted_ibex: 'íbex enferrujado',
  burning_ape: 'macaco ardente',
  twisted_finch: 'tentilhão torcido',
  shard_fly: 'mosca fragmento',
  fang_sprite: 'sprite presa',
  scale_gremlin: 'gremlin escama',
  crown_troll: 'troll coroa',
  torch_construct: 'constructo tocha',
  drum_mage: 'mago tambor',
  cinder_assassin: 'assassino cinza',
  magma_raider: 'saqueador magma',
  kiln_mummy: 'múmia forno',
  glacier_whelp: 'filhote geleira',
  arctic_sphinx: 'esfinge ártico',
  bog_krakenling: 'krakenzinho pântano',
  fungal_dryad: 'dríade fúngico',
  dune_cyclops_cub: 'ciclope filhote duna',
  dust_familiar: 'familiar pó',
  thorn_chanter: 'cantor espinho',
  bark_berserker: 'berserker casca',
  root_swarmer: 'enxame raiz',
  granite_cub: 'filhote granito',
  tunnel_brute: 'bruto túnel',
  crypt_stinger: 'ferrão cripta',
  plague_haunter: 'assombrador praga',
  coral_piercer: 'perfurador coral',
  reef_freezer: 'congelador recife',
  thunder_weaver: 'tecelão trovão',
  zephyr_diver: 'mergulhador zéfiro',
  glass_glider: 'planador vidro',
  ruby_prophet: 'profeta rubi',
  dusk_savant: 'erudito crepúsculo',
  hex_jailer: 'carcereiro hex',
  idol_zealot: 'fanático ídolo',
  arcane_exile: 'exilado arcano',
  copper_tick_2: 'carrapato cobre',
  crimson_slug: 'lesma carmesim',
  amber_snake: 'serpente âmbar',
  verdant_crab: 'caranguejo verdejante',
  hollow_vole: 'arganaz oco',
  wild_jackal: 'chacal selvagem',
  elder_ibex: 'íbex ancião',
  blight_ape: 'macaco praga',
  venom_finch: 'tentilhão veneno',
  slate_fly: 'mosca ardósia',
  ink_sprite: 'sprite tinta',
  spark_gremlin: 'gremlin faísca',
  lunar_troll: 'troll lunar',
  doom_construct: 'constructo perdição',
  spirit_mage: 'mago espírito',
  rift_assassin: 'assassino fenda',
  aether_raider: 'saqueador éter',
  raw_mummy: 'múmia bruto',
  silent_whelp: 'filhote silencioso',
  whisper_sphinx: 'esfinge sussurro',
  flux_krakenling: 'krakenzinho fluxo',
  gilded_dryad: 'dríade dourado',
  frozen_cyclops_cub: 'ciclope filhote congelado',
  laughing_familiar: 'familiar ríspido',
  splinter_chanter: 'cantor estilhaço',
  claw_berserker: 'berserker garra',
  wing_swarmer: 'enxame asa',
  mask_cub: 'filhote máscara',
  blade_brute: 'bruto lâmina',
  bell_stinger: 'ferrão sino',
  dirge_haunter: 'assombrador réquiem',
  pyre_piercer: 'perfurador pira',
  soot_freezer: 'congelador fuligem',
  frost_weaver: 'tecelão geada',
  rime_diver: 'mergulhador geada',
  mire_glider: 'planador lodo',
  spore_prophet: 'profeta esporo',
  marsh_savant: 'erudito charco',
  salt_jailer: 'carcereiro sal',
  oasis_zealot: 'fanático oásis',
  moss_exile: 'exilado musgo',
  bloom_tick: 'carrapato flor',
  shale_slug: 'lesma folhelho',
  obsidian_snake: 'serpente obsidiana',
  bone_crab: 'caranguejo osso',
  wraith_vole: 'arganaz espectro',
  brine_jackal: 'chacal salmoura',
  abyss_ibex: 'íbex abismo',
  gale_ape: 'macaco vendaval',
  aurora_finch: 'tentilhão aurora',
  crystal_fly: 'mosca cristal',
  sapphire_sprite: 'sprite safira',
  void_gremlin: 'gremlin vazio',
  eclipse_troll: 'troll eclipse',
  temple_construct: 'constructo templo',
  sacred_mage: 'mago sagrado',
  scrap_assassin: 'assassino sucata',
  ashen_raider: 'saqueador acinzentado',
  onyx_mummy: 'múmia ônix',
  azure_whelp: 'filhote azul',
  pale_sphinx: 'esfinge pálido',
  bright_krakenling: 'krakenzinho luminoso',
  ancient_dryad: 'dríade ancestral',
  cursed_cyclops_cub: 'ciclope filhote amaldiçoado',
  blizzard_scarab_chief: 'escaravelho nevasca chefe',
  marsh_fish_overseer: 'peixe charco supervisor',
  thorn_fox_raider: 'raposa espinho saqueador',
  cave_ape_enraged: 'macaco caverna enraivecido',
  bone_spider_savage: 'aranha osso selvagem',
  coral_kobold_dawn: 'kobold coral alvorada',
  cloud_knight_venomous: 'cavaleiro nuvem venenoso',
  sapphire_scout_frozen: 'batedor safira congelado',
  hex_whelp_necrotic: 'filhote hex necrótico',
  iron_leviathan_cub_raid: 'leviatã filhote ferro de raid',
  onyx_efreet_matron: 'efreet ônix matrona',
  hollow_monk_broodmother: 'monge oco mãe da ninhada',
  fallen_hatchling_hexer: 'filhote caído amaldiçoador',
  coal_stinger_prime: 'ferrão carvão primordial',
  spark_bombardier_blessed: 'bombardeiro faísca abençoado',
  blood_smith_ironbound: 'ferreiro sangue preso em ferro',
  chrono_trickster_runic: 'trapaceiro crono rúnico',
  silent_keeper_abyssal: 'guarda silencioso abissal',
  surge_exile_war: 'exilado surto de guerra',
  weeping_snail_captain: 'caracol choroso capitão',
  claw_jellyfish_champion: 'água-viva garra campeão',
  crown_panther_sentinel: 'pantera coroa sentinela',
  choir_hawk_armored: 'falcão coro blindado',
  soot_sprite_dire: 'sprite fuligem terrível',
  arctic_ogre_midnight: 'ogro ártico meia-noite',
  reed_priest_blooded: 'sacerdote junco sangrento',
  oasis_skeleton_ashen: 'esqueleto oásis acinzentado',
  root_naga_infernal: 'naga raiz infernal',
  grave_dryad_siege: 'dríade túmulo de cerco',
  brine_puppet_alpha: 'marionete salmoura alfa',
  thunder_stalker_packlord: 'perseguidor trovão senhor da matilha',
  jade_fledgling_stalker: 'filhote jade perseguidor',
  eclipse_whisperer_ascendant: 'sussurrador eclipse ascendente',
  arcane_freezer_cursed: 'congelador arcano amaldiçoado',
  ivory_sailor_stormforged: 'marinheiro marfim forjado na tempestade',
  pale_acolyte_arcane: 'acólito pálido arcano',
  elder_judge_molten: 'juiz ancião fundido',
  lava_mite_primal: 'ácaro lava primitivo',
  fog_snake_veteran: 'serpente neblina veterano',
  doom_ferret_warden: 'furão perdição guardião',
  warp_ram_hierophant: 'carneiro distorção hierofante',
  jagged_drone_blighted: 'zangão serrilhado corrompido',
  flux_mephit_greater: 'mefite fluxo maior',
  burning_construct_twilight: 'constructo ardente crepuscular',
  spike_duelist_soulbound: 'duelista espeto preso à alma',
  mask_specter_crystalbound: 'fantasma máscara cristalino',
  drum_chimera_celestial: 'quimera tambor celestial',
  brimstone_minotaurling_battle: 'minotauro jovem enxofre de batalha',
  rime_chanter_chief: 'cantor geada chefe',
  fungal_swarm_overseer: 'enxame fúngico supervisor',
  mirage_smasher_raider: 'destruidor miragem saqueador',
  bloom_ripper_enraged: 'rasgador flor enraivecido',
  tunnel_binder_savage: 'amarrador túnel selvagem',
  tide_glider_dawn: 'planador maré alvorada',
  gale_archivist_venomous: 'arquivista vendaval venenoso',
  glass_martyr_frozen: 'mártir vidro congelado',
  night_grub_necrotic: 'larva noite necrótico',
  sacred_shark_raid: 'tubarão sagrado de raid',
  crimson_jackal_matron: 'chacal carmesim matrona',
  scarlet_bat_broodmother: 'morcego escarlate mãe da ninhada',
  ancient_mantis_hexer: 'louva-a-deus ancestral amaldiçoador',
  venom_gnoll_prime: 'gnoll veneno primordial',
  mist_archer_blessed: 'arqueiro névoa abençoado',
  chaos_raider_ironbound: 'saqueador caos preso em ferro',
  rift_drake_runic: 'draco fenda rúnico',
  sharp_phoenixling_abyssal: 'fênix filhote afiado abissal',
  pulse_marid_war: 'marid pulso de guerra',
  frozen_paladin_captain: 'paladino congelado capitão',
  shard_cub_champion: 'filhote fragmento campeão',
  shell_biter_sentinel: 'mordedor concha sentinela',
  bell_spitter_armored: 'cuspidor sino blindado',
  magma_forger_dire: 'forjador magma terrível',
  hail_oracle_midnight: 'oráculo granizo meia-noite',
  spore_jailer_blooded: 'carcereiro esporo sangrento',
  dust_outcast_ashen: 'pária pó acinzentado',
  pine_newt_infernal: 'tritão pinheiro infernal',
  obsidian_ray_siege: 'arraia obsidiana de cerco',
  plague_boar_alpha: 'javali praga alfa',
  storm_finch_packlord: 'tentilhão tempestade senhor da matilha',
  crystal_pixie_stalker: 'pixie cristal perseguidor',
  dusk_giant_ascendant: 'gigante crepúsculo ascendente',
  oracle_cultist_cursed: 'cultista oráculo amaldiçoado',
  ashen_zombie_stormforged: 'zumbi acinzentado forjado na tempestade',
  verdant_sphinx_arcane: 'esfinge verdejante arcano',
  feral_nymph_molten: 'ninfa feroz fundido',
  toxic_doll_primal: 'boneca tóxico primitivo',
  ink_lurker_veteran: 'espreitador tinta veterano',
  stellar_juvenile_warden: 'jovem estelar guardião',
  nightmare_haunter_hierophant: 'assombrador pesadelo hierofante',
  raw_burner_blighted: 'queimador bruto corrompido',
  echo_rider_greater: 'cavaleiro eco maior',
  molten_initiate_twilight: 'iniciado fundido crepuscular',
  splinter_inquisitor_soulbound: 'inquisidor estilhaço preso à alma',
  scale_tick_crystalbound: 'carrapato escama cristalino',
  lantern_viper_celestial: 'víbora lanterna celestial',
  pyre_weasel_battle: 'doninha pira de batalha',
  reed_urchin_emperor: 'ouriço junco imperador',
  vine_boar_overlord: 'javali cipó suserano',
  quartz_wasp_colossus: 'vespa quartzo colosso',
  tide_gremlin_primordial: 'gremlin maré primordial',
  cloud_knight_harbinger: 'cavaleiro nuvem presságio',
  shadow_bandit_eternal: 'bandido sombra eterno',
  oracle_naga_voidborn: 'naga oráculo nascido do vazio',
  ivory_satyr_deathlord: 'sátiro marfim senhor da morte',
  gloom_chanter_stormqueen: 'cantor treva rainha da tempestade',
  rot_spawn_boneking: 'cria podridão rei dos ossos',
  mist_biter_skymother: 'mordedor névoa mãe dos céus',
  blood_shocker_sunscorch: 'eletrizante sangue queimadura solar',
  nether_rider_entropy: 'cavaleiro nether entropia',
  echo_savant_worldbreaker: 'erudito eco quebrador de mundos',
  burning_pilgrim_hellcrown: 'peregrino ardente coroa do inferno',
  fang_snail_ironthrone: 'caracol presa trono de ferro',
  torch_rat_paragon: 'rato tocha paragão',
  magma_ram_alpha_prime: 'carneiro magma alfa primordial',
  arctic_fly_mythic: 'mosca ártico mítico',
  dune_gnoll_profane: 'gnoll duna profano',
  bark_witch_empress: 'bruxa casca imperatriz',
  tunnel_zombie_matriarch: 'zumbi túnel matriarca',
  coral_harpy_behemoth: 'harpía coral beemote',
  zephyr_cyclops_cub_avatar: 'ciclope filhote zéfiro avatar',
  dusk_monk_apocalypse: 'monge crepúsculo apocalipse',
  arcane_pup_infinite: 'filhote arcano infinito',
  amber_whisperer_starborn: 'sussurrador âmbar nascido das estrelas',
  wild_poisoner_flametyrant: 'envenenador selvagem tirano das chamas',
  venom_glider_plagueking: 'planador veneno rei da praga',
  spark_ward_ashenlord: 'guardião faísca senhor das cinzas',
  spirit_outcast_crystalheart: 'pária espírito coração de cristal',
  raw_frog_moonfall: 'rã bruto queda lunar',
  flux_weasel_chaosborn: 'doninha fluxo nascido do caos',
  laughing_ape_soulreaper: 'macaco ríspido ceifador de almas',
  wing_scorpion_abysscrown: 'escorpião asa coroa do abismo',
  bell_ogre_forgemaster: 'ogro sino mestre da forja',
  soot_alchemist_apex: 'alquimista fuligem ápice',
  mire_specter_final: 'fantasma lodo final',
  salt_krakenling_legendary: 'krakenzinho sal lendário',
  bloom_marid_sovereign: 'marid flor soberano',
  bone_reaver_tyrant: 'devastador osso tirano',
  abyss_juvenile_patriarch: 'jovem abismo patriarca',
  crystal_mangler_leviathan: 'dilacerador cristal leviatã',
  eclipse_weaver_herald: 'tecelão eclipse arauto',
  scrap_trickster_cataclysm: 'trapaceiro sucata cataclismo',
  azure_torturer_world: 'torturador azul do mundo',
  ancient_mite_doomlord: 'ácaro ancestral senhor da perdição',
  coal_eel_frostking: 'enguia carvão rei da geada',
  solar_jackal_bloodqueen: 'chacal solar rainha do sangue',
  nightmare_raven_tidefather: 'corvo pesadelo pai das marés',
  jagged_pixie_nightcrown: 'pixie serrilhado coroa da noite',
  rifted_elemental_riftwalker: 'elemental rachado caminhante da fenda',
  gnarled_warden_endbringer: 'guardião retorcido trazedor do fim',
  shell_whelp_graveking: 'filhote concha rei das tumbas',
  choir_treantling_jadeempire: 'treantzinho coro império de jade',
  furnace_puppet_archon: 'marionete fornalha arconte',
  peat_crawler_omega: 'rastejante turfa ômega',
  mirage_smasher_ultimate: 'destruidor miragem supremo',
  cave_piercer_divine: 'perfurador caverna divino',
  ghoul_forger_emperor: 'forjador carniçal imperador',
};

export function monsterLabel(type) {
  if (!type) return 'Monstro';
  const known = MONSTER_LABELS[type];
  if (known) return known;
  // Fallback legível: id com underscore → palavras
  return String(type)
    .split('_')
    .filter(Boolean)
    .join(' ');
}
