/** Nomes de exibição (PT) dos tipos de monstro. */
export const MONSTER_LABELS = {
  imp: 'imp',
  slime: 'slime',
  wraith: 'espectro',
  goblin: 'goblin',
  orc: 'orc',
  skeleton: 'esqueleto',
  skeleton_archer: 'esqueleto arqueiro',
  wolf: 'lobo',
  giant_spider: 'aranha gigante',
  bat: 'morcego',
  elf: 'elfo',
  beholder: 'beholder',
  dragon: 'dragão',
  lich: 'lich',
  fire_elemental: 'elemental de fogo',
  demon: 'demônio',
  grim_reaper: 'ceifador',
  bruxo: 'bruxo',
  cyclops: 'ciclope',
  minotaur: 'minotauro',
  harpy: 'harpía',
  kobold: 'kobold',
  zombie: 'zumbi',
  mummy: 'múmia',
  ghoul: 'carniçal',
  ratman: 'homem-rato',
  scorpion: 'escorpião',
  venom_snake: 'serpente venenosa',
  cultist: 'cultista',
  gargoyle: 'gárgula',
  pixie: 'pixie',
  dwarf_guard: 'anão guardião',
  bandit: 'bandido',
  pirate: 'pirata',
  giant_toad: 'sapo gigante',
  wasp: 'vespa',
  crab: 'caranguejo',
  yeti_cub: 'yeti jovem',
  shadow_wolf: 'lobo sombrio',
  cave_troll: 'troll das cavernas',
  swamp_slug: 'lesma do pântano',
  desert_scavenger: 'necrófago do deserto',
  gnoll: 'gnoll',
  ice_imp: 'imp de gelo',
  ancient_scarab: 'escaravelho antigo',
  death_knight: 'cavaleiro da morte',
  frost_mage: 'mago do gelo',
  venom_hydra: 'hidra venenosa',
  stone_golem: 'golem de pedra',
  blood_succubus: 'súcubo de sangue',
  nightmare_steed: 'corcel do pesadelo',
  bone_whelp: 'filhote ósseo',
  abyss_watcher: 'vigia do abismo',
  crystal_elemental: 'elemental de cristal',
  plague_doctor: 'médico da praga',
  war_troll: 'troll de guerra',
  shadow_assassin: 'assassino sombrio',
  storm_elemental: 'elemental da tempestade',
  magma_golem: 'golem de magma',
  forest_guardian: 'guardião da floresta',
  void_stalker: 'caçador do vazio',
  ice_wyrm: 'serpe de gelo',
  necromancer: 'necromante',
  frost_dragon: 'dragão de gelo',
  bone_dragon: 'dragão ósseo',
  kraken: 'kraken',
  hydra_boss: 'hidra ancestral',
  medusa: 'medusa',
  phoenix: 'fênix',
  titan: 'titã',
  void_lord: 'senhor do vazio',
  ancient_treant: 'treant ancestral',
  sand_worm: 'verme das areias',
  flame_lord: 'senhor das chamas',
  frost_lich: 'lich glacial',
  plague_queen: 'rainha da praga',
  storm_giant: 'gigante da tempestade',
  cerberus: 'cérbero',
  basilisk: 'basilisco',
  djinn: 'djinn',
  archdemon: 'arquidemônio',
  world_serpent: 'serpente do mundo',
  frogman: 'homem-sapo',
  porcupine: 'porco-espinho',
  dune_viper: 'víbora das dunas',
  moss_sprite: 'sprite do musgo',
  scrap_golem: 'golem de sucata',
  raven_scout: 'corvo batedor',
  bog_witch_apprentice: 'aprendiz do pântano',
  crystal_bat: 'morcego de cristal',
  iron_boar: 'javali de ferro',
  sand_archer: 'arqueiro das areias',
  frost_sprite: 'sprite glacial',
  cave_crawler: 'rastejante das cavernas',
  marsh_lurker: 'espreitador do pântano',
  ember_whelp: 'filhote de brasa',
  bone_picker: 'catador de ossos',
  thorn_bush: 'arbusto espinhoso',
  ash_rat: 'rato de cinzas',
  coral_crab: 'caranguejo de coral',
  wind_sylph: 'sílfide do vento',
  tomb_guard: 'guardião do túmulo',
  spore_fungus: 'fungo esporado',
  glacier_cub: 'filhote glacial',
  night_owl: 'coruja noturna',
  brimstone_imp: 'imp de enxofre',
  reed_stalker: 'espreitador dos juncos',
  thunder_hawk: 'falcão do trovão',
  blood_ogre: 'ogro sangrento',
  mirage_dancer: 'dançarina da miragem',
  frost_berserker: 'berserker glacial',
  venom_alchemist: 'alquimista venenoso',
  obsidian_guardian: 'guardião de obsidiana',
  soul_harvester: 'ceifador de almas',
  lava_serpent: 'serpente de lava',
  mirror_wraith: 'espectro espelhado',
  plague_rat_king: 'rei dos ratos da praga',
  storm_rider: 'cavaleiro da tempestade',
  ironbark_treant: 'treant de casca-ferro',
  crimson_cultist: 'cultista carmesim',
  void_imp_lord: 'senhor dos imps do vazio',
  sapphire_drake: 'dragão de safira',
  eclipse_sphinx: 'esfinge do eclipse',
  magma_colossus: 'colosso de magma',
  arctic_leviathan: 'leviatã ártico',
  blight_emperor: 'imperador da praga',
  chronomancer: 'cronomante',
  dread_naga: 'naga do pavor',
  solar_phoenix: 'fênix solar',
  abyssal_kraken: 'kraken abissal',
  bone_emperor: 'imperador ósseo',
  world_ender: 'fim do mundo',
  mushroom_brute: 'ogro-cogumelo',
  salt_golem: 'golem de sal',
  fox_trickster: 'raposa trapaceira',
  quill_hunter: 'caçador de espinhos',
  peat_zombie: 'zumbi de turfa',
  lantern_spirit: 'espírito da lanterna',
  cliff_goat: 'cabra do penhasco',
  reef_shark: 'tubarão do recife',
  dust_mephit: 'mefite de pó',
  bark_spider: 'aranha-casca',
  snow_hare: 'lebre da neve',
  torch_bearer: 'portador da tocha',
  bog_mosquito: 'mosquito do pântano',
  rune_scribe: 'escriba rúnico',
  clay_soldier: 'soldado de barro',
  pearl_diver: 'mergulhador de pérolas',
  night_panther: 'pantera noturna',
  hive_drone: 'zangão da colmeia',
  frost_toad: 'sapo glacial',
  scrap_bandit: 'bandido de sucata',
  vine_creeper: 'cipó rastejante',
  cinder_sprite: 'sprite de cinzas',
  tunnel_mole: 'toupeira de túnel',
  glass_imp: 'imp de vidro',
  thunder_boar: 'javali do trovão',
  blood_knight: 'cavaleiro sangrento',
  sand_djinni: 'djinn das areias',
  poison_archer: 'arqueiro venenoso',
  jade_golem: 'golem de jade',
  shadow_priest: 'sacerdote das sombras',
  bladed_mantis: 'louva-a-deus laminado',
  storm_witch: 'bruxa da tempestade',
  furnace_beast: 'fera da fornalha',
  crystal_archer: 'arqueiro de cristal',
  void_hound: 'cão do vazio',
  plague_swarm: 'enxame da praga',
  iron_sentinel: 'sentinela de ferro',
  aurora_mage: 'mago da aurora',
  ash_wyvern: 'wyvern de cinzas',
  bone_reaver: 'ceifador ósseo',
  tempest_queen: 'rainha da tempestade',
  forge_titan: 'titã da forja',
  coral_empress: 'imperatriz de coral',
  nightmare_king: 'rei do pesadelo',
  elder_beholder: 'beholder ancião',
  doom_hydra: 'hidra da perdição',
  astral_serpent: 'serpente astral',
  war_god_avatar: 'avatar do deus da guerra',
  necrotic_colossus: 'colosso necrótico',
  chaos_primordial: 'primordial do caos',
  pebble_sprite: 'sprite de pedra',
  reed_rat: 'rato dos juncos',
  tide_urchin: 'ouriço da maré',
  cinder_moth: 'mariposa de cinzas',
  pine_sprite: 'sprite do pinheiro',
  copper_goblin: 'goblin de cobre',
  mist_wisp: 'fogo-fátuo da névoa',
  brine_crab: 'caranguejo salgado',
  soot_imp: 'imp de fuligem',
  thistle_boar: 'javali de cardos',
  kelp_strider: 'caminhante de algas',
  ember_gnat: 'mosquito de brasas',
  chalk_golem_cub: 'golem de giz jovem',
  dusk_ferret: 'furão do crepúsculo',
  bog_newt: 'tritão do pântano',
  crystal_mite: 'ácaro de cristal',
  rust_scorpion: 'escorpião enferrujado',
  pollen_pixie: 'pixie de pólen',
  shale_basher: 'espancador de xisto',
  frost_vole: 'arganaz glacial',
  tar_slug: 'lesma de piche',
  spark_sprite: 'sprite de faísca',
  dune_jackal: 'chacal das dunas',
  lichen_troll_cub: 'troll de líquen jovem',
  ivory_skeleton: 'esqueleto de marfim',
  mangrove_croco: 'crocodilo do mangue',
  storm_finch: 'tentilhão da tempestade',
  ash_cult_initiate: 'iniciado do culto das cinzas',
  prism_moth: 'mariposa prismática',
  geyser_toad: 'sapo do gêiser',
  carrion_vulture: 'abutre carniceiro',
  magma_grub: 'larva de magma',
  void_mote: 'partícula do vazio',
  salt_wraith: 'espectro de sal',
  iron_tick: 'carrapato de ferro',
  glacier_imp: 'imp glacial',
  thorn_imp: 'imp de espinhos',
  cave_bat_swarm: 'enxame de morcegos',
  scrap_wolf: 'lobo de sucata',
  coral_snake: 'serpente de coral',
  rune_imp: 'imp rúnico',
  peat_slime: 'slime de turfa',
  wind_razor: 'lâmina do vento',
  blood_leech: 'sanguessuga',
  frost_archer_novice: 'arqueiro glacial novato',
  shade_larva: 'larva das sombras',
  pyre_cultist: 'cultista da pira',
  quartz_beetle: 'besouro de quartzo',
  acid_alchemist: 'alquimista ácido',
  frost_wyvern: 'wyvern glacial',
  bone_chanter: 'encantador ósseo',
  hex_witch: 'bruxa do hex',
  magma_brute: 'bruto de magma',
  storm_centurion: 'centurião da tempestade',
  obsidian_raptor: 'raptor de obsidiana',
  venom_naga: 'naga venenosa',
  crystal_guardian: 'guardião de cristal',
  shadow_duelist: 'duelista sombrio',
  pyre_drake: 'drake da pira',
  glacier_knight: 'cavaleiro glacial',
  plague_harpy: 'harpía da praga',
  rune_golem: 'golem rúnico',
  blood_panther: 'pantera sangrenta',
  arcane_archer: 'arqueiro arcano',
  furnace_golem: 'golem da fornalha',
  void_serpent: 'serpente do vazio',
  jade_monk: 'monge de jade',
  thunder_drake: 'drake do trovão',
  mirror_knight: 'cavaleiro espelhado',
  blight_treant: 'treant da praga',
  ash_assassin: 'assassino de cinzas',
  sapphire_witch: 'bruxa de safira',
  iron_hydra: 'hidra de ferro',
  soul_thief: 'ladrão de almas',
  cinder_titan_spawn: 'cria do titã de brasas',
  aurora_serpent: 'serpente da aurora',
  grave_sentinel: 'sentinela da sepultura',
  night_reaver: 'ceifador noturno',
  ember_witch: 'bruxa de brasas',
  toxin_archer: 'arqueiro tóxico',
  acid_sovereign: 'soberano ácido',
  frost_empress: 'imperatriz glacial',
  bone_overlord: 'suserano ósseo',
  hex_archon: 'arconte do hex',
  magma_tyrant: 'tirano de magma',
  storm_colossus: 'colosso da tempestade',
  void_matriarch: 'matriarca do vazio',
  plague_sovereign: 'soberano da praga',
  solar_phoenix_lord: 'senhor da fênix solar',
  abyss_leviathan: 'leviatã abissal',
  jade_emperor: 'imperador de jade',
  crimson_warlord: 'senhor da guerra carmesim',
  necrotic_queen: 'rainha necrótica',
  entropy_dragon: 'dragão da entropia',
  iron_behemoth: 'beemote de ferro',
  mire_hydra_king: 'rei hidra do lodo',
  astral_tyrant: 'tirano astral',
  forge_emperor: 'imperador da forja',
  shadow_primordial: 'primordial das sombras',
  tide_kraken_lord: 'senhor kraken das marés',
};

export function monsterLabel(type) {
  return MONSTER_LABELS[type] || type;
}
