/** Nomes de exibição (PT) dos tipos de monstro. */
export const MONSTER_LABELS = {
  imp: 'imp',
  slime: 'slime',
  wraith: 'espectro',
  goblin: 'goblin',
  orc: 'orc',
  skeleton: 'esqueleto',
  skeleton_archer: 'esqueleto arqueiro',
  wolf: 'lobo',
  giant_spider: 'aranha gigante',
  bat: 'morcego',
  elf: 'elfo',
  beholder: 'beholder',
  dragon: 'dragão',
  lich: 'lich',
  fire_elemental: 'elemental de fogo',
  demon: 'demônio',
  grim_reaper: 'ceifador',
  bruxo: 'bruxo',
  cyclops: 'ciclope',
  minotaur: 'minotauro',
  harpy: 'harpía',
  kobold: 'kobold',
  zombie: 'zumbi',
  mummy: 'múmia',
  ghoul: 'carniçal',
  ratman: 'homem-rato',
  scorpion: 'escorpião',
  venom_snake: 'serpente venenosa',
  cultist: 'cultista',
  gargoyle: 'gárgula',
  pixie: 'pixie',
  dwarf_guard: 'anão guardião',
  bandit: 'bandido',
  pirate: 'pirata',
  giant_toad: 'sapo gigante',
  wasp: 'vespa',
  crab: 'caranguejo',
  yeti_cub: 'yeti jovem',
  shadow_wolf: 'lobo sombrio',
  cave_troll: 'troll das cavernas',
  swamp_slug: 'lesma do pântano',
  desert_scavenger: 'necrófago do deserto',
  gnoll: 'gnoll',
  ice_imp: 'imp de gelo',
  ancient_scarab: 'escaravelho antigo',
  death_knight: 'cavaleiro da morte',
  frost_mage: 'mago do gelo',
  venom_hydra: 'hidra venenosa',
  stone_golem: 'golem de pedra',
  blood_succubus: 'súcubo de sangue',
  nightmare_steed: 'corcel do pesadelo',
  bone_whelp: 'filhote ósseo',
  abyss_watcher: 'vigia do abismo',
  crystal_elemental: 'elemental de cristal',
  plague_doctor: 'médico da praga',
  war_troll: 'troll de guerra',
  shadow_assassin: 'assassino sombrio',
  storm_elemental: 'elemental da tempestade',
  magma_golem: 'golem de magma',
  forest_guardian: 'guardião da floresta',
  void_stalker: 'caçador do vazio',
  ice_wyrm: 'serpe de gelo',
  necromancer: 'necromante',
  frost_dragon: 'dragão de gelo',
  bone_dragon: 'dragão ósseo',
  kraken: 'kraken',
  hydra_boss: 'hidra ancestral',
  medusa: 'medusa',
  phoenix: 'fênix',
  titan: 'titã',
  void_lord: 'senhor do vazio',
  ancient_treant: 'treant ancestral',
  sand_worm: 'verme das areias',
  flame_lord: 'senhor das chamas',
  frost_lich: 'lich glacial',
  plague_queen: 'rainha da praga',
  storm_giant: 'gigante da tempestade',
  cerberus: 'cérbero',
  basilisk: 'basilisco',
  djinn: 'djinn',
  archdemon: 'arquidemônio',
  world_serpent: 'serpente do mundo',
  frogman: 'homem-sapo',
  porcupine: 'porco-espinho',
  dune_viper: 'víbora das dunas',
  moss_sprite: 'sprite do musgo',
  scrap_golem: 'golem de sucata',
  raven_scout: 'corvo batedor',
  bog_witch_apprentice: 'aprendiz do pântano',
  crystal_bat: 'morcego de cristal',
  iron_boar: 'javali de ferro',
  sand_archer: 'arqueiro das areias',
  frost_sprite: 'sprite glacial',
  cave_crawler: 'rastejante das cavernas',
  marsh_lurker: 'espreitador do pântano',
  ember_whelp: 'filhote de brasa',
  bone_picker: 'catador de ossos',
  thorn_bush: 'arbusto espinhoso',
  ash_rat: 'rato de cinzas',
  coral_crab: 'caranguejo de coral',
  wind_sylph: 'sílfide do vento',
  tomb_guard: 'guardião do túmulo',
  spore_fungus: 'fungo esporado',
  glacier_cub: 'filhote glacial',
  night_owl: 'coruja noturna',
  brimstone_imp: 'imp de enxofre',
  reed_stalker: 'espreitador dos juncos',
  thunder_hawk: 'falcão do trovão',
  blood_ogre: 'ogro sangrento',
  mirage_dancer: 'dançarina da miragem',
  frost_berserker: 'berserker glacial',
  venom_alchemist: 'alquimista venenoso',
  obsidian_guardian: 'guardião de obsidiana',
  soul_harvester: 'ceifador de almas',
  lava_serpent: 'serpente de lava',
  mirror_wraith: 'espectro espelhado',
  plague_rat_king: 'rei dos ratos da praga',
  storm_rider: 'cavaleiro da tempestade',
  ironbark_treant: 'treant de casca-ferro',
  crimson_cultist: 'cultista carmesim',
  void_imp_lord: 'senhor dos imps do vazio',
  sapphire_drake: 'dragão de safira',
  eclipse_sphinx: 'esfinge do eclipse',
  magma_colossus: 'colosso de magma',
  arctic_leviathan: 'leviatã ártico',
  blight_emperor: 'imperador da praga',
  chronomancer: 'cronomante',
  dread_naga: 'naga do pavor',
  solar_phoenix: 'fênix solar',
  abyssal_kraken: 'kraken abissal',
  bone_emperor: 'imperador ósseo',
  world_ender: 'fim do mundo',
  mushroom_brute: 'ogro-cogumelo',
  salt_golem: 'golem de sal',
  fox_trickster: 'raposa trapaceira',
  quill_hunter: 'caçador de espinhos',
  peat_zombie: 'zumbi de turfa',
  lantern_spirit: 'espírito da lanterna',
  cliff_goat: 'cabra do penhasco',
  reef_shark: 'tubarão do recife',
  dust_mephit: 'mefite de pó',
  bark_spider: 'aranha-casca',
  snow_hare: 'lebre da neve',
  torch_bearer: 'portador da tocha',
  bog_mosquito: 'mosquito do pântano',
  rune_scribe: 'escriba rúnico',
  clay_soldier: 'soldado de barro',
  pearl_diver: 'mergulhador de pérolas',
  night_panther: 'pantera noturna',
  hive_drone: 'zangão da colmeia',
  frost_toad: 'sapo glacial',
  scrap_bandit: 'bandido de sucata',
  vine_creeper: 'cipó rastejante',
  cinder_sprite: 'sprite de cinzas',
  tunnel_mole: 'toupeira de túnel',
  glass_imp: 'imp de vidro',
  thunder_boar: 'javali do trovão',
  blood_knight: 'cavaleiro sangrento',
  sand_djinni: 'djinn das areias',
  poison_archer: 'arqueiro venenoso',
  jade_golem: 'golem de jade',
  shadow_priest: 'sacerdote das sombras',
  bladed_mantis: 'louva-a-deus laminado',
  storm_witch: 'bruxa da tempestade',
  furnace_beast: 'fera da fornalha',
  crystal_archer: 'arqueiro de cristal',
  void_hound: 'cão do vazio',
  plague_swarm: 'enxame da praga',
  iron_sentinel: 'sentinela de ferro',
  aurora_mage: 'mago da aurora',
  ash_wyvern: 'wyvern de cinzas',
  bone_reaver: 'ceifador ósseo',
  tempest_queen: 'rainha da tempestade',
  forge_titan: 'titã da forja',
  coral_empress: 'imperatriz de coral',
  nightmare_king: 'rei do pesadelo',
  elder_beholder: 'beholder ancião',
  doom_hydra: 'hidra da perdição',
  astral_serpent: 'serpente astral',
  war_god_avatar: 'avatar do deus da guerra',
  necrotic_colossus: 'colosso necrótico',
  chaos_primordial: 'primordial do caos',
  pebble_sprite: 'sprite de pedra',
  reed_rat: 'rato dos juncos',
  tide_urchin: 'ouriço da maré',
  cinder_moth: 'mariposa de cinzas',
  pine_sprite: 'sprite do pinheiro',
  copper_goblin: 'goblin de cobre',
  mist_wisp: 'fogo-fátuo da névoa',
  brine_crab: 'caranguejo salgado',
  soot_imp: 'imp de fuligem',
  thistle_boar: 'javali de cardos',
  kelp_strider: 'caminhante de algas',
  ember_gnat: 'mosquito de brasas',
  chalk_golem_cub: 'golem de giz jovem',
  dusk_ferret: 'furão do crepúsculo',
  bog_newt: 'tritão do pântano',
  crystal_mite: 'ácaro de cristal',
  rust_scorpion: 'escorpião enferrujado',
  pollen_pixie: 'pixie de pólen',
  shale_basher: 'espancador de xisto',
  frost_vole: 'arganaz glacial',
  tar_slug: 'lesma de piche',
  spark_sprite: 'sprite de faísca',
  dune_jackal: 'chacal das dunas',
  lichen_troll_cub: 'troll de líquen jovem',
  ivory_skeleton: 'esqueleto de marfim',
  mangrove_croco: 'crocodilo do mangue',
  storm_finch: 'tentilhão da tempestade',
  ash_cult_initiate: 'iniciado do culto das cinzas',
  prism_moth: 'mariposa prismática',
  geyser_toad: 'sapo do gêiser',
  carrion_vulture: 'abutre carniceiro',
  magma_grub: 'larva de magma',
  void_mote: 'partícula do vazio',
  salt_wraith: 'espectro de sal',
  iron_tick: 'carrapato de ferro',
  glacier_imp: 'imp glacial',
  thorn_imp: 'imp de espinhos',
  cave_bat_swarm: 'enxame de morcegos',
  scrap_wolf: 'lobo de sucata',
  coral_snake: 'serpente de coral',
  rune_imp: 'imp rúnico',
  peat_slime: 'slime de turfa',
  wind_razor: 'lâmina do vento',
  blood_leech: 'sanguessuga',
  frost_archer_novice: 'arqueiro glacial novato',
  shade_larva: 'larva das sombras',
  pyre_cultist: 'cultista da pira',
  quartz_beetle: 'besouro de quartzo',
  acid_alchemist: 'alquimista ácido',
  frost_wyvern: 'wyvern glacial',
  bone_chanter: 'encantador ósseo',
  hex_witch: 'bruxa do hex',
  magma_brute: 'bruto de magma',
  storm_centurion: 'centurião da tempestade',
  obsidian_raptor: 'raptor de obsidiana',
  venom_naga: 'naga venenosa',
  crystal_guardian: 'guardião de cristal',
  shadow_duelist: 'duelista sombrio',
  pyre_drake: 'drake da pira',
  glacier_knight: 'cavaleiro glacial',
  plague_harpy: 'harpía da praga',
  rune_golem: 'golem rúnico',
  blood_panther: 'pantera sangrenta',
  arcane_archer: 'arqueiro arcano',
  furnace_golem: 'golem da fornalha',
  void_serpent: 'serpente do vazio',
  jade_monk: 'monge de jade',
  thunder_drake: 'drake do trovão',
  mirror_knight: 'cavaleiro espelhado',
  blight_treant: 'treant da praga',
  ash_assassin: 'assassino de cinzas',
  sapphire_witch: 'bruxa de safira',
  iron_hydra: 'hidra de ferro',
  soul_thief: 'ladrão de almas',
  cinder_titan_spawn: 'cria do titã de brasas',
  aurora_serpent: 'serpente da aurora',
  grave_sentinel: 'sentinela da sepultura',
  night_reaver: 'ceifador noturno',
  ember_witch: 'bruxa de brasas',
  toxin_archer: 'arqueiro tóxico',
  acid_sovereign: 'soberano ácido',
  frost_empress: 'imperatriz glacial',
  bone_overlord: 'suserano ósseo',
  hex_archon: 'arconte do hex',
  magma_tyrant: 'tirano de magma',
  storm_colossus: 'colosso da tempestade',
  void_matriarch: 'matriarca do vazio',
  plague_sovereign: 'soberano da praga',
  solar_phoenix_lord: 'senhor da fênix solar',
  abyss_leviathan: 'leviatã abissal',
  jade_emperor: 'imperador de jade',
  crimson_warlord: 'senhor da guerra carmesim',
  necrotic_queen: 'rainha necrótica',
  entropy_dragon: 'dragão da entropia',
  iron_behemoth: 'beemote de ferro',
  mire_hydra_king: 'rei hidra do lodo',
  astral_tyrant: 'tirano astral',
  forge_emperor: 'imperador da forja',
  shadow_primordial: 'primordial das sombras',
  tide_kraken_lord: 'senhor kraken das marés',
  amber_mite: 'ácaro âmbar',
  fog_hare: 'lebre da névoa',
  driftwood_crab: 'caranguejo de madeira',
  pollen_moth: 'mariposa de pólen',
  basalt_cub: 'filhote de basalto',
  reed_imp: 'imp de junco',
  snow_finch: 'tentilhão da neve',
  salt_scorpion: 'escorpião de sal',
  moss_newt: 'tritão de musgo',
  copper_tick: 'carrapato de cobre',
  tide_sprite: 'sprite das marés',
  ash_vole: 'arganaz de cinzas',
  bramble_boar: 'javali de sarças',
  chalk_imp: 'imp de giz',
  mire_slug: 'lesma do lodo',
  gust_sylph: 'sylph da rajada',
  onyx_beetle: 'besouro de ônix',
  peat_rat: 'rato de turfa',
  glint_pixie: 'pixie reluzente',
  dune_scarab: 'escaravelho das dunas',
  frost_gnat: 'mosquito glacial',
  root_crawler: 'rastejante de raízes',
  cinder_toad: 'sapo de brasas',
  pearl_slug: 'lesma de pérola',
  rune_mite: 'ácaro rúnico',
  shadow_vole: 'arganaz sombrio',
  coral_urchin: 'ouriço de coral',
  pine_imp: 'imp de pinheiro',
  slag_imp: 'imp de escória',
  ice_tick: 'carrapato de gelo',
  bog_finch: 'tentilhão do pântano',
  quartz_mite: 'ácaro de quartzo',
  dust_jackal: 'chacal de pó',
  kelp_newt: 'tritão de algas',
  ember_vole: 'arganaz de brasas',
  thorn_mite: 'ácaro de espinhos',
  mist_imp: 'imp da névoa',
  shale_tick: 'carrapato de xisto',
  aurora_moth: 'mariposa da aurora',
  blood_mite: 'ácaro de sangue',
  salt_newt: 'tritão de sal',
  vine_imp: 'imp de vinhas',
  glacier_mite: 'ácaro glacial',
  scrap_tick: 'carrapato de sucata',
  void_gnat: 'mosquito do vazio',
  marsh_imp: 'imp do pântano',
  crystal_finch: 'tentilhão de cristal',
  pyre_mite: 'ácaro da pira',
  amber_golem: 'golem âmbar',
  fog_wraith: 'espectro da névoa',
  drift_krakenling: 'kraken jovem',
  pollen_witch: 'bruxa de pólen',
  basalt_guardian: 'guardião de basalto',
  reed_naga: 'naga de junco',
  snow_berserker: 'berserker da neve',
  salt_goliath: 'golias de sal',
  moss_treant: 'treant de musgo',
  copper_sentinel: 'sentinela de cobre',
  tide_witch: 'bruxa das marés',
  ash_assassin_adept: 'assassino de cinzas adepto',
  bramble_hydra: 'hidra de sarças',
  chalk_mage: 'mago de giz',
  mire_hydra: 'hidra do lodo',
  gust_djinn: 'djinn da rajada',
  onyx_knight: 'cavaleiro de ônix',
  peat_necromancer: 'necromante de turfa',
  glint_sphinx: 'esfinge reluzente',
  dune_wyrm: 'serpe das dunas',
  frost_centurion: 'centurião glacial',
  root_guardian: 'guardião de raízes',
  cinder_drake: 'drake de brasas',
  pearl_siren: 'sereia de pérola',
  rune_archon_adept: 'adepto arconte rúnico',
  shadow_duelist_elite: 'duelista sombrio elite',
  coral_hydra: 'hidra de coral',
  pine_treant: 'treant de pinheiro',
  slag_golem: 'golem de escória',
  ice_wyvern_adept: 'wyvern glacial adepto',
  bog_alchemist: 'alquimista do pântano',
  quartz_guardian: 'guardião de quartzo',
  amber_sovereign: 'soberano âmbar',
  fog_matriarch: 'matriarca da névoa',
  drift_kraken_king: 'rei kraken das correntes',
  pollen_empress: 'imperatriz de pólen',
  basalt_colossus: 'colosso de basalto',
  reed_hydra_queen: 'rainha hidra de junco',
  snow_emperor: 'imperador da neve',
  salt_tyrant: 'tirano de sal',
  moss_world_tree: 'árvore-mundo de musgo',
  copper_behemoth: 'beemote de cobre',
  tide_leviathan: 'leviatã das marés',
  ash_warlord: 'senhor da guerra de cinzas',
  bramble_primordial: 'primordial de sarças',
  chalk_archon: 'arconte de giz',
  mire_sovereign: 'soberano do lodo',
  gust_storm_lord: 'senhor da rajada',
  onyx_overlord: 'suserano de ônix',
  peat_bone_king: 'rei ósseo de turfa',
  glint_astral_lord: 'senhor astral reluzente',
  dune_sand_emperor: 'imperador das areias',
  orc_recruit: 'orc recruta',
  goblin_scout: 'goblin batedor',
  slime_spawn: 'slime cria',
  wolf_pup: 'filhote de lobo',
  skeleton_recruit: 'esqueleto recruta',
  bat_hatchling: 'morcego filhote',
  imp_whelp: 'imp filhote',
  elf_apprentice: 'elfo aprendiz',
  zombie_thrall: 'zumbi servo',
  mummy_servant: 'múmia serva',
  ghoul_scavenger: 'carniçal necrófago',
  kobold_miner: 'kobold mineiro',
  bandit_thug: 'bandido capanga',
  pirate_deckhand: 'pirata grumete',
  cyclops_youth: 'ciclope jovem',
  minotaur_calf: 'minotauro jovem',
  harpy_fledgling: 'harpía filhote',
  scorpion_nymph: 'escorpião ninfa',
  cultist_initiate: 'cultista iniciado',
  gargoyle_shard: 'gárgula fragmento',
  pixie_spark: 'pixie faísca',
  gnoll_pup: 'gnoll filhote',
  ratman_squeaker: 'homem-rato chiador',
  crab_hatchling: 'caranguejo filhote',
  wasp_drone: 'vespa zangão',
  toad_tadpole: 'sapo girino',
  dwarf_squire: 'anão escudeiro',
  wraith_shade: 'espectro sombra',
  frogman_poliwog: 'homem-sapo girino',
  porcupine_kit: 'porco-espinho filhote',
  raven_chick: 'corvo filhote',
  boar_piglet: 'javali leitão',
  owl_fledgling: 'coruja filhote',
  fox_kit: 'raposa filhote',
  shark_pup: 'tubarão filhote',
  hive_larva: 'larva da colmeia',
  yeti_whelp: 'yeti filhote',
  spiderling: 'aranha filhote',
  snake_hatchling: 'serpente filhote',
  desert_jackal_pup: 'chacal filhote',
  troll_runt: 'troll nanico',
  slug_nymph: 'lesma ninfa',
  ice_imp_spark: 'imp de gelo faísca',
  scarab_larva: 'escaravelho larva',
  bone_shardling: 'fragmento ósseo',
  ember_spark: 'faísca de brasa',
  ash_rat_pup: 'rato de cinzas filhote',
  coral_crab_hatch: 'caranguejo de coral filhote',
  orc_war_chief: 'orc chefe da guerra',
  goblin_raid_captain: 'goblin capitão de raid',
  slime_overseer: 'slime supervisor',
  wolf_alpha: 'lobo alfa',
  skeleton_captain: 'esqueleto capitão',
  bat_matriarch: 'morcego matriarca',
  imp_taskmaster: 'imp feitor',
  elf_blademaster: 'elfo mestre das lâminas',
  zombie_warlord: 'zumbi senhor da guerra',
  mummy_pharaoh_guard: 'guarda do faraó',
  ghoul_packleader: 'carniçal líder da matilha',
  kobold_trapmaster: 'kobold mestre das armadilhas',
  bandit_kingpin: 'bandido chefão',
  pirate_captain: 'pirata capitão',
  cyclops_champion: 'ciclope campeão',
  minotaur_arena_lord: 'minotauro senhor da arena',
  harpy_stormcaller: 'harpía invocadora de tempestade',
  scorpion_broodmother: 'escorpião mãe da ninhada',
  cultist_hierophant: 'cultista hierofante',
  gargoyle_sentinel: 'gárgula sentinela',
  pixie_queen_guard: 'guarda da rainha pixie',
  gnoll_packlord: 'gnoll senhor da matilha',
  ratman_warlord: 'homem-rato senhor da guerra',
  crab_shellbreaker: 'caranguejo quebracascos',
  wasp_hivequeen_guard: 'guarda da rainha vespa',
  toad_bog_king: 'sapo rei do pântano',
  dwarf_warcaptain: 'anão capitão de guerra',
  wraith_reaper: 'espectro ceifador',
  frost_mage_adept: 'mago do gelo adepto',
  death_knight_vanguard: 'cavaleiro da morte vanguarda',
  shadow_assassin_master: 'assassino sombrio mestre',
  stone_golem_warden: 'golem de pedra guardião',
  orc_warchief_king: 'orc rei chefe da guerra',
  goblin_warlord_king: 'goblin rei senhor da guerra',
  slime_emperor: 'slime imperador',
  wolf_dire_king: 'lobo rei dire',
  skeleton_bone_king: 'esqueleto rei dos ossos',
  imp_hell_overlord: 'imp suserano do inferno',
  elf_forest_sovereign: 'elfo soberano da floresta',
  zombie_plague_king: 'zumbi rei da praga',
  mummy_pharaoh: 'múmia faraó',
  cyclops_mountain_king: 'ciclope rei da montanha',
  minotaur_labyrinth_king: 'minotauro rei do labirinto',
  harpy_sky_empress: 'harpía imperatriz dos céus',
  cultist_dark_messiah: 'cultista messias sombrio',
  gargoyle_cathedral_lord: 'gárgula senhor da catedral',
  gnoll_war_khan: 'gnoll khan da guerra',
  pirate_sea_emperor: 'pirata imperador dos mares',
  bandit_crime_emperor: 'bandido imperador do crime',
  dwarf_forge_king: 'anão rei da forja',
  ratman_underking: 'homem-rato rei subterrâneo',
  scorpion_dune_emperor: 'escorpião imperador das dunas',
};

export function monsterLabel(type) {
  return MONSTER_LABELS[type] || type;
}
