/** Habitats RPG: em quais terrenos cada monstro pode spawnar. */
export const MONSTER_FLOORS = {
  imp: ['volcano', 'hell', 'lava_field', 'dungeon', 'blood'],
  slime: ['sewer', 'dungeon', 'cave', 'swamp', 'mushroom'],
  wraith: ['graveyard', 'shadow', 'ruins', 'ice', 'blood'],
  goblin: ['dirt', 'grass', 'cave', 'dungeon', 'mountain', 'wood'],
  skeleton: ['graveyard', 'dungeon', 'ruins', 'temple', 'wood', 'blood'],
  skeleton_archer: ['graveyard', 'dungeon', 'ruins'],
  wolf: ['grass', 'meadow', 'tundra', 'snow', 'mountain'],
  bat: ['cave', 'dungeon', 'graveyard', 'shadow', 'wood', 'blood'],
  elf: ['grass', 'enchanted', 'jungle', 'meadow'],
  cyclops: ['mountain', 'cave', 'ruins'],
  minotaur: ['dungeon', 'ruins', 'temple'],
  harpy: ['sky', 'mountain', 'ruins'],
  kobold: ['dungeon', 'wood', 'ruins', 'temple', 'dirt'],
  zombie: ['graveyard', 'swamp', 'dungeon', 'sewer', 'blood'],
  mummy: ['desert', 'temple', 'ruins', 'graveyard'],
  ghoul: ['graveyard', 'dungeon', 'sewer', 'ruins', 'blood'],
  ratman: ['dungeon', 'wood', 'ruins', 'temple', 'dirt', 'blood'],
  scorpion: ['desert', 'beach', 'ashland'],
  venom_snake: ['swamp', 'sewer', 'mushroom', 'jungle'],
  cultist: ['dungeon', 'ruins', 'temple', 'shadow', 'blood', 'wood'],
  gargoyle: ['ruins', 'temple', 'dungeon', 'sky'],
  pixie: ['enchanted', 'grass', 'meadow', 'mushroom'],
  dwarf_guard: ['dungeon', 'wood', 'ruins', 'temple', 'dirt'],
  bandit: ['dungeon', 'wood', 'ruins', 'temple', 'dirt', 'desert', 'blood'],
  pirate: ['sea', 'beach', 'wood', 'coral'],
  giant_toad: ['swamp', 'sewer', 'mushroom', 'jungle', 'mountain'],
  wasp: ['grass', 'jungle', 'meadow', 'enchanted', 'mushroom', 'beach'],
  crab: ['beach', 'sea', 'coral'],
  yeti_cub: ['snow', 'tundra', 'mountain', 'ice'],
  shadow_wolf: ['shadow', 'graveyard', 'ruins', 'crystal', 'dungeon'],
  cave_troll: ['cave', 'mountain', 'dungeon', 'ruins', 'tundra'],
  swamp_slug: ['swamp', 'sewer', 'mushroom', 'jungle'],
  desert_scavenger: ['desert', 'beach', 'ashland', 'cave', 'mountain'],
  gnoll: ['dirt', 'grass', 'meadow', 'ruins', 'dungeon', 'desert'],
  ice_imp: ['ice', 'snow', 'tundra', 'mountain', 'hell'],
  orc: ['dirt', 'grass', 'mountain', 'ashland', 'meadow', 'desert', 'blood'],
  giant_spider: ['cave', 'dungeon', 'jungle', 'mushroom', 'wood'],
  fire_elemental: ['volcano', 'hell', 'lava_field', 'ashland'],
  bruxo: ['hell', 'volcano', 'ruins', 'shadow', 'blood'],
  ancient_scarab: ['desert', 'beach', 'ashland'],
  death_knight: ['graveyard', 'ruins', 'dungeon', 'temple', 'shadow', 'blood'],
  frost_mage: ['ice', 'snow', 'tundra', 'mountain', 'dungeon'],
  venom_hydra: ['swamp', 'sewer', 'mushroom', 'jungle', 'sea', 'coral'],
  stone_golem: ['cave', 'mountain', 'dungeon', 'ruins'],
  blood_succubus: ['blood', 'hell', 'graveyard', 'ruins'],
  nightmare_steed: ['shadow', 'graveyard', 'ruins', 'crystal', 'dungeon'],
  bone_whelp: ['graveyard', 'ruins', 'dungeon', 'temple', 'shadow'],
  abyss_watcher: ['shadow', 'graveyard', 'ruins', 'crystal', 'dungeon', 'coral'],
  crystal_elemental: ['crystal', 'cave', 'enchanted', 'temple', 'coral'],
  plague_doctor: ['swamp', 'sewer', 'mushroom', 'jungle', 'wood', 'blood'],
  war_troll: ['mountain', 'tundra', 'cave', 'meadow'],
  shadow_assassin: ['shadow', 'graveyard', 'ruins', 'crystal', 'dungeon', 'wood', 'blood'],
  storm_elemental: ['sky', 'mountain', 'grass', 'meadow', 'coral'],
  magma_golem: ['volcano', 'hell', 'lava_field', 'ashland', 'cave'],
  forest_guardian: ['grass', 'jungle', 'enchanted', 'meadow'],
  void_stalker: ['shadow', 'graveyard', 'ruins', 'crystal', 'dungeon'],
  ice_wyrm: ['ice', 'snow', 'tundra', 'mountain'],
  necromancer: ['graveyard', 'ruins', 'dungeon', 'temple', 'shadow', 'wood'],
  beholder: ['dungeon', 'cave', 'ruins', 'crystal', 'wood'],
  dragon: ['mountain', 'volcano', 'sky', 'lava_field'],
  lich: ['graveyard', 'ruins', 'dungeon', 'shadow', 'temple', 'wood'],
  demon: ['hell', 'volcano', 'lava_field', 'blood'],
  grim_reaper: ['graveyard', 'shadow', 'ruins', 'blood'],
  frost_dragon: ['ice', 'snow', 'tundra', 'mountain', 'sky'],
  bone_dragon: ['graveyard', 'ruins', 'dungeon', 'temple', 'shadow'],
  kraken: ['sea', 'coral'],
  hydra_boss: ['sea', 'beach', 'coral'],
  medusa: ['ruins', 'temple', 'dungeon', 'jungle', 'coral'],
  phoenix: ['volcano', 'sky', 'lava_field', 'ashland', 'desert'],
  titan: ['mountain', 'temple', 'ruins', 'sky'],
  void_lord: ['shadow', 'crystal', 'ruins'],
  ancient_treant: ['grass', 'jungle', 'enchanted', 'meadow'],
  sand_worm: ['desert', 'ashland'],
  flame_lord: ['volcano', 'hell', 'lava_field', 'ashland', 'desert'],
  frost_lich: ['ice', 'snow', 'tundra', 'mountain', 'graveyard'],
  plague_queen: ['swamp', 'sewer', 'mushroom', 'jungle'],
  storm_giant: ['sky', 'mountain', 'grass', 'meadow', 'tundra'],
  cerberus: ['hell', 'graveyard', 'lava_field', 'blood'],
  basilisk: ['desert', 'ruins', 'cave', 'temple', 'coral'],
  djinn: ['desert', 'sky', 'enchanted'],
  archdemon: ['hell', 'volcano', 'lava_field', 'blood'],
  world_serpent: ['swamp', 'jungle', 'sea', 'shadow', 'coral'],
  frogman: ['swamp', 'sewer', 'mushroom', 'jungle', 'coral', 'beach'],
  porcupine: ['grass', 'jungle', 'meadow', 'enchanted', 'mushroom'],
  dune_viper: ['desert', 'beach', 'ashland'],
  moss_sprite: ['grass', 'jungle', 'meadow', 'enchanted', 'mushroom'],
  scrap_golem: ['cave', 'mountain', 'dungeon', 'ruins'],
  raven_scout: ['sky', 'mountain', 'grass', 'meadow', 'beach'],
  bog_witch_apprentice: ['ice', 'snow', 'tundra', 'mountain', 'swamp', 'wood'],
  crystal_bat: ['crystal', 'cave', 'enchanted', 'temple', 'sky'],
  iron_boar: ['cave', 'mountain', 'dungeon', 'ruins', 'grass'],
  sand_archer: ['desert', 'beach', 'ashland', 'dungeon', 'wood'],
  frost_sprite: ['ice', 'snow', 'tundra', 'mountain', 'grass'],
  cave_crawler: ['cave', 'mountain', 'dungeon', 'ruins'],
  marsh_lurker: ['swamp', 'sewer', 'mushroom', 'jungle'],
  ember_whelp: ['volcano', 'hell', 'lava_field', 'ashland'],
  bone_picker: ['graveyard', 'ruins', 'dungeon', 'temple', 'shadow'],
  thorn_bush: ['grass', 'jungle', 'meadow', 'enchanted', 'mushroom'],
  ash_rat: ['volcano', 'hell', 'lava_field', 'ashland', 'dungeon'],
  coral_crab: ['sea', 'beach', 'coral'],
  wind_sylph: ['sky', 'mountain', 'grass', 'meadow', 'enchanted'],
  tomb_guard: ['graveyard', 'ruins', 'dungeon', 'temple', 'shadow'],
  spore_fungus: ['swamp', 'sewer', 'mushroom', 'jungle'],
  glacier_cub: ['ice', 'snow', 'tundra', 'mountain'],
  night_owl: ['shadow', 'graveyard', 'ruins', 'crystal', 'dungeon'],
  brimstone_imp: ['volcano', 'hell', 'lava_field', 'ashland', 'cave'],
  reed_stalker: ['dirt', 'grass', 'meadow', 'ruins', 'dungeon'],
  thunder_hawk: ['sky', 'mountain', 'grass', 'meadow'],
  blood_ogre: ['blood', 'hell', 'graveyard', 'ruins'],
  mirage_dancer: ['desert', 'beach', 'ashland'],
  frost_berserker: ['ice', 'snow', 'tundra', 'mountain'],
  venom_alchemist: ['swamp', 'sewer', 'mushroom', 'jungle', 'dungeon'],
  obsidian_guardian: ['volcano', 'hell', 'lava_field', 'ashland', 'dungeon'],
  soul_harvester: ['shadow', 'graveyard', 'ruins', 'crystal', 'dungeon', 'blood'],
  lava_serpent: ['volcano', 'hell', 'lava_field', 'ashland'],
  mirror_wraith: ['shadow', 'graveyard', 'ruins', 'crystal', 'dungeon'],
  plague_rat_king: ['swamp', 'sewer', 'mushroom', 'jungle', 'dungeon', 'wood'],
  storm_rider: ['sky', 'mountain', 'grass', 'meadow'],
  ironbark_treant: ['grass', 'jungle', 'meadow', 'enchanted', 'mushroom'],
  crimson_cultist: ['blood', 'hell', 'graveyard', 'ruins', 'dungeon'],
  void_imp_lord: ['shadow', 'graveyard', 'ruins', 'crystal', 'dungeon', 'blood'],
  sapphire_drake: ['crystal', 'cave', 'enchanted', 'temple', 'sky'],
  eclipse_sphinx: ['dirt', 'grass', 'meadow', 'ruins', 'dungeon', 'desert'],
  magma_colossus: ['volcano', 'hell', 'lava_field', 'ashland', 'mountain'],
  arctic_leviathan: ['ice', 'snow', 'tundra', 'mountain', 'sea'],
  blight_emperor: ['dirt', 'grass', 'meadow', 'ruins', 'dungeon'],
  chronomancer: ['enchanted', 'crystal', 'sky', 'meadow'],
  dread_naga: ['sea', 'beach', 'coral'],
  solar_phoenix: ['volcano', 'hell', 'lava_field', 'ashland', 'sky', 'desert'],
  abyssal_kraken: ['sea', 'beach', 'coral'],
  bone_emperor: ['graveyard', 'ruins', 'dungeon', 'temple', 'shadow', 'wood'],
  world_ender: ['shadow', 'hell', 'crystal', 'ruins'],
  mushroom_brute: ['swamp', 'sewer', 'mushroom', 'jungle'],
  salt_golem: ['desert', 'beach', 'ashland', 'cave', 'mountain'],
  fox_trickster: ['grass', 'jungle', 'meadow', 'enchanted', 'mushroom', 'desert'],
  quill_hunter: ['grass', 'jungle', 'meadow', 'enchanted', 'mushroom', 'desert'],
  peat_zombie: ['swamp', 'sewer', 'mushroom', 'jungle', 'graveyard'],
  lantern_spirit: ['enchanted', 'crystal', 'sky', 'meadow'],
  cliff_goat: ['mountain', 'tundra', 'cave', 'meadow'],
  reef_shark: ['sea', 'beach', 'coral'],
  dust_mephit: ['dirt', 'grass', 'meadow', 'ruins', 'dungeon', 'desert', 'beach'],
  bark_spider: ['grass', 'jungle', 'meadow', 'enchanted', 'mushroom'],
  snow_hare: ['ice', 'snow', 'tundra', 'mountain'],
  torch_bearer: ['dungeon', 'wood', 'ruins', 'temple', 'dirt'],
  bog_mosquito: ['swamp', 'sewer', 'mushroom', 'jungle'],
  rune_scribe: ['crystal', 'cave', 'enchanted', 'temple', 'dungeon', 'wood'],
  clay_soldier: ['dungeon', 'wood', 'ruins', 'temple', 'dirt'],
  pearl_diver: ['sea', 'beach', 'coral'],
  night_panther: ['shadow', 'graveyard', 'ruins', 'crystal', 'dungeon'],
  hive_drone: ['grass', 'jungle', 'meadow', 'enchanted', 'mushroom'],
  frost_toad: ['ice', 'snow', 'tundra', 'mountain', 'swamp'],
  scrap_bandit: ['cave', 'mountain', 'dungeon', 'ruins', 'wood'],
  vine_creeper: ['grass', 'jungle', 'meadow', 'enchanted', 'mushroom'],
  cinder_sprite: ['volcano', 'hell', 'lava_field', 'ashland', 'grass'],
  tunnel_mole: ['cave', 'mountain', 'dungeon', 'ruins'],
  glass_imp: ['crystal', 'cave', 'enchanted', 'temple', 'hell', 'ice'],
  thunder_boar: ['sky', 'mountain', 'grass', 'meadow', 'jungle'],
  blood_knight: ['blood', 'hell', 'graveyard', 'ruins', 'dungeon'],
  sand_djinni: ['desert', 'beach', 'ashland'],
  poison_archer: ['swamp', 'sewer', 'mushroom', 'jungle', 'dungeon'],
  jade_golem: ['crystal', 'cave', 'enchanted', 'temple', 'mountain'],
  shadow_priest: ['shadow', 'graveyard', 'ruins', 'crystal', 'dungeon', 'wood'],
  bladed_mantis: ['grass', 'jungle', 'meadow', 'enchanted', 'mushroom'],
  storm_witch: ['sky', 'mountain', 'grass', 'meadow', 'dungeon'],
  furnace_beast: ['volcano', 'hell', 'lava_field', 'ashland'],
  crystal_archer: ['crystal', 'cave', 'enchanted', 'temple', 'dungeon'],
  void_hound: ['shadow', 'graveyard', 'ruins', 'crystal', 'dungeon', 'blood'],
  plague_swarm: ['swamp', 'sewer', 'mushroom', 'jungle', 'blood'],
  iron_sentinel: ['cave', 'mountain', 'dungeon', 'ruins', 'wood'],
  aurora_mage: ['ice', 'snow', 'tundra', 'mountain', 'dungeon'],
  ash_wyvern: ['volcano', 'hell', 'lava_field', 'ashland', 'sky'],
  bone_reaver: ['graveyard', 'ruins', 'dungeon', 'temple', 'shadow', 'blood'],
  tempest_queen: ['sky', 'mountain', 'grass', 'meadow', 'sea'],
  forge_titan: ['volcano', 'hell', 'lava_field', 'ashland', 'mountain'],
  coral_empress: ['sea', 'beach', 'coral'],
  nightmare_king: ['shadow', 'graveyard', 'ruins', 'crystal', 'dungeon', 'wood'],
  elder_beholder: ['dirt', 'grass', 'meadow', 'ruins', 'dungeon', 'wood'],
  doom_hydra: ['sea', 'beach', 'coral'],
  astral_serpent: ['enchanted', 'crystal', 'sky', 'meadow'],
  war_god_avatar: ['dirt', 'grass', 'meadow', 'ruins', 'dungeon', 'desert'],
  necrotic_colossus: ['graveyard', 'ruins', 'dungeon', 'temple', 'shadow'],
  chaos_primordial: ['shadow', 'crystal', 'hell', 'ruins'],
  pebble_sprite: ['cave', 'mountain', 'dungeon', 'ruins', 'grass'],
  reed_rat: ['dungeon', 'wood', 'ruins', 'temple', 'dirt'],
  tide_urchin: ['sea', 'beach', 'coral'],
  cinder_moth: ['volcano', 'hell', 'lava_field', 'ashland'],
  pine_sprite: ['grass', 'jungle', 'meadow', 'enchanted', 'mushroom'],
  copper_goblin: ['dungeon', 'wood', 'ruins', 'temple', 'dirt'],
  mist_wisp: ['enchanted', 'crystal', 'sky', 'meadow', 'ice'],
  brine_crab: ['sea', 'beach', 'coral'],
  soot_imp: ['hell', 'volcano', 'lava_field', 'blood'],
  thistle_boar: ['grass', 'jungle', 'meadow', 'enchanted', 'mushroom'],
  kelp_strider: ['sea', 'beach', 'coral'],
  ember_gnat: ['volcano', 'hell', 'lava_field', 'ashland'],
  chalk_golem_cub: ['cave', 'mountain', 'dungeon', 'ruins'],
  dusk_ferret: ['shadow', 'graveyard', 'ruins', 'crystal', 'dungeon'],
  bog_newt: ['swamp', 'sewer', 'mushroom', 'jungle'],
  crystal_mite: ['crystal', 'cave', 'enchanted', 'temple', 'mountain'],
  rust_scorpion: ['desert', 'beach', 'ashland'],
  pollen_pixie: ['grass', 'jungle', 'meadow', 'enchanted', 'mushroom'],
  shale_basher: ['cave', 'mountain', 'dungeon', 'ruins'],
  frost_vole: ['ice', 'snow', 'tundra', 'mountain'],
  tar_slug: ['swamp', 'sewer', 'mushroom', 'jungle'],
  spark_sprite: ['grass', 'jungle', 'meadow', 'enchanted', 'mushroom'],
  dune_jackal: ['desert', 'beach', 'ashland'],
  lichen_troll_cub: ['graveyard', 'ruins', 'dungeon', 'temple', 'shadow'],
  ivory_skeleton: ['graveyard', 'ruins', 'dungeon', 'temple', 'shadow'],
  mangrove_croco: ['dirt', 'grass', 'meadow', 'ruins', 'dungeon'],
  storm_finch: ['sky', 'mountain', 'grass', 'meadow'],
  ash_cult_initiate: ['volcano', 'hell', 'lava_field', 'ashland', 'dungeon'],
  prism_moth: ['crystal', 'cave', 'enchanted', 'temple'],
  geyser_toad: ['swamp', 'sewer', 'mushroom', 'jungle', 'coral'],
  carrion_vulture: ['graveyard', 'ruins', 'dungeon', 'temple', 'shadow'],
  magma_grub: ['volcano', 'hell', 'lava_field', 'ashland'],
  void_mote: ['shadow', 'graveyard', 'ruins', 'crystal', 'dungeon'],
  salt_wraith: ['shadow', 'graveyard', 'ruins', 'crystal', 'dungeon'],
  iron_tick: ['cave', 'mountain', 'dungeon', 'ruins'],
  glacier_imp: ['ice', 'snow', 'tundra', 'mountain', 'hell'],
  thorn_imp: ['grass', 'jungle', 'meadow', 'enchanted', 'mushroom'],
  cave_bat_swarm: ['sky', 'mountain', 'grass', 'meadow', 'cave'],
  scrap_wolf: ['cave', 'mountain', 'dungeon', 'ruins', 'grass'],
  coral_snake: ['sea', 'beach', 'coral'],
  rune_imp: ['crystal', 'cave', 'enchanted', 'temple', 'hell'],
  peat_slime: ['swamp', 'sewer', 'mushroom', 'jungle'],
  wind_razor: ['sky', 'mountain', 'grass', 'meadow'],
  blood_leech: ['swamp', 'sewer', 'mushroom', 'jungle', 'blood'],
  frost_archer_novice: ['ice', 'snow', 'tundra', 'mountain', 'dungeon'],
  shade_larva: ['shadow', 'graveyard', 'ruins', 'crystal', 'dungeon'],
  pyre_cultist: ['volcano', 'hell', 'lava_field', 'ashland', 'dungeon'],
  quartz_beetle: ['crystal', 'cave', 'enchanted', 'temple'],
  acid_alchemist: ['dungeon', 'wood', 'ruins', 'temple', 'dirt'],
  frost_wyvern: ['ice', 'snow', 'tundra', 'mountain', 'sky'],
  bone_chanter: ['graveyard', 'ruins', 'dungeon', 'temple', 'shadow'],
  hex_witch: ['shadow', 'graveyard', 'ruins', 'crystal', 'dungeon'],
  magma_brute: ['volcano', 'hell', 'lava_field', 'ashland'],
  storm_centurion: ['sky', 'mountain', 'grass', 'meadow', 'dungeon'],
  obsidian_raptor: ['volcano', 'hell', 'lava_field', 'ashland'],
  venom_naga: ['swamp', 'sewer', 'mushroom', 'jungle', 'sea', 'coral'],
  crystal_guardian: ['crystal', 'cave', 'enchanted', 'temple', 'dungeon'],
  shadow_duelist: ['shadow', 'graveyard', 'ruins', 'crystal', 'dungeon'],
  pyre_drake: ['volcano', 'hell', 'lava_field', 'ashland', 'sky'],
  glacier_knight: ['ice', 'snow', 'tundra', 'mountain', 'dungeon'],
  plague_harpy: ['swamp', 'sewer', 'mushroom', 'jungle', 'sky'],
  rune_golem: ['crystal', 'cave', 'enchanted', 'temple', 'mountain'],
  blood_panther: ['blood', 'hell', 'graveyard', 'ruins', 'grass'],
  arcane_archer: ['dungeon', 'wood', 'ruins', 'temple', 'dirt'],
  furnace_golem: ['volcano', 'hell', 'lava_field', 'ashland', 'cave'],
  void_serpent: ['shadow', 'graveyard', 'ruins', 'crystal', 'dungeon'],
  jade_monk: ['crystal', 'cave', 'enchanted', 'temple', 'dungeon'],
  thunder_drake: ['sky', 'mountain', 'grass', 'meadow'],
  mirror_knight: ['dungeon', 'wood', 'ruins', 'temple', 'dirt'],
  blight_treant: ['grass', 'jungle', 'meadow', 'enchanted', 'mushroom'],
  ash_assassin: ['volcano', 'hell', 'lava_field', 'ashland', 'dungeon'],
  sapphire_witch: ['crystal', 'cave', 'enchanted', 'temple', 'dungeon'],
  iron_hydra: ['sea', 'beach', 'coral', 'cave', 'mountain'],
  soul_thief: ['shadow', 'graveyard', 'ruins', 'crystal', 'dungeon', 'blood'],
  cinder_titan_spawn: ['volcano', 'hell', 'lava_field', 'ashland', 'mountain'],
  aurora_serpent: ['ice', 'snow', 'tundra', 'mountain', 'enchanted'],
  grave_sentinel: ['graveyard', 'ruins', 'dungeon', 'temple', 'shadow'],
  night_reaver: ['shadow', 'graveyard', 'ruins', 'crystal', 'dungeon', 'blood'],
  ember_witch: ['volcano', 'hell', 'lava_field', 'ashland', 'dungeon'],
  toxin_archer: ['swamp', 'sewer', 'mushroom', 'jungle', 'dungeon'],
  acid_sovereign: ['dirt', 'grass', 'meadow', 'ruins', 'dungeon'],
  frost_empress: ['ice', 'snow', 'tundra', 'mountain'],
  bone_overlord: ['graveyard', 'ruins', 'dungeon', 'temple', 'shadow'],
  hex_archon: ['shadow', 'graveyard', 'ruins', 'crystal', 'dungeon'],
  magma_tyrant: ['volcano', 'hell', 'lava_field', 'ashland'],
  storm_colossus: ['sky', 'mountain', 'grass', 'meadow', 'tundra', 'sea'],
  void_matriarch: ['shadow', 'graveyard', 'ruins', 'crystal', 'dungeon'],
  plague_sovereign: ['swamp', 'sewer', 'mushroom', 'jungle', 'wood'],
  solar_phoenix_lord: ['volcano', 'hell', 'lava_field', 'ashland', 'sky'],
  abyss_leviathan: ['shadow', 'graveyard', 'ruins', 'crystal', 'dungeon', 'coral'],
  jade_emperor: ['crystal', 'cave', 'enchanted', 'temple'],
  crimson_warlord: ['blood', 'hell', 'graveyard', 'ruins'],
  necrotic_queen: ['graveyard', 'ruins', 'dungeon', 'temple', 'shadow', 'wood'],
  entropy_dragon: ['shadow', 'graveyard', 'ruins', 'crystal', 'dungeon'],
  iron_behemoth: ['cave', 'mountain', 'dungeon', 'ruins', 'tundra'],
  mire_hydra_king: ['swamp', 'sewer', 'mushroom', 'jungle', 'sea', 'coral'],
  astral_tyrant: ['enchanted', 'crystal', 'sky', 'meadow'],
  forge_emperor: ['volcano', 'hell', 'lava_field', 'ashland'],
  shadow_primordial: ['shadow', 'graveyard', 'ruins', 'crystal', 'dungeon'],
  tide_kraken_lord: ['sea', 'beach', 'coral'],
};

export function floorsForMonster(type) {
  return MONSTER_FLOORS[type] || null;
}

/** Todos os IDs de terreno da arena (legado + expansão). */
export const ALL_FLOOR_TYPES = [
  "dirt",
  "grass",
  "ice",
  "wood",
  "sea",
  "desert",
  "swamp",
  "volcano",
  "ruins",
  "crystal",
  "snow",
  "tundra",
  "cave",
  "dungeon",
  "graveyard",
  "hell",
  "sky",
  "mushroom",
  "jungle",
  "mountain",
  "beach",
  "coral",
  "ashland",
  "enchanted",
  "blood",
  "shadow",
  "temple",
  "sewer",
  "meadow",
  "lava_field"
];
