/**
 * Catálogo de tipos de monstro (normal / elite / boss).
 * Inspirado em fantasia clássica (D&D / WoW / Tibia) — nomes originais.
 */

export function createMonsterTypeDefs(CONFIG) {
  const common = CONFIG.MONSTER_WEIGHT_COMMON;
  const elite = CONFIG.MONSTER_WEIGHT_ELITE;
  const boss = CONFIG.MONSTER_WEIGHT_BOSS;

  return {
    // ─── Normal ───────────────────────────────────────────────
    imp: {
      hpMul: 1,
      speedMul: 1.2,
      dmgMul: 1,
      radius: 14,
      color: 0xff4422,
      attack: 'ranged',
      projectile: 'fireball',
      range: 190,
      preferRange: 130,
      projectileSpeed: 220,
      projectileRadius: 7,
      projectileColor: 0xff6622,
      attackCooldown: 1.45,
      weight: common,
      difficulty: 'normal',
    },
    slime: {
      hpMul: 1.5,
      speedMul: 0.8,
      dmgMul: 1,
      radius: 16,
      color: 0x44ff66,
      attack: 'melee',
      weight: common,
      difficulty: 'normal',
    },
    wraith: {
      hpMul: 1.3,
      speedMul: 1.1,
      dmgMul: 1,
      radius: 14,
      color: 0x8866ff,
      attack: 'melee',
      weight: common,
      difficulty: 'normal',
    },
    goblin: {
      hpMul: 0.7,
      speedMul: 1.35,
      dmgMul: 0.85,
      radius: 12,
      color: 0xa8c734,
      attack: 'ranged',
      projectile: 'arrow',
      range: 210,
      preferRange: 140,
      projectileSpeed: 340,
      projectileRadius: 4,
      projectileColor: 0xd4c4a0,
      attackCooldown: 1.15,
      weight: common,
      difficulty: 'normal',
    },
    skeleton: {
      hpMul: 1.1,
      speedMul: 1.05,
      dmgMul: 1.15,
      radius: 14,
      color: 0xe8e0d0,
      attack: 'melee',
      attackCooldown: 0.9,
      weight: common,
      difficulty: 'normal',
    },
    skeleton_archer: {
      hpMul: 0.85,
      speedMul: 0.95,
      dmgMul: 1.05,
      radius: 13,
      color: 0xd8d0c0,
      attack: 'ranged',
      projectile: 'arrow',
      range: 230,
      preferRange: 160,
      projectileSpeed: 360,
      projectileRadius: 4,
      projectileColor: 0xc8b8a0,
      attackCooldown: 1.35,
      weight: common,
      difficulty: 'normal',
    },
    wolf: {
      hpMul: 0.95,
      speedMul: 1.45,
      dmgMul: 1.2,
      radius: 14,
      color: 0x8b7355,
      attack: 'melee',
      attackCooldown: 0.75,
      weight: common,
      difficulty: 'normal',
    },
    bat: {
      hpMul: 0.5,
      speedMul: 1.65,
      dmgMul: 0.8,
      radius: 11,
      color: 0x4a3728,
      attack: 'melee',
      attackCooldown: 0.65,
      weight: common,
      difficulty: 'normal',
    },
    elf: {
      hpMul: 0.9,
      speedMul: 1.25,
      dmgMul: 1.1,
      radius: 13,
      color: 0x6bbf59,
      attack: 'ranged',
      projectile: 'arrow',
      range: 240,
      preferRange: 170,
      projectileSpeed: 380,
      projectileRadius: 4,
      projectileColor: 0xc8e6a0,
      attackCooldown: 1.05,
      weight: common,
      difficulty: 'normal',
    },
    cyclops: {
      hpMul: 1.6,
      speedMul: 0.75,
      dmgMul: 1.4,
      radius: 20,
      color: 0xc4a35a,
      attack: 'melee',
      attackCooldown: 1.15,
      weight: common,
      difficulty: 'normal',
    },
    minotaur: {
      hpMul: 1.8,
      speedMul: 0.9,
      dmgMul: 1.45,
      radius: 19,
      color: 0x8b4513,
      attack: 'melee',
      attackCooldown: 1.0,
      weight: common,
      difficulty: 'normal',
    },
    harpy: {
      hpMul: 0.85,
      speedMul: 1.4,
      dmgMul: 1.05,
      radius: 13,
      color: 0xd4a0c8,
      attack: 'ranged',
      projectile: 'arrow',
      range: 200,
      preferRange: 140,
      projectileSpeed: 320,
      projectileRadius: 4,
      projectileColor: 0xf0c0e0,
      attackCooldown: 1.2,
      weight: common,
      difficulty: 'normal',
    },
    kobold: {
      hpMul: 0.65,
      speedMul: 1.3,
      dmgMul: 0.9,
      radius: 11,
      color: 0xc97840,
      attack: 'ranged',
      projectile: 'arrow',
      range: 180,
      preferRange: 120,
      projectileSpeed: 300,
      projectileRadius: 4,
      projectileColor: 0xe8b080,
      attackCooldown: 1.1,
      weight: common,
      difficulty: 'normal',
    },
    zombie: {
      hpMul: 1.4,
      speedMul: 0.7,
      dmgMul: 1.1,
      radius: 15,
      color: 0x6b8f5a,
      attack: 'melee',
      attackCooldown: 1.25,
      weight: common,
      difficulty: 'normal',
    },
    mummy: {
      hpMul: 1.55,
      speedMul: 0.72,
      dmgMul: 1.2,
      radius: 15,
      color: 0xd4c48a,
      attack: 'melee',
      attackCooldown: 1.2,
      weight: common,
      difficulty: 'normal',
    },
    ghoul: {
      hpMul: 1.25,
      speedMul: 1.15,
      dmgMul: 1.25,
      radius: 14,
      color: 0x8fbc8f,
      attack: 'melee',
      attackCooldown: 0.85,
      weight: common,
      difficulty: 'normal',
    },
    ratman: {
      hpMul: 0.8,
      speedMul: 1.35,
      dmgMul: 0.95,
      radius: 12,
      color: 0x7a6a5a,
      attack: 'melee',
      attackCooldown: 0.8,
      weight: common,
      difficulty: 'normal',
    },
    scorpion: {
      hpMul: 1.15,
      speedMul: 1.05,
      dmgMul: 1.3,
      radius: 14,
      color: 0xc45c26,
      attack: 'melee',
      attackCooldown: 0.95,
      weight: common,
      difficulty: 'normal',
    },
    venom_snake: {
      hpMul: 0.75,
      speedMul: 1.25,
      dmgMul: 1.15,
      radius: 12,
      color: 0x3d8b40,
      attack: 'melee',
      attackCooldown: 0.85,
      weight: common,
      difficulty: 'normal',
    },
    cultist: {
      hpMul: 1.0,
      speedMul: 1.0,
      dmgMul: 1.1,
      radius: 14,
      color: 0x5c2d6e,
      attack: 'caster',
      spells: ['firebolt'], // só single-target em normais
      range: 220,
      preferRange: 140,
      projectileSpeed: 400,
      projectileRadius: 8,
      projectileColor: 0xaa44ff,
      attackCooldown: 1.55,
      weight: common,
      difficulty: 'normal',
    },
    gargoyle: {
      hpMul: 1.7,
      speedMul: 0.85,
      dmgMul: 1.35,
      radius: 17,
      color: 0x6e6e78,
      attack: 'melee',
      attackCooldown: 1.05,
      weight: common,
      difficulty: 'normal',
    },
    pixie: {
      hpMul: 0.55,
      speedMul: 1.55,
      dmgMul: 0.85,
      radius: 10,
      color: 0xff88cc,
      attack: 'ranged',
      projectile: 'arrow',
      range: 190,
      preferRange: 130,
      projectileSpeed: 360,
      projectileRadius: 4,
      projectileColor: 0xffaadd,
      attackCooldown: 1.0,
      weight: common,
      difficulty: 'normal',
    },
    dwarf_guard: {
      hpMul: 1.45,
      speedMul: 0.8,
      dmgMul: 1.35,
      radius: 14,
      color: 0xb87333,
      attack: 'melee',
      attackCooldown: 0.95,
      weight: common,
      difficulty: 'normal',
    },
    bandit: {
      hpMul: 1.0,
      speedMul: 1.2,
      dmgMul: 1.1,
      radius: 13,
      color: 0x8b5a2b,
      attack: 'ranged',
      projectile: 'arrow',
      range: 200,
      preferRange: 135,
      projectileSpeed: 330,
      projectileRadius: 4,
      projectileColor: 0xd2b48c,
      attackCooldown: 1.15,
      weight: common,
      difficulty: 'normal',
    },
    pirate: {
      hpMul: 1.2,
      speedMul: 1.1,
      dmgMul: 1.2,
      radius: 14,
      color: 0x2f4f6f,
      attack: 'melee',
      attackCooldown: 0.9,
      weight: common,
      difficulty: 'normal',
    },
    giant_toad: {
      hpMul: 1.65,
      speedMul: 0.7,
      dmgMul: 1.25,
      radius: 18,
      color: 0x4a7c59,
      attack: 'melee',
      attackCooldown: 1.2,
      weight: common,
      difficulty: 'normal',
    },
    wasp: {
      hpMul: 0.6,
      speedMul: 1.6,
      dmgMul: 0.9,
      radius: 10,
      color: 0xf0c040,
      attack: 'melee',
      attackCooldown: 0.7,
      weight: common,
      difficulty: 'normal',
    },
    crab: {
      hpMul: 1.5,
      speedMul: 0.75,
      dmgMul: 1.3,
      radius: 16,
      color: 0xd35400,
      attack: 'melee',
      attackCooldown: 1.1,
      weight: common,
      difficulty: 'normal',
    },
    yeti_cub: {
      hpMul: 1.35,
      speedMul: 0.95,
      dmgMul: 1.2,
      radius: 15,
      color: 0xe8eef5,
      attack: 'melee',
      attackCooldown: 1.0,
      weight: common,
      difficulty: 'normal',
    },
    shadow_wolf: {
      hpMul: 1.05,
      speedMul: 1.5,
      dmgMul: 1.25,
      radius: 14,
      color: 0x2c2c3a,
      attack: 'melee',
      attackCooldown: 0.7,
      weight: common,
      difficulty: 'normal',
    },
    cave_troll: {
      hpMul: 2.0,
      speedMul: 0.65,
      dmgMul: 1.5,
      radius: 22,
      color: 0x5a6e4a,
      attack: 'melee',
      attackCooldown: 1.3,
      weight: common,
      difficulty: 'normal',
    },
    swamp_slug: {
      hpMul: 1.8,
      speedMul: 0.55,
      dmgMul: 1.15,
      radius: 17,
      color: 0x556b2f,
      attack: 'melee',
      attackCooldown: 1.35,
      weight: common,
      difficulty: 'normal',
    },
    desert_scavenger: {
      hpMul: 0.9,
      speedMul: 1.3,
      dmgMul: 1.0,
      radius: 13,
      color: 0xc2a05a,
      attack: 'ranged',
      projectile: 'arrow',
      range: 195,
      preferRange: 130,
      projectileSpeed: 310,
      projectileRadius: 4,
      projectileColor: 0xe8d090,
      attackCooldown: 1.2,
      weight: common,
      difficulty: 'normal',
    },
    gnoll: {
      hpMul: 1.15,
      speedMul: 1.15,
      dmgMul: 1.2,
      radius: 15,
      color: 0xb8860b,
      attack: 'melee',
      attackCooldown: 0.9,
      weight: common,
      difficulty: 'normal',
    },
    ice_imp: {
      hpMul: 0.95,
      speedMul: 1.15,
      dmgMul: 1.05,
      radius: 13,
      color: 0x7ec8e3,
      attack: 'caster',
      spells: ['ice_shard'], // só single-target em normais
      range: 210,
      preferRange: 140,
      projectileSpeed: 420,
      projectileRadius: 8,
      projectileColor: 0x66ccff,
      attackCooldown: 1.6,
      weight: common,
      difficulty: 'normal',
    },

    // ─── Elite (mais forte) ───────────────────────────────────
    orc: {
      hpMul: 2.2,
      speedMul: 0.65,
      dmgMul: 1.6,
      radius: 20,
      color: 0x3d8b4a,
      attack: 'ranged',
      projectile: 'arrow',
      range: 175,
      preferRange: 110,
      projectileSpeed: 260,
      projectileRadius: 5,
      projectileColor: 0xb8956a,
      attackCooldown: 1.7,
      weight: elite,
      isElite: true,
      difficulty: 'hard',
    },
    giant_spider: {
      hpMul: 1.7,
      speedMul: 0.85,
      dmgMul: 1.35,
      radius: 18,
      color: 0x2d1b2e,
      attack: 'melee',
      attackCooldown: 1.1,
      weight: elite,
      isElite: true,
      difficulty: 'hard',
    },
    fire_elemental: {
      hpMul: 1.8,
      speedMul: 1.1,
      dmgMul: 1.3,
      radius: 16,
      color: 0xff6622,
      attack: 'caster',
      spells: ['firebreath', 'firebolt', 'flame_nova'],
      range: 250,
      preferRange: 145,
      projectileSpeed: 440,
      projectileRadius: 9,
      projectileColor: 0xff5533,
      attackCooldown: 1.15,
      novaRadius: 105,
      novaCooldown: 4.0,
      weight: elite,
      isElite: true,
      difficulty: 'hard',
    },
    bruxo: {
      hpMul: 1.9,
      speedMul: 1.05,
      dmgMul: 1.25,
      radius: 15,
      color: 0xff5522,
      attack: 'caster',
      spells: ['firebreath', 'firebolt'],
      range: 260,
      preferRange: 150,
      projectileSpeed: 450,
      projectileRadius: 9,
      projectileColor: 0xff5533,
      attackCooldown: 1.2,
      fireTrail: true,
      fireTrailInterval: 0.32,
      fireTrailRadius: 34,
      fireTrailLife: 2.6,
      fireTrailBurnDamage: 2,
      fireTrailBurnTick: 1,
      fireTrailBurnDuration: 3,
      weight: elite,
      isElite: true,
      difficulty: 'hard',
    },
    ancient_scarab: {
      hpMul: 2.4,
      speedMul: 0.8,
      dmgMul: 1.55,
      radius: 18,
      color: 0x1a5c3a,
      attack: 'melee',
      attackCooldown: 1.05,
      weight: elite,
      isElite: true,
      difficulty: 'hard',
    },
    death_knight: {
      hpMul: 2.6,
      speedMul: 0.85,
      dmgMul: 1.7,
      radius: 18,
      color: 0x3a3a5c,
      attack: 'melee',
      attackCooldown: 0.95,
      weight: elite,
      isElite: true,
      difficulty: 'nightmare',
    },
    frost_mage: {
      hpMul: 1.9,
      speedMul: 0.9,
      dmgMul: 1.4,
      radius: 15,
      color: 0x5dade2,
      attack: 'caster',
      spells: ['ice_shard'],
      range: 270,
      preferRange: 155,
      projectileSpeed: 460,
      projectileRadius: 9,
      projectileColor: 0x66ccff,
      attackCooldown: 1.15,
      weight: elite,
      isElite: true,
      difficulty: 'hard',
    },
    venom_hydra: {
      hpMul: 2.8,
      speedMul: 0.7,
      dmgMul: 1.65,
      radius: 22,
      color: 0x27ae60,
      attack: 'caster',
      spells: ['poison_cloud', 'firebolt'],
      range: 240,
      preferRange: 140,
      projectileSpeed: 380,
      projectileRadius: 9,
      projectileColor: 0x88ff44,
      attackCooldown: 1.25,
      novaRadius: 100,
      novaCooldown: 4.2,
      weight: elite,
      isElite: true,
      difficulty: 'nightmare',
    },
    stone_golem: {
      hpMul: 3.2,
      speedMul: 0.5,
      dmgMul: 1.8,
      radius: 24,
      color: 0x7f8c8d,
      attack: 'melee',
      attackCooldown: 1.4,
      weight: elite,
      isElite: true,
      difficulty: 'hard',
    },
    blood_succubus: {
      hpMul: 2.0,
      speedMul: 1.2,
      dmgMul: 1.5,
      radius: 15,
      color: 0xc0392b,
      attack: 'caster',
      spells: ['arc_lightning', 'firebolt'],
      range: 230,
      preferRange: 140,
      projectileSpeed: 420,
      projectileRadius: 8,
      projectileColor: 0xff4466,
      attackCooldown: 1.1,
      weight: elite,
      isElite: true,
      difficulty: 'nightmare',
    },
    nightmare_steed: {
      hpMul: 2.2,
      speedMul: 1.55,
      dmgMul: 1.55,
      radius: 17,
      color: 0x1a0a20,
      attack: 'melee',
      attackCooldown: 0.75,
      weight: elite,
      isElite: true,
      difficulty: 'hard',
    },
    bone_whelp: {
      hpMul: 2.1,
      speedMul: 1.0,
      dmgMul: 1.45,
      radius: 16,
      color: 0xd5d0c0,
      attack: 'caster',
      spells: ['firebolt', 'skull_wave'],
      range: 240,
      preferRange: 145,
      projectileSpeed: 400,
      projectileRadius: 9,
      projectileColor: 0xe8e0d0,
      attackCooldown: 1.2,
      skullCount: 6,
      weight: elite,
      isElite: true,
      difficulty: 'nightmare',
    },
    abyss_watcher: {
      hpMul: 2.3,
      speedMul: 0.95,
      dmgMul: 1.5,
      radius: 17,
      color: 0x4a0080,
      attack: 'caster',
      spells: ['arc_lightning', 'electric_bolt'],
      range: 250,
      preferRange: 150,
      attackCooldown: 1.15,
      weight: elite,
      isElite: true,
      difficulty: 'nightmare',
    },
    crystal_elemental: {
      hpMul: 2.5,
      speedMul: 0.75,
      dmgMul: 1.55,
      radius: 18,
      color: 0xaed6f1,
      attack: 'caster',
      spells: ['ice_shard', 'arc_lightning'],
      range: 260,
      preferRange: 150,
      projectileSpeed: 450,
      projectileRadius: 9,
      projectileColor: 0xd6eaf8,
      attackCooldown: 1.2,
      weight: elite,
      isElite: true,
      difficulty: 'hard',
    },
    plague_doctor: {
      hpMul: 2.0,
      speedMul: 0.95,
      dmgMul: 1.35,
      radius: 15,
      color: 0x2c3e2d,
      attack: 'caster',
      spells: ['poison_cloud', 'ice_shard'],
      range: 230,
      preferRange: 140,
      projectileSpeed: 400,
      projectileRadius: 8,
      projectileColor: 0x88ff44,
      attackCooldown: 1.25,
      novaRadius: 95,
      novaCooldown: 3.8,
      weight: elite,
      isElite: true,
      difficulty: 'hard',
    },
    war_troll: {
      hpMul: 3.0,
      speedMul: 0.6,
      dmgMul: 1.9,
      radius: 24,
      color: 0x4a6741,
      attack: 'melee',
      attackCooldown: 1.25,
      weight: elite,
      isElite: true,
      difficulty: 'nightmare',
    },
    shadow_assassin: {
      hpMul: 1.7,
      speedMul: 1.6,
      dmgMul: 1.7,
      radius: 13,
      color: 0x1c1c28,
      attack: 'melee',
      attackCooldown: 0.65,
      weight: elite,
      isElite: true,
      difficulty: 'nightmare',
    },
    storm_elemental: {
      hpMul: 2.2,
      speedMul: 1.1,
      dmgMul: 1.5,
      radius: 17,
      color: 0x5dade2,
      attack: 'caster',
      spells: ['electric_bolt', 'arc_lightning'],
      range: 260,
      preferRange: 150,
      attackCooldown: 1.1,
      weight: elite,
      isElite: true,
      difficulty: 'hard',
    },
    magma_golem: {
      hpMul: 3.0,
      speedMul: 0.55,
      dmgMul: 1.85,
      radius: 23,
      color: 0xe67e22,
      attack: 'caster',
      spells: ['firebreath', 'flame_nova', 'firebolt'],
      range: 220,
      preferRange: 130,
      projectileSpeed: 400,
      projectileRadius: 9,
      projectileColor: 0xff6622,
      attackCooldown: 1.2,
      novaRadius: 110,
      novaCooldown: 4.0,
      weight: elite,
      isElite: true,
      difficulty: 'nightmare',
    },
    forest_guardian: {
      hpMul: 2.7,
      speedMul: 0.7,
      dmgMul: 1.6,
      radius: 22,
      color: 0x1e8449,
      attack: 'melee',
      attackCooldown: 1.15,
      weight: elite,
      isElite: true,
      difficulty: 'hard',
    },
    void_stalker: {
      hpMul: 2.1,
      speedMul: 1.35,
      dmgMul: 1.6,
      radius: 15,
      color: 0x2c003e,
      attack: 'caster',
      spells: ['skull_wave', 'arc_lightning'],
      range: 230,
      preferRange: 140,
      projectileSpeed: 320,
      projectileRadius: 10,
      projectileColor: 0x4a0080,
      attackCooldown: 1.3,
      skullCount: 7,
      weight: elite,
      isElite: true,
      difficulty: 'apocalypse',
    },
    ice_wyrm: {
      hpMul: 2.5,
      speedMul: 0.85,
      dmgMul: 1.55,
      radius: 20,
      color: 0xaed6f1,
      attack: 'caster',
      spells: ['ice_shard', 'firebreath'],
      range: 250,
      preferRange: 150,
      projectileSpeed: 440,
      projectileRadius: 9,
      projectileColor: 0x66ccff,
      attackCooldown: 1.15,
      weight: elite,
      isElite: true,
      difficulty: 'nightmare',
    },
    necromancer: {
      hpMul: 2.0,
      speedMul: 0.9,
      dmgMul: 1.4,
      radius: 15,
      color: 0x4a235a,
      attack: 'caster',
      spells: ['skull_wave', 'ice_shard'],
      range: 250,
      preferRange: 150,
      projectileSpeed: 420,
      projectileRadius: 9,
      projectileColor: 0x6c3483,
      attackCooldown: 1.25,
      skullCount: 8,
      weight: elite,
      isElite: true,
      difficulty: 'nightmare',
    },

    // ─── Boss ─────────────────────────────────────────────────
    beholder: {
      hpMul: 2.4,
      speedMul: 0.55,
      dmgMul: 1.25,
      radius: 30,
      color: 0x9b59b6,
      attack: 'caster',
      spells: ['arc_lightning', 'void_collapse'],
      range: 170,
      preferRange: 130,
      attackCooldown: 1.35,
      novaRadius: 120,
      novaCooldown: 5.5,
      weight: boss,
      isBoss: true,
      difficulty: 'hard',
    },
    dragon: {
      hpMul: 3.8,
      speedMul: 0.5,
      dmgMul: 1.55,
      radius: 42,
      color: 0xe74c3c,
      attack: 'caster',
      spells: ['firebreath', 'firebolt', 'flame_nova', 'infernal_judgment'],
      range: 300,
      preferRange: 170,
      projectileSpeed: 480,
      projectileRadius: 10,
      projectileColor: 0xff5533,
      attackCooldown: 1.1,
      novaRadius: 120,
      novaCooldown: 4.2,
      weight: boss,
      isBoss: true,
      difficulty: 'nightmare',
    },
    lich: {
      hpMul: 2.1,
      speedMul: 0.6,
      dmgMul: 1.15,
      radius: 24,
      color: 0x66ccff,
      attack: 'caster',
      spells: ['ice_shard', 'death_knell', 'frost_apocalypse'],
      range: 280,
      preferRange: 160,
      projectileSpeed: 460,
      projectileRadius: 9,
      projectileColor: 0x66ccff,
      attackCooldown: 1.25,
      novaRadius: 130,
      novaCooldown: 5.0,
      weight: boss,
      isBoss: true,
      difficulty: 'hard',
    },
    demon: {
      hpMul: 2.2,
      speedMul: 0.85,
      dmgMul: 1.4,
      radius: 42,
      color: 0x8b1a2b,
      attack: 'caster',
      spells: ['electric_bolt', 'electric_storm', 'infernal_judgment'],
      range: 260,
      preferRange: 150,
      attackCooldown: 1.2,
      novaRadius: 130,
      novaCooldown: 4.5,
      weight: boss,
      isBoss: true,
      difficulty: 'nightmare',
    },
    grim_reaper: {
      hpMul: 2.6,
      speedMul: 0.7,
      dmgMul: 1.35,
      radius: 27,
      color: 0x2a0044,
      attack: 'caster',
      spells: ['skull_wave', 'soul_rend', 'death_knell'],
      range: 220,
      preferRange: 140,
      projectileSpeed: 300,
      projectileRadius: 11,
      projectileColor: 0x4a0080,
      attackCooldown: 2.4,
      skullCount: 10,
      novaRadius: 110,
      novaCooldown: 5.2,
      weight: boss,
      isBoss: true,
      difficulty: 'apocalypse',
    },
    frost_dragon: {
      hpMul: 4.0,
      speedMul: 0.48,
      dmgMul: 1.6,
      radius: 40,
      color: 0x5dade2,
      attack: 'caster',
      spells: ['ice_shard', 'frost_apocalypse', 'cataclysm_beam'],
      range: 300,
      preferRange: 170,
      projectileSpeed: 470,
      projectileRadius: 10,
      projectileColor: 0xaed6f1,
      attackCooldown: 1.15,
      novaRadius: 135,
      novaCooldown: 4.8,
      weight: boss,
      isBoss: true,
      difficulty: 'nightmare',
    },
    bone_dragon: {
      hpMul: 3.6,
      speedMul: 0.52,
      dmgMul: 1.5,
      radius: 38,
      color: 0xece5d0,
      attack: 'caster',
      spells: ['skull_wave', 'soul_rend', 'abyss_nova'],
      range: 280,
      preferRange: 160,
      projectileSpeed: 340,
      projectileRadius: 11,
      projectileColor: 0xd5d0c0,
      attackCooldown: 1.3,
      skullCount: 12,
      novaRadius: 125,
      novaCooldown: 5.0,
      weight: boss,
      isBoss: true,
      difficulty: 'apocalypse',
    },
    kraken: {
      hpMul: 4.2,
      speedMul: 0.45,
      dmgMul: 1.7,
      radius: 44,
      color: 0x1a5276,
      attack: 'caster',
      spells: ['void_collapse', 'abyss_nova', 'electric_storm', 'electric_bolt'],
      range: 260,
      preferRange: 150,
      attackCooldown: 1.25,
      novaRadius: 140,
      novaCooldown: 4.6,
      weight: boss,
      isBoss: true,
      difficulty: 'nightmare',
    },
    hydra_boss: {
      hpMul: 4.5,
      speedMul: 0.55,
      dmgMul: 1.65,
      radius: 40,
      color: 0x196f3d,
      attack: 'caster',
      spells: ['plague_burst', 'poison_cloud', 'firebreath'],
      range: 250,
      preferRange: 145,
      attackCooldown: 1.2,
      novaRadius: 120,
      novaCooldown: 4.4,
      weight: boss,
      isBoss: true,
      difficulty: 'hard',
    },
    medusa: {
      hpMul: 3.0,
      speedMul: 0.75,
      dmgMul: 1.45,
      radius: 28,
      color: 0x58d68d,
      attack: 'caster',
      spells: ['cataclysm_beam', 'poison_cloud', 'ice_shard'],
      range: 270,
      preferRange: 155,
      projectileSpeed: 450,
      projectileRadius: 9,
      projectileColor: 0x82e0aa,
      attackCooldown: 1.2,
      novaRadius: 115,
      novaCooldown: 5.0,
      weight: boss,
      isBoss: true,
      difficulty: 'hard',
    },
    phoenix: {
      hpMul: 3.4,
      speedMul: 1.05,
      dmgMul: 1.55,
      radius: 32,
      color: 0xff6b35,
      attack: 'caster',
      spells: ['infernal_judgment', 'flame_nova', 'firebreath'],
      range: 280,
      preferRange: 160,
      attackCooldown: 1.1,
      novaRadius: 125,
      novaCooldown: 4.0,
      weight: boss,
      isBoss: true,
      difficulty: 'nightmare',
    },
    titan: {
      hpMul: 5.0,
      speedMul: 0.4,
      dmgMul: 1.9,
      radius: 48,
      color: 0xf5cba7,
      attack: 'caster',
      spells: ['abyss_nova', 'cataclysm_beam', 'electric_storm', 'electric_bolt'],
      range: 290,
      preferRange: 160,
      attackCooldown: 1.35,
      novaRadius: 150,
      novaCooldown: 5.5,
      weight: boss,
      isBoss: true,
      difficulty: 'apocalypse',
    },
    void_lord: {
      hpMul: 3.8,
      speedMul: 0.65,
      dmgMul: 1.6,
      radius: 36,
      color: 0x1a0033,
      attack: 'caster',
      spells: ['void_collapse', 'shadow_eclipse', 'soul_rend', 'arc_lightning'],
      range: 270,
      preferRange: 155,
      attackCooldown: 1.2,
      novaRadius: 140,
      novaCooldown: 5.2,
      weight: boss,
      isBoss: true,
      difficulty: 'apocalypse',
    },
    ancient_treant: {
      hpMul: 4.4,
      speedMul: 0.42,
      dmgMul: 1.55,
      radius: 42,
      color: 0x145a32,
      attack: 'caster',
      spells: ['plague_burst', 'abyss_nova', 'flame_nova', 'firebolt'],
      range: 240,
      preferRange: 140,
      projectileSpeed: 400,
      projectileRadius: 9,
      projectileColor: 0x88ff44,
      attackCooldown: 1.3,
      novaRadius: 130,
      novaCooldown: 4.8,
      weight: boss,
      isBoss: true,
      difficulty: 'hard',
    },
    sand_worm: {
      hpMul: 4.0,
      speedMul: 0.6,
      dmgMul: 1.7,
      radius: 40,
      color: 0xd4a017,
      attack: 'caster',
      spells: ['void_collapse', 'cataclysm_beam', 'flame_nova', 'firebolt'],
      range: 250,
      preferRange: 140,
      projectileSpeed: 420,
      projectileRadius: 9,
      projectileColor: 0xf4d03f,
      attackCooldown: 1.25,
      novaRadius: 125,
      novaCooldown: 4.5,
      weight: boss,
      isBoss: true,
      difficulty: 'nightmare',
    },
    flame_lord: {
      hpMul: 3.9,
      speedMul: 0.7,
      dmgMul: 1.75,
      radius: 38,
      color: 0xcb4335,
      attack: 'caster',
      spells: ['infernal_judgment', 'firebreath', 'flame_nova', 'blood_pact'],
      range: 280,
      preferRange: 160,
      attackCooldown: 1.15,
      novaRadius: 130,
      novaCooldown: 4.2,
      weight: boss,
      isBoss: true,
      difficulty: 'apocalypse',
    },
    frost_lich: {
      hpMul: 3.2,
      speedMul: 0.58,
      dmgMul: 1.4,
      radius: 26,
      color: 0x85c1e9,
      attack: 'caster',
      spells: ['frost_apocalypse', 'death_knell', 'ice_shard'],
      range: 290,
      preferRange: 165,
      projectileSpeed: 470,
      projectileRadius: 9,
      projectileColor: 0xd6eaf8,
      attackCooldown: 1.2,
      novaRadius: 135,
      novaCooldown: 5.0,
      weight: boss,
      isBoss: true,
      difficulty: 'nightmare',
    },
    plague_queen: {
      hpMul: 3.5,
      speedMul: 0.8,
      dmgMul: 1.5,
      radius: 30,
      color: 0x7d3c98,
      attack: 'caster',
      spells: ['plague_burst', 'poison_cloud', 'blood_pact', 'ice_shard'],
      range: 260,
      preferRange: 150,
      projectileSpeed: 430,
      projectileRadius: 9,
      projectileColor: 0xbb8fce,
      attackCooldown: 1.2,
      novaRadius: 120,
      novaCooldown: 4.3,
      weight: boss,
      isBoss: true,
      difficulty: 'nightmare',
    },
    storm_giant: {
      hpMul: 4.6,
      speedMul: 0.5,
      dmgMul: 1.8,
      radius: 46,
      color: 0x5d6d7e,
      attack: 'caster',
      spells: ['electric_storm', 'electric_bolt', 'cataclysm_beam'],
      range: 300,
      preferRange: 170,
      attackCooldown: 1.25,
      novaRadius: 145,
      novaCooldown: 4.6,
      weight: boss,
      isBoss: true,
      difficulty: 'apocalypse',
    },
    cerberus: {
      hpMul: 3.7,
      speedMul: 1.1,
      dmgMul: 1.7,
      radius: 34,
      color: 0x641e16,
      attack: 'caster',
      spells: ['infernal_judgment', 'firebreath', 'soul_rend'],
      range: 240,
      preferRange: 130,
      attackCooldown: 1.05,
      novaRadius: 110,
      novaCooldown: 4.5,
      weight: boss,
      isBoss: true,
      difficulty: 'hard',
    },
    basilisk: {
      hpMul: 3.3,
      speedMul: 0.7,
      dmgMul: 1.55,
      radius: 32,
      color: 0x117a65,
      attack: 'caster',
      spells: ['cataclysm_beam', 'plague_burst', 'poison_cloud', 'ice_shard'],
      range: 250,
      preferRange: 145,
      projectileSpeed: 440,
      projectileRadius: 9,
      projectileColor: 0x1abc9c,
      attackCooldown: 1.2,
      novaRadius: 115,
      novaCooldown: 4.8,
      weight: boss,
      isBoss: true,
      difficulty: 'hard',
    },
    djinn: {
      hpMul: 3.1,
      speedMul: 1.0,
      dmgMul: 1.5,
      radius: 28,
      color: 0xf4d03f,
      attack: 'caster',
      spells: ['shadow_eclipse', 'electric_bolt', 'void_collapse'],
      range: 270,
      preferRange: 155,
      attackCooldown: 1.15,
      novaRadius: 130,
      novaCooldown: 5.0,
      weight: boss,
      isBoss: true,
      difficulty: 'nightmare',
    },
    archdemon: {
      hpMul: 4.3,
      speedMul: 0.75,
      dmgMul: 1.85,
      radius: 40,
      color: 0x7b241c,
      attack: 'caster',
      spells: ['blood_pact', 'infernal_judgment', 'shadow_eclipse', 'electric_storm', 'firebolt'],
      range: 280,
      preferRange: 160,
      projectileSpeed: 450,
      projectileRadius: 10,
      projectileColor: 0xff4422,
      attackCooldown: 1.15,
      novaRadius: 140,
      novaCooldown: 4.4,
      weight: boss,
      isBoss: true,
      difficulty: 'apocalypse',
    },
    world_serpent: {
      hpMul: 5.2,
      speedMul: 0.5,
      dmgMul: 1.95,
      radius: 50,
      color: 0x0e6655,
      attack: 'caster',
      spells: ['abyss_nova', 'void_collapse', 'plague_burst', 'death_knell', 'electric_bolt'],
      range: 310,
      preferRange: 175,
      attackCooldown: 1.3,
      novaRadius: 155,
      novaCooldown: 5.5,
      weight: boss,
      isBoss: true,
      difficulty: 'apocalypse',
    },

    // ─── Expansão (+50 tipos, dificuldades variadas) ───────────
    // Normais
    frogman: {
      hpMul: 1.05, speedMul: 1.1, dmgMul: 1.05, radius: 13, color: 0x3d9970,
      attack: 'melee', attackCooldown: 0.95, weight: common, difficulty: 'normal',
    },
    porcupine: {
      hpMul: 1.2, speedMul: 0.9, dmgMul: 1.15, radius: 14, color: 0x8b7355,
      attack: 'ranged', projectile: 'arrow', range: 170, preferRange: 110,
      projectileSpeed: 300, projectileRadius: 4, projectileColor: 0xc4a882,
      attackCooldown: 1.25, weight: common, difficulty: 'normal',
    },
    dune_viper: {
      hpMul: 0.85, speedMul: 1.35, dmgMul: 1.2, radius: 12, color: 0xc9a227,
      attack: 'melee', attackCooldown: 0.8, weight: common, difficulty: 'normal',
    },
    moss_sprite: {
      hpMul: 0.6, speedMul: 1.5, dmgMul: 0.9, radius: 10, color: 0x7dcea0,
      attack: 'caster', spells: ['ice_shard'], range: 200, preferRange: 135,
      projectileSpeed: 400, projectileRadius: 7, projectileColor: 0xa9dfbf,
      attackCooldown: 1.7, weight: common, difficulty: 'normal',
    },
    scrap_golem: {
      hpMul: 1.7, speedMul: 0.7, dmgMul: 1.35, radius: 18, color: 0x7f8c8d,
      attack: 'melee', attackCooldown: 1.2, weight: common, difficulty: 'hard',
    },
    raven_scout: {
      hpMul: 0.7, speedMul: 1.55, dmgMul: 0.95, radius: 11, color: 0x2c3e50,
      attack: 'ranged', projectile: 'arrow', range: 220, preferRange: 150,
      projectileSpeed: 360, projectileRadius: 4, projectileColor: 0x5d6d7e,
      attackCooldown: 1.1, weight: common, difficulty: 'normal',
    },
    bog_witch_apprentice: {
      hpMul: 1.0, speedMul: 1.0, dmgMul: 1.1, radius: 13, color: 0x6c3483,
      attack: 'caster', spells: ['firebolt'], range: 215, preferRange: 140,
      projectileSpeed: 410, projectileRadius: 8, projectileColor: 0x9b59b6,
      attackCooldown: 1.65, weight: common, difficulty: 'hard',
    },
    crystal_bat: {
      hpMul: 0.55, speedMul: 1.7, dmgMul: 0.85, radius: 10, color: 0xaed6f1,
      attack: 'melee', attackCooldown: 0.6, weight: common, difficulty: 'normal',
    },
    iron_boar: {
      hpMul: 1.6, speedMul: 1.05, dmgMul: 1.4, radius: 17, color: 0x566573,
      attack: 'melee', attackCooldown: 1.0, weight: common, difficulty: 'hard',
    },
    sand_archer: {
      hpMul: 0.9, speedMul: 1.15, dmgMul: 1.1, radius: 13, color: 0xd4a017,
      attack: 'ranged', projectile: 'arrow', range: 235, preferRange: 160,
      projectileSpeed: 370, projectileRadius: 4, projectileColor: 0xf4d03f,
      attackCooldown: 1.2, weight: common, difficulty: 'normal',
    },
    frost_sprite: {
      hpMul: 0.65, speedMul: 1.4, dmgMul: 0.95, radius: 10, color: 0xd6eaf8,
      attack: 'caster', spells: ['ice_shard'], range: 205, preferRange: 130,
      projectileSpeed: 430, projectileRadius: 7, projectileColor: 0x85c1e9,
      attackCooldown: 1.75, weight: common, difficulty: 'normal',
    },
    cave_crawler: {
      hpMul: 1.1, speedMul: 1.25, dmgMul: 1.15, radius: 13, color: 0x5d4037,
      attack: 'melee', attackCooldown: 0.85, weight: common, difficulty: 'normal',
    },
    marsh_lurker: {
      hpMul: 1.45, speedMul: 0.75, dmgMul: 1.25, radius: 16, color: 0x4a6741,
      attack: 'melee', attackCooldown: 1.15, weight: common, difficulty: 'hard',
    },
    ember_whelp: {
      hpMul: 0.95, speedMul: 1.2, dmgMul: 1.15, radius: 13, color: 0xe67e22,
      attack: 'ranged', projectile: 'fireball', range: 200, preferRange: 135,
      projectileSpeed: 280, projectileRadius: 7, projectileColor: 0xff6622,
      attackCooldown: 1.3, weight: common, difficulty: 'hard',
    },
    bone_picker: {
      hpMul: 0.8, speedMul: 1.3, dmgMul: 1.0, radius: 12, color: 0xd5d0c0,
      attack: 'ranged', projectile: 'arrow', range: 195, preferRange: 130,
      projectileSpeed: 340, projectileRadius: 4, projectileColor: 0xece5d0,
      attackCooldown: 1.15, weight: common, difficulty: 'normal',
    },
    thorn_bush: {
      hpMul: 1.5, speedMul: 0.55, dmgMul: 1.2, radius: 16, color: 0x1e8449,
      attack: 'melee', attackCooldown: 1.25, weight: common, difficulty: 'normal',
    },
    ash_rat: {
      hpMul: 0.7, speedMul: 1.45, dmgMul: 0.95, radius: 11, color: 0x6e2c00,
      attack: 'melee', attackCooldown: 0.7, weight: common, difficulty: 'normal',
    },
    coral_crab: {
      hpMul: 1.55, speedMul: 0.7, dmgMul: 1.3, radius: 16, color: 0xe74c3c,
      attack: 'melee', attackCooldown: 1.1, weight: common, difficulty: 'hard',
    },
    wind_sylph: {
      hpMul: 0.75, speedMul: 1.6, dmgMul: 1.0, radius: 11, color: 0xaed6f1,
      attack: 'caster', spells: ['arc_lightning'], range: 180, preferRange: 120,
      attackCooldown: 1.8, weight: common, difficulty: 'hard',
    },
    tomb_guard: {
      hpMul: 1.65, speedMul: 0.8, dmgMul: 1.35, radius: 16, color: 0xb7950b,
      attack: 'melee', attackCooldown: 1.05, weight: common, difficulty: 'hard',
    },
    spore_fungus: {
      hpMul: 1.3, speedMul: 0.6, dmgMul: 1.1, radius: 15, color: 0xa569bd,
      attack: 'ranged', projectile: 'orb', range: 175, preferRange: 115,
      projectileSpeed: 220, projectileRadius: 8, projectileColor: 0xd2b4de,
      attackCooldown: 1.4, weight: common, difficulty: 'normal',
    },
    glacier_cub: {
      hpMul: 1.4, speedMul: 0.95, dmgMul: 1.25, radius: 15, color: 0xd4e6f1,
      attack: 'melee', attackCooldown: 1.0, weight: common, difficulty: 'hard',
    },
    night_owl: {
      hpMul: 0.85, speedMul: 1.35, dmgMul: 1.05, radius: 12, color: 0x1c2833,
      attack: 'ranged', projectile: 'arrow', range: 210, preferRange: 145,
      projectileSpeed: 350, projectileRadius: 4, projectileColor: 0x566573,
      attackCooldown: 1.15, weight: common, difficulty: 'normal',
    },
    brimstone_imp: {
      hpMul: 0.9, speedMul: 1.25, dmgMul: 1.1, radius: 12, color: 0xcb4335,
      attack: 'caster', spells: ['firebolt'], range: 200, preferRange: 130,
      projectileSpeed: 400, projectileRadius: 8, projectileColor: 0xe74c3c,
      attackCooldown: 1.7, weight: common, difficulty: 'nightmare',
    },
    reed_stalker: {
      hpMul: 1.15, speedMul: 1.2, dmgMul: 1.2, radius: 14, color: 0x7d6608,
      attack: 'melee', attackCooldown: 0.9, weight: common, difficulty: 'normal',
    },

    // Elites
    thunder_hawk: {
      hpMul: 2.0, speedMul: 1.35, dmgMul: 1.45, radius: 16, color: 0x5dade2,
      attack: 'caster', spells: ['electric_bolt', 'arc_lightning', 'electric_storm'],
      range: 255, preferRange: 150, attackCooldown: 1.15,
      novaRadius: 105, novaCooldown: 4.0,
      weight: elite, isElite: true, difficulty: 'hard',
    },
    blood_ogre: {
      hpMul: 2.8, speedMul: 0.7, dmgMul: 1.75, radius: 22, color: 0x922b21,
      attack: 'melee', attackCooldown: 1.05, weight: elite, isElite: true, difficulty: 'nightmare',
    },
    mirage_dancer: {
      hpMul: 1.8, speedMul: 1.4, dmgMul: 1.4, radius: 14, color: 0xf5b041,
      attack: 'ranged', projectile: 'orb', range: 230, preferRange: 145,
      projectileSpeed: 320, projectileRadius: 7, projectileColor: 0xf9e79f,
      attackCooldown: 1.0, weight: elite, isElite: true, difficulty: 'hard',
    },
    frost_berserker: {
      hpMul: 2.4, speedMul: 1.15, dmgMul: 1.65, radius: 17, color: 0x5dade2,
      attack: 'melee', attackCooldown: 0.8, weight: elite, isElite: true, difficulty: 'nightmare',
    },
    venom_alchemist: {
      hpMul: 2.1, speedMul: 0.95, dmgMul: 1.4, radius: 15, color: 0x1e8449,
      attack: 'caster', spells: ['poison_cloud', 'ice_shard', 'firebolt'],
      range: 240, preferRange: 145, projectileSpeed: 420, projectileRadius: 8,
      projectileColor: 0x58d68d, attackCooldown: 1.2,
      novaRadius: 100, novaCooldown: 3.9,
      weight: elite, isElite: true, difficulty: 'hard',
    },
    obsidian_guardian: {
      hpMul: 3.1, speedMul: 0.55, dmgMul: 1.8, radius: 23, color: 0x1c2833,
      attack: 'melee', attackCooldown: 1.3, weight: elite, isElite: true, difficulty: 'nightmare',
    },
    soul_harvester: {
      hpMul: 2.2, speedMul: 1.05, dmgMul: 1.5, radius: 16, color: 0x4a235a,
      attack: 'caster', spells: ['skull_wave', 'arc_lightning', 'ice_shard'],
      range: 245, preferRange: 145, projectileSpeed: 340, projectileRadius: 10,
      projectileColor: 0x7d3c98, attackCooldown: 1.2, skullCount: 7,
      weight: elite, isElite: true, difficulty: 'apocalypse',
    },
    lava_serpent: {
      hpMul: 2.5, speedMul: 0.9, dmgMul: 1.6, radius: 19, color: 0xd35400,
      attack: 'caster', spells: ['firebreath', 'flame_nova', 'firebolt'],
      range: 235, preferRange: 140, projectileSpeed: 410, projectileRadius: 9,
      projectileColor: 0xe67e22, attackCooldown: 1.15,
      novaRadius: 108, novaCooldown: 4.0,
      weight: elite, isElite: true, difficulty: 'nightmare',
    },
    mirror_wraith: {
      hpMul: 1.9, speedMul: 1.3, dmgMul: 1.45, radius: 14, color: 0xd5d8dc,
      attack: 'caster', spells: ['arc_lightning', 'electric_bolt'],
      range: 250, preferRange: 150, attackCooldown: 1.1,
      weight: elite, isElite: true, difficulty: 'hard',
    },
    plague_rat_king: {
      hpMul: 2.3, speedMul: 1.2, dmgMul: 1.5, radius: 16, color: 0x6e2c00,
      attack: 'caster', spells: ['poison_cloud', 'firebolt'],
      range: 220, preferRange: 135, projectileSpeed: 390, projectileRadius: 8,
      projectileColor: 0x88ff44, attackCooldown: 1.2,
      novaRadius: 95, novaCooldown: 3.8,
      weight: elite, isElite: true, difficulty: 'hard',
    },
    storm_rider: {
      hpMul: 2.0, speedMul: 1.45, dmgMul: 1.55, radius: 15, color: 0x2874a6,
      attack: 'ranged', projectile: 'orb', range: 240, preferRange: 155,
      projectileSpeed: 380, projectileRadius: 7, projectileColor: 0x5dade2,
      attackCooldown: 0.95, weight: elite, isElite: true, difficulty: 'nightmare',
    },
    ironbark_treant: {
      hpMul: 2.9, speedMul: 0.6, dmgMul: 1.7, radius: 24, color: 0x145a32,
      attack: 'melee', attackCooldown: 1.2, weight: elite, isElite: true, difficulty: 'hard',
    },
    crimson_cultist: {
      hpMul: 2.0, speedMul: 1.0, dmgMul: 1.45, radius: 15, color: 0xc0392b,
      attack: 'caster', spells: ['firebolt', 'flame_nova', 'arc_lightning'],
      range: 250, preferRange: 145, projectileSpeed: 430, projectileRadius: 9,
      projectileColor: 0xe74c3c, attackCooldown: 1.15,
      novaRadius: 100, novaCooldown: 4.1,
      weight: elite, isElite: true, difficulty: 'nightmare',
    },
    void_imp_lord: {
      hpMul: 2.15, speedMul: 1.25, dmgMul: 1.55, radius: 15, color: 0x2c003e,
      attack: 'caster', spells: ['skull_wave', 'electric_bolt', 'firebolt'],
      range: 245, preferRange: 145, projectileSpeed: 400, projectileRadius: 9,
      projectileColor: 0x8e44ad, attackCooldown: 1.15, skullCount: 6,
      weight: elite, isElite: true, difficulty: 'apocalypse',
    },
    sapphire_drake: {
      hpMul: 2.6, speedMul: 1.0, dmgMul: 1.6, radius: 20, color: 0x1a5276,
      attack: 'caster', spells: ['ice_shard', 'firebreath', 'electric_bolt'],
      range: 260, preferRange: 150, projectileSpeed: 450, projectileRadius: 9,
      projectileColor: 0x5dade2, attackCooldown: 1.1,
      weight: elite, isElite: true, difficulty: 'nightmare',
    },

    // Bosses
    eclipse_sphinx: {
      hpMul: 3.6, speedMul: 0.7, dmgMul: 1.55, radius: 34, color: 0xf4d03f,
      attack: 'caster',
      spells: ['shadow_eclipse', 'cataclysm_beam', 'soul_rend', 'firebolt'],
      range: 280, preferRange: 160, projectileSpeed: 440, projectileRadius: 9,
      projectileColor: 0xf9e79f, attackCooldown: 1.2,
      novaRadius: 130, novaCooldown: 5.0,
      weight: boss, isBoss: true, difficulty: 'nightmare',
    },
    magma_colossus: {
      hpMul: 4.8, speedMul: 0.42, dmgMul: 1.85, radius: 46, color: 0xa04000,
      attack: 'caster',
      spells: ['flame_nova', 'infernal_judgment', 'firebreath', 'firebolt'],
      range: 270, preferRange: 150, projectileSpeed: 430, projectileRadius: 10,
      projectileColor: 0xe67e22, attackCooldown: 1.2,
      novaRadius: 140, novaCooldown: 4.5,
      weight: boss, isBoss: true, difficulty: 'apocalypse',
    },
    arctic_leviathan: {
      hpMul: 4.4, speedMul: 0.5, dmgMul: 1.7, radius: 44, color: 0x85c1e9,
      attack: 'caster',
      spells: ['frost_apocalypse', 'ice_shard', 'death_knell', 'electric_bolt'],
      range: 300, preferRange: 170, projectileSpeed: 460, projectileRadius: 10,
      projectileColor: 0xd6eaf8, attackCooldown: 1.2,
      novaRadius: 145, novaCooldown: 5.0,
      weight: boss, isBoss: true, difficulty: 'nightmare',
    },
    blight_emperor: {
      hpMul: 3.9, speedMul: 0.65, dmgMul: 1.6, radius: 36, color: 0x196f3d,
      attack: 'caster',
      spells: ['plague_burst', 'poison_cloud', 'blood_pact', 'ice_shard'],
      range: 270, preferRange: 155, projectileSpeed: 420, projectileRadius: 9,
      projectileColor: 0x58d68d, attackCooldown: 1.2,
      novaRadius: 125, novaCooldown: 4.4,
      weight: boss, isBoss: true, difficulty: 'hard',
    },
    chronomancer: {
      hpMul: 3.2, speedMul: 0.85, dmgMul: 1.5, radius: 28, color: 0xaf7ac5,
      attack: 'caster',
      spells: ['void_collapse', 'arc_lightning', 'soul_rend', 'electric_bolt'],
      range: 285, preferRange: 160, attackCooldown: 1.15,
      novaRadius: 130, novaCooldown: 5.0,
      weight: boss, isBoss: true, difficulty: 'apocalypse',
    },
    dread_naga: {
      hpMul: 3.7, speedMul: 0.9, dmgMul: 1.65, radius: 32, color: 0x117a65,
      attack: 'caster',
      spells: ['abyss_nova', 'poison_cloud', 'cataclysm_beam', 'firebolt'],
      range: 265, preferRange: 150, projectileSpeed: 430, projectileRadius: 9,
      projectileColor: 0x1abc9c, attackCooldown: 1.15,
      novaRadius: 120, novaCooldown: 4.6,
      weight: boss, isBoss: true, difficulty: 'hard',
    },
    solar_phoenix: {
      hpMul: 3.5, speedMul: 1.1, dmgMul: 1.7, radius: 33, color: 0xff9f1c,
      attack: 'caster',
      spells: ['infernal_judgment', 'flame_nova', 'firebreath', 'firebolt'],
      range: 290, preferRange: 165, projectileSpeed: 470, projectileRadius: 10,
      projectileColor: 0xff6b35, attackCooldown: 1.1,
      novaRadius: 130, novaCooldown: 4.0,
      weight: boss, isBoss: true, difficulty: 'nightmare',
    },
    abyssal_kraken: {
      hpMul: 4.6, speedMul: 0.48, dmgMul: 1.8, radius: 45, color: 0x0e2f44,
      attack: 'caster',
      spells: ['void_collapse', 'electric_storm', 'abyss_nova', 'electric_bolt'],
      range: 280, preferRange: 155, attackCooldown: 1.25,
      novaRadius: 145, novaCooldown: 4.8,
      weight: boss, isBoss: true, difficulty: 'apocalypse',
    },
    bone_emperor: {
      hpMul: 3.8, speedMul: 0.6, dmgMul: 1.55, radius: 34, color: 0xece5d0,
      attack: 'caster',
      spells: ['skull_wave', 'death_knell', 'shadow_eclipse', 'ice_shard'],
      range: 275, preferRange: 155, projectileSpeed: 350, projectileRadius: 11,
      projectileColor: 0xd5d0c0, attackCooldown: 1.25, skullCount: 12,
      novaRadius: 125, novaCooldown: 5.0,
      weight: boss, isBoss: true, difficulty: 'nightmare',
    },
    world_ender: {
      hpMul: 5.5, speedMul: 0.45, dmgMul: 2.0, radius: 52, color: 0x1a0033,
      attack: 'caster',
      spells: ['shadow_eclipse', 'void_collapse', 'cataclysm_beam', 'blood_pact', 'firebolt'],
      range: 320, preferRange: 180, projectileSpeed: 450, projectileRadius: 10,
      projectileColor: 0xff44ff, attackCooldown: 1.2,
      novaRadius: 160, novaCooldown: 5.2,
      weight: boss, isBoss: true, difficulty: 'apocalypse',
    },

    // ─── Expansão 2 (+50 tipos) ────────────────────────────────
    // Normais (24)
    mushroom_brute: {
      hpMul: 1.45, speedMul: 0.75, dmgMul: 1.25, radius: 17, color: 0xc0392b,
      attack: 'melee', attackCooldown: 1.15, weight: common, difficulty: 'normal',
    },
    salt_golem: {
      hpMul: 1.75, speedMul: 0.65, dmgMul: 1.35, radius: 18, color: 0xf5e6c8,
      attack: 'melee', attackCooldown: 1.25, weight: common, difficulty: 'hard',
    },
    fox_trickster: {
      hpMul: 0.85, speedMul: 1.4, dmgMul: 1.05, radius: 12, color: 0xe67e22,
      attack: 'caster', spells: ['firebolt'], range: 210, preferRange: 140,
      projectileSpeed: 410, projectileRadius: 8, projectileColor: 0xf5b041,
      attackCooldown: 1.6, weight: common, difficulty: 'normal',
    },
    quill_hunter: {
      hpMul: 1.0, speedMul: 1.15, dmgMul: 1.1, radius: 13, color: 0x6e4a2e,
      attack: 'ranged', projectile: 'arrow', range: 215, preferRange: 145,
      projectileSpeed: 350, projectileRadius: 4, projectileColor: 0xc4a882,
      attackCooldown: 1.15, weight: common, difficulty: 'normal',
    },
    peat_zombie: {
      hpMul: 1.5, speedMul: 0.68, dmgMul: 1.2, radius: 15, color: 0x4a5c3a,
      attack: 'melee', attackCooldown: 1.2, weight: common, difficulty: 'normal',
    },
    lantern_spirit: {
      hpMul: 0.7, speedMul: 1.35, dmgMul: 1.0, radius: 11, color: 0xf4d03f,
      attack: 'caster', spells: ['ice_shard'], range: 205, preferRange: 135,
      projectileSpeed: 420, projectileRadius: 7, projectileColor: 0xf9e79f,
      attackCooldown: 1.7, weight: common, difficulty: 'hard',
    },
    cliff_goat: {
      hpMul: 1.2, speedMul: 1.25, dmgMul: 1.2, radius: 14, color: 0xb0a090,
      attack: 'melee', attackCooldown: 0.9, weight: common, difficulty: 'normal',
    },
    reef_shark: {
      hpMul: 1.3, speedMul: 1.35, dmgMul: 1.3, radius: 15, color: 0x5d8aa8,
      attack: 'melee', attackCooldown: 0.85, weight: common, difficulty: 'hard',
    },
    dust_mephit: {
      hpMul: 0.8, speedMul: 1.3, dmgMul: 1.05, radius: 12, color: 0xc2a05a,
      attack: 'caster', spells: ['firebolt'], range: 195, preferRange: 130,
      projectileSpeed: 390, projectileRadius: 8, projectileColor: 0xe8d090,
      attackCooldown: 1.65, weight: common, difficulty: 'normal',
    },
    bark_spider: {
      hpMul: 1.05, speedMul: 1.2, dmgMul: 1.15, radius: 13, color: 0x5d4037,
      attack: 'melee', attackCooldown: 0.9, weight: common, difficulty: 'normal',
    },
    snow_hare: {
      hpMul: 0.65, speedMul: 1.7, dmgMul: 0.9, radius: 11, color: 0xf0f4f8,
      attack: 'melee', attackCooldown: 0.65, weight: common, difficulty: 'normal',
    },
    torch_bearer: {
      hpMul: 1.1, speedMul: 1.05, dmgMul: 1.15, radius: 14, color: 0xd35400,
      attack: 'ranged', projectile: 'fireball', range: 200, preferRange: 135,
      projectileSpeed: 270, projectileRadius: 7, projectileColor: 0xff6622,
      attackCooldown: 1.35, weight: common, difficulty: 'hard',
    },
    bog_mosquito: {
      hpMul: 0.55, speedMul: 1.65, dmgMul: 0.85, radius: 10, color: 0x556b2f,
      attack: 'melee', attackCooldown: 0.6, weight: common, difficulty: 'normal',
    },
    rune_scribe: {
      hpMul: 0.95, speedMul: 1.0, dmgMul: 1.15, radius: 13, color: 0x5b2c6f,
      attack: 'caster', spells: ['arc_lightning'], range: 185, preferRange: 125,
      attackCooldown: 1.75, weight: common, difficulty: 'hard',
    },
    clay_soldier: {
      hpMul: 1.55, speedMul: 0.8, dmgMul: 1.3, radius: 16, color: 0xa07850,
      attack: 'melee', attackCooldown: 1.1, weight: common, difficulty: 'normal',
    },
    pearl_diver: {
      hpMul: 0.9, speedMul: 1.2, dmgMul: 1.05, radius: 13, color: 0x48c9b0,
      attack: 'ranged', projectile: 'orb', range: 205, preferRange: 140,
      projectileSpeed: 300, projectileRadius: 6, projectileColor: 0x76d7c4,
      attackCooldown: 1.2, weight: common, difficulty: 'normal',
    },
    night_panther: {
      hpMul: 1.1, speedMul: 1.5, dmgMul: 1.25, radius: 14, color: 0x1c1c28,
      attack: 'melee', attackCooldown: 0.7, weight: common, difficulty: 'hard',
    },
    hive_drone: {
      hpMul: 0.75, speedMul: 1.4, dmgMul: 0.95, radius: 11, color: 0xf1c40f,
      attack: 'melee', attackCooldown: 0.75, weight: common, difficulty: 'normal',
    },
    frost_toad: {
      hpMul: 1.25, speedMul: 0.85, dmgMul: 1.15, radius: 15, color: 0x85c1e9,
      attack: 'caster', spells: ['ice_shard'], range: 190, preferRange: 125,
      projectileSpeed: 400, projectileRadius: 8, projectileColor: 0xaed6f1,
      attackCooldown: 1.7, weight: common, difficulty: 'hard',
    },
    scrap_bandit: {
      hpMul: 1.0, speedMul: 1.2, dmgMul: 1.1, radius: 13, color: 0x7f8c8d,
      attack: 'ranged', projectile: 'arrow', range: 200, preferRange: 135,
      projectileSpeed: 330, projectileRadius: 4, projectileColor: 0xb2babb,
      attackCooldown: 1.15, weight: common, difficulty: 'normal',
    },
    vine_creeper: {
      hpMul: 1.35, speedMul: 0.7, dmgMul: 1.2, radius: 15, color: 0x27ae60,
      attack: 'melee', attackCooldown: 1.15, weight: common, difficulty: 'normal',
    },
    cinder_sprite: {
      hpMul: 0.6, speedMul: 1.55, dmgMul: 0.95, radius: 10, color: 0xe74c3c,
      attack: 'caster', spells: ['firebolt'], range: 200, preferRange: 130,
      projectileSpeed: 420, projectileRadius: 7, projectileColor: 0xff6644,
      attackCooldown: 1.7, weight: common, difficulty: 'nightmare',
    },
    tunnel_mole: {
      hpMul: 1.15, speedMul: 1.15, dmgMul: 1.15, radius: 13, color: 0x6d4c41,
      attack: 'melee', attackCooldown: 0.9, weight: common, difficulty: 'normal',
    },
    glass_imp: {
      hpMul: 0.75, speedMul: 1.35, dmgMul: 1.05, radius: 11, color: 0xd5f5e3,
      attack: 'caster', spells: ['ice_shard'], range: 210, preferRange: 140,
      projectileSpeed: 440, projectileRadius: 7, projectileColor: 0xa9dfbf,
      attackCooldown: 1.65, weight: common, difficulty: 'hard',
    },

    // Elites (16)
    thunder_boar: {
      hpMul: 2.5, speedMul: 1.1, dmgMul: 1.65, radius: 19, color: 0x5dade2,
      attack: 'caster', spells: ['electric_bolt', 'arc_lightning', 'electric_storm'],
      range: 230, preferRange: 140, attackCooldown: 1.1,
      novaRadius: 100, novaCooldown: 4.0,
      weight: elite, isElite: true, difficulty: 'hard',
    },
    blood_knight: {
      hpMul: 2.7, speedMul: 0.9, dmgMul: 1.75, radius: 18, color: 0x922b21,
      attack: 'melee', attackCooldown: 0.9, weight: elite, isElite: true, difficulty: 'nightmare',
    },
    sand_djinni: {
      hpMul: 2.1, speedMul: 1.15, dmgMul: 1.5, radius: 16, color: 0xd4a017,
      attack: 'caster', spells: ['flame_nova', 'firebolt', 'arc_lightning'],
      range: 250, preferRange: 150, projectileSpeed: 430, projectileRadius: 9,
      projectileColor: 0xf4d03f, attackCooldown: 1.15,
      novaRadius: 105, novaCooldown: 4.1,
      weight: elite, isElite: true, difficulty: 'hard',
    },
    poison_archer: {
      hpMul: 1.9, speedMul: 1.2, dmgMul: 1.45, radius: 14, color: 0x1e8449,
      attack: 'ranged', projectile: 'arrow', range: 250, preferRange: 165,
      projectileSpeed: 380, projectileRadius: 5, projectileColor: 0x58d68d,
      attackCooldown: 1.0, weight: elite, isElite: true, difficulty: 'hard',
    },
    jade_golem: {
      hpMul: 3.0, speedMul: 0.55, dmgMul: 1.8, radius: 23, color: 0x117a65,
      attack: 'melee', attackCooldown: 1.3, weight: elite, isElite: true, difficulty: 'nightmare',
    },
    shadow_priest: {
      hpMul: 2.0, speedMul: 0.95, dmgMul: 1.45, radius: 15, color: 0x2c003e,
      attack: 'caster', spells: ['skull_wave', 'ice_shard', 'arc_lightning'],
      range: 255, preferRange: 150, projectileSpeed: 400, projectileRadius: 9,
      projectileColor: 0x8e44ad, attackCooldown: 1.2, skullCount: 7,
      weight: elite, isElite: true, difficulty: 'apocalypse',
    },
    bladed_mantis: {
      hpMul: 2.0, speedMul: 1.4, dmgMul: 1.6, radius: 15, color: 0x27ae60,
      attack: 'melee', attackCooldown: 0.7, weight: elite, isElite: true, difficulty: 'nightmare',
    },
    storm_witch: {
      hpMul: 2.15, speedMul: 1.05, dmgMul: 1.5, radius: 15, color: 0x2874a6,
      attack: 'caster', spells: ['electric_bolt', 'electric_storm', 'arc_lightning'],
      range: 260, preferRange: 155, attackCooldown: 1.1,
      novaRadius: 110, novaCooldown: 3.9,
      weight: elite, isElite: true, difficulty: 'nightmare',
    },
    furnace_beast: {
      hpMul: 2.6, speedMul: 0.85, dmgMul: 1.65, radius: 20, color: 0xcb4335,
      attack: 'caster', spells: ['firebreath', 'flame_nova', 'firebolt'],
      range: 235, preferRange: 140, projectileSpeed: 420, projectileRadius: 9,
      projectileColor: 0xe74c3c, attackCooldown: 1.15,
      novaRadius: 108, novaCooldown: 4.0,
      weight: elite, isElite: true, difficulty: 'nightmare',
    },
    crystal_archer: {
      hpMul: 1.85, speedMul: 1.15, dmgMul: 1.4, radius: 14, color: 0xaed6f1,
      attack: 'ranged', projectile: 'orb', range: 255, preferRange: 170,
      projectileSpeed: 400, projectileRadius: 6, projectileColor: 0xd6eaf8,
      attackCooldown: 1.05, weight: elite, isElite: true, difficulty: 'hard',
    },
    void_hound: {
      hpMul: 2.2, speedMul: 1.45, dmgMul: 1.6, radius: 16, color: 0x1a0033,
      attack: 'melee', attackCooldown: 0.7, weight: elite, isElite: true, difficulty: 'apocalypse',
    },
    plague_swarm: {
      hpMul: 2.1, speedMul: 1.1, dmgMul: 1.4, radius: 16, color: 0x6e2c00,
      attack: 'caster', spells: ['poison_cloud', 'plague_burst', 'firebolt'],
      range: 230, preferRange: 140, projectileSpeed: 390, projectileRadius: 8,
      projectileColor: 0x88ff44, attackCooldown: 1.2,
      novaRadius: 100, novaCooldown: 3.8,
      weight: elite, isElite: true, difficulty: 'hard',
    },
    iron_sentinel: {
      hpMul: 3.1, speedMul: 0.5, dmgMul: 1.85, radius: 24, color: 0x566573,
      attack: 'melee', attackCooldown: 1.35, weight: elite, isElite: true, difficulty: 'nightmare',
    },
    aurora_mage: {
      hpMul: 2.0, speedMul: 1.0, dmgMul: 1.45, radius: 15, color: 0xaf7ac5,
      attack: 'caster', spells: ['ice_shard', 'arc_lightning', 'electric_bolt'],
      range: 265, preferRange: 155, projectileSpeed: 460, projectileRadius: 9,
      projectileColor: 0xd2b4de, attackCooldown: 1.15,
      weight: elite, isElite: true, difficulty: 'hard',
    },
    ash_wyvern: {
      hpMul: 2.5, speedMul: 1.15, dmgMul: 1.55, radius: 19, color: 0x6e2c00,
      attack: 'caster', spells: ['firebreath', 'firebolt', 'flame_nova'],
      range: 250, preferRange: 150, projectileSpeed: 440, projectileRadius: 9,
      projectileColor: 0xe67e22, attackCooldown: 1.1,
      novaRadius: 105, novaCooldown: 4.0,
      weight: elite, isElite: true, difficulty: 'nightmare',
    },
    bone_reaver: {
      hpMul: 2.3, speedMul: 1.05, dmgMul: 1.55, radius: 17, color: 0xece5d0,
      attack: 'caster', spells: ['skull_wave', 'soul_rend', 'ice_shard'],
      range: 240, preferRange: 145, projectileSpeed: 340, projectileRadius: 10,
      projectileColor: 0xd5d0c0, attackCooldown: 1.2, skullCount: 8,
      weight: elite, isElite: true, difficulty: 'apocalypse',
    },

    // Bosses (10)
    tempest_queen: {
      hpMul: 3.6, speedMul: 0.9, dmgMul: 1.6, radius: 32, color: 0x5dade2,
      attack: 'caster',
      spells: ['electric_storm', 'electric_bolt', 'cataclysm_beam', 'arc_lightning'],
      range: 290, preferRange: 165, attackCooldown: 1.15,
      novaRadius: 135, novaCooldown: 4.5,
      weight: boss, isBoss: true, difficulty: 'nightmare',
    },
    forge_titan: {
      hpMul: 4.9, speedMul: 0.42, dmgMul: 1.9, radius: 47, color: 0xa04000,
      attack: 'caster',
      spells: ['infernal_judgment', 'flame_nova', 'firebreath', 'firebolt'],
      range: 275, preferRange: 155, projectileSpeed: 430, projectileRadius: 10,
      projectileColor: 0xe67e22, attackCooldown: 1.2,
      novaRadius: 145, novaCooldown: 4.5,
      weight: boss, isBoss: true, difficulty: 'apocalypse',
    },
    coral_empress: {
      hpMul: 3.8, speedMul: 0.75, dmgMul: 1.55, radius: 34, color: 0xe74c3c,
      attack: 'caster',
      spells: ['abyss_nova', 'poison_cloud', 'ice_shard', 'electric_bolt'],
      range: 270, preferRange: 155, projectileSpeed: 420, projectileRadius: 9,
      projectileColor: 0xf1948a, attackCooldown: 1.2,
      novaRadius: 125, novaCooldown: 4.6,
      weight: boss, isBoss: true, difficulty: 'hard',
    },
    nightmare_king: {
      hpMul: 4.0, speedMul: 0.7, dmgMul: 1.7, radius: 36, color: 0x1a0a20,
      attack: 'caster',
      spells: ['shadow_eclipse', 'soul_rend', 'void_collapse', 'skull_wave'],
      range: 280, preferRange: 160, projectileSpeed: 360, projectileRadius: 11,
      projectileColor: 0x4a0080, attackCooldown: 1.2, skullCount: 11,
      novaRadius: 135, novaCooldown: 5.0,
      weight: boss, isBoss: true, difficulty: 'apocalypse',
    },
    elder_beholder: {
      hpMul: 3.4, speedMul: 0.55, dmgMul: 1.5, radius: 33, color: 0x7d3c98,
      attack: 'caster',
      spells: ['cataclysm_beam', 'void_collapse', 'arc_lightning', 'electric_bolt'],
      range: 260, preferRange: 150, attackCooldown: 1.2,
      novaRadius: 125, novaCooldown: 5.2,
      weight: boss, isBoss: true, difficulty: 'hard',
    },
    doom_hydra: {
      hpMul: 4.6, speedMul: 0.55, dmgMul: 1.75, radius: 42, color: 0x145a32,
      attack: 'caster',
      spells: ['plague_burst', 'poison_cloud', 'firebreath', 'blood_pact'],
      range: 255, preferRange: 145, attackCooldown: 1.15,
      novaRadius: 125, novaCooldown: 4.3,
      weight: boss, isBoss: true, difficulty: 'nightmare',
    },
    astral_serpent: {
      hpMul: 4.2, speedMul: 0.65, dmgMul: 1.7, radius: 40, color: 0xaf7ac5,
      attack: 'caster',
      spells: ['void_collapse', 'shadow_eclipse', 'death_knell', 'ice_shard'],
      range: 300, preferRange: 170, projectileSpeed: 450, projectileRadius: 9,
      projectileColor: 0xd2b4de, attackCooldown: 1.2,
      novaRadius: 140, novaCooldown: 5.0,
      weight: boss, isBoss: true, difficulty: 'apocalypse',
    },
    war_god_avatar: {
      hpMul: 4.5, speedMul: 0.8, dmgMul: 1.85, radius: 38, color: 0xb9770e,
      attack: 'caster',
      spells: ['infernal_judgment', 'electric_storm', 'cataclysm_beam', 'firebolt'],
      range: 285, preferRange: 160, projectileSpeed: 440, projectileRadius: 10,
      projectileColor: 0xf4d03f, attackCooldown: 1.1,
      novaRadius: 135, novaCooldown: 4.4,
      weight: boss, isBoss: true, difficulty: 'nightmare',
    },
    necrotic_colossus: {
      hpMul: 5.0, speedMul: 0.4, dmgMul: 1.9, radius: 48, color: 0xd5d0c0,
      attack: 'caster',
      spells: ['skull_wave', 'death_knell', 'abyss_nova', 'soul_rend'],
      range: 275, preferRange: 155, projectileSpeed: 340, projectileRadius: 11,
      projectileColor: 0xece5d0, attackCooldown: 1.3, skullCount: 14,
      novaRadius: 145, novaCooldown: 5.2,
      weight: boss, isBoss: true, difficulty: 'apocalypse',
    },
    chaos_primordial: {
      hpMul: 5.6, speedMul: 0.5, dmgMul: 2.05, radius: 50, color: 0x6c3483,
      attack: 'caster',
      spells: ['shadow_eclipse', 'void_collapse', 'infernal_judgment', 'frost_apocalypse', 'electric_bolt'],
      range: 320, preferRange: 180, projectileSpeed: 460, projectileRadius: 10,
      projectileColor: 0xff44ff, attackCooldown: 1.15,
      novaRadius: 155, novaCooldown: 5.0,
      weight: boss, isBoss: true, difficulty: 'apocalypse',
    },

    // ─── Expansão 3 +100 ─────────────────────────────────────
    // Normals (48)
    pebble_sprite: {
      hpMul: 1.00, speedMul: 0.91, dmgMul: 1.25, radius: 16, color: 0x95a5a6,
      attack: 'melee',
      weight: common, difficulty: 'normal',
    },
    reed_rat: {
      hpMul: 1.50, speedMul: 1.07, dmgMul: 1.25, radius: 11, color: 0x7d6608,
      attack: 'melee',
      weight: common, difficulty: 'normal',
    },
    tide_urchin: {
      hpMul: 0.80, speedMul: 1.23, dmgMul: 1.09, radius: 14, color: 0x5d8aa8,
      attack: 'melee',
      weight: common, difficulty: 'normal',
    },
    cinder_moth: {
      hpMul: 0.80, speedMul: 1.47, dmgMul: 1.09, radius: 14, color: 0xe67e22,
      attack: 'ranged', projectile: 'fireball',
      range: 185, preferRange: 125, projectileSpeed: 240, projectileRadius: 6, projectileColor: 0xff8844, attackCooldown: 1.4,
      weight: common, difficulty: 'normal',
    },
    pine_sprite: {
      hpMul: 0.80, speedMul: 0.91, dmgMul: 1.09, radius: 14, color: 0x1e8449,
      attack: 'caster', spells: ['firebolt'],
      range: 210, preferRange: 135, projectileSpeed: 400, projectileRadius: 7, projectileColor: 0x58d68d, attackCooldown: 1.6,
      weight: common, difficulty: 'normal',
    },
    copper_goblin: {
      hpMul: 1.00, speedMul: 1.47, dmgMul: 1.09, radius: 16, color: 0xb87333,
      attack: 'ranged', projectile: 'arrow',
      range: 205, preferRange: 140, projectileSpeed: 330, projectileRadius: 4, projectileColor: 0xd4c4a0, attackCooldown: 1.2,
      weight: common, difficulty: 'normal',
    },
    mist_wisp: {
      hpMul: 1.60, speedMul: 1.47, dmgMul: 1.09, radius: 12, color: 0xd5d8dc,
      attack: 'caster', spells: ['ice_shard'],
      range: 215, preferRange: 140, projectileSpeed: 430, projectileRadius: 7, projectileColor: 0xaed6f1, attackCooldown: 1.55,
      weight: common, difficulty: 'hard',
    },
    brine_crab: {
      hpMul: 0.70, speedMul: 1.39, dmgMul: 0.85, radius: 13, color: 0x48c9b0,
      attack: 'melee',
      weight: common, difficulty: 'normal',
    },
    soot_imp: {
      hpMul: 1.50, speedMul: 1.15, dmgMul: 1.09, radius: 11, color: 0x566573,
      attack: 'ranged', projectile: 'fireball',
      range: 190, preferRange: 130, projectileSpeed: 230, projectileRadius: 7, projectileColor: 0xff5533, attackCooldown: 1.45,
      weight: common, difficulty: 'normal',
    },
    thistle_boar: {
      hpMul: 0.90, speedMul: 1.23, dmgMul: 1.01, radius: 15, color: 0x6e4a2e,
      attack: 'melee',
      weight: common, difficulty: 'normal',
    },
    kelp_strider: {
      hpMul: 0.90, speedMul: 1.31, dmgMul: 1.25, radius: 15, color: 0x117a65,
      attack: 'melee',
      weight: common, difficulty: 'normal',
    },
    ember_gnat: {
      hpMul: 0.70, speedMul: 0.83, dmgMul: 0.93, radius: 13, color: 0xcb4335,
      attack: 'ranged', projectile: 'orb',
      range: 175, preferRange: 120, projectileSpeed: 260, projectileRadius: 5, projectileColor: 0xff8844, attackCooldown: 1.25,
      weight: common, difficulty: 'normal',
    },
    chalk_golem_cub: {
      hpMul: 1.20, speedMul: 1.47, dmgMul: 1.01, radius: 18, color: 0xf5e6c8,
      attack: 'melee',
      weight: common, difficulty: 'hard',
    },
    dusk_ferret: {
      hpMul: 0.80, speedMul: 0.75, dmgMul: 1.09, radius: 14, color: 0x5d4037,
      attack: 'melee',
      weight: common, difficulty: 'normal',
    },
    bog_newt: {
      hpMul: 1.50, speedMul: 1.39, dmgMul: 1.09, radius: 11, color: 0x556b2f,
      attack: 'melee',
      weight: common, difficulty: 'normal',
    },
    crystal_mite: {
      hpMul: 0.90, speedMul: 1.47, dmgMul: 0.85, radius: 15, color: 0xaed6f1,
      attack: 'caster', spells: ['ice_shard'],
      range: 200, preferRange: 130, projectileSpeed: 420, projectileRadius: 6, projectileColor: 0xd6eaf8, attackCooldown: 1.7,
      weight: common, difficulty: 'normal',
    },
    rust_scorpion: {
      hpMul: 1.00, speedMul: 1.07, dmgMul: 1.09, radius: 16, color: 0xa04000,
      attack: 'melee',
      weight: common, difficulty: 'hard',
    },
    pollen_pixie: {
      hpMul: 0.90, speedMul: 0.91, dmgMul: 1.09, radius: 15, color: 0xf9e79f,
      attack: 'caster', spells: ['firebolt'],
      range: 205, preferRange: 135, projectileSpeed: 390, projectileRadius: 7, projectileColor: 0xf4d03f, attackCooldown: 1.55,
      weight: common, difficulty: 'normal',
    },
    shale_basher: {
      hpMul: 0.90, speedMul: 1.15, dmgMul: 1.01, radius: 15, color: 0x7f8c8d,
      attack: 'melee',
      weight: common, difficulty: 'hard',
    },
    frost_vole: {
      hpMul: 0.70, speedMul: 0.91, dmgMul: 0.85, radius: 13, color: 0xd4e6f1,
      attack: 'melee',
      weight: common, difficulty: 'normal',
    },
    tar_slug: {
      hpMul: 1.50, speedMul: 1.23, dmgMul: 0.93, radius: 11, color: 0x1c1c28,
      attack: 'melee',
      weight: common, difficulty: 'hard',
    },
    spark_sprite: {
      hpMul: 0.90, speedMul: 1.15, dmgMul: 1.17, radius: 15, color: 0x5dade2,
      attack: 'caster', spells: ['arc_lightning'],
      range: 180, preferRange: 120, attackCooldown: 1.35,
      weight: common, difficulty: 'hard',
    },
    dune_jackal: {
      hpMul: 0.80, speedMul: 0.75, dmgMul: 1.09, radius: 14, color: 0xd4a017,
      attack: 'melee',
      weight: common, difficulty: 'normal',
    },
    lichen_troll_cub: {
      hpMul: 1.30, speedMul: 1.39, dmgMul: 1.09, radius: 11, color: 0x4a6741,
      attack: 'melee',
      weight: common, difficulty: 'hard',
    },
    ivory_skeleton: {
      hpMul: 1.10, speedMul: 1.15, dmgMul: 1.17, radius: 17, color: 0xf5eef0,
      attack: 'melee', attackCooldown: 0.95,
      weight: common, difficulty: 'normal',
    },
    mangrove_croco: {
      hpMul: 1.10, speedMul: 1.47, dmgMul: 0.93, radius: 17, color: 0x145a32,
      attack: 'melee',
      weight: common, difficulty: 'hard',
    },
    storm_finch: {
      hpMul: 0.80, speedMul: 1.15, dmgMul: 1.01, radius: 14, color: 0x2874a6,
      attack: 'ranged', projectile: 'orb',
      range: 220, preferRange: 150, projectileSpeed: 360, projectileRadius: 5, projectileColor: 0x7cf0ff, attackCooldown: 1.3,
      weight: common, difficulty: 'hard',
    },
    ash_cult_initiate: {
      hpMul: 1.40, speedMul: 1.31, dmgMul: 0.93, radius: 12, color: 0x6e2c00,
      attack: 'caster', spells: ['firebolt'],
      range: 215, preferRange: 140, projectileSpeed: 410, projectileRadius: 8, projectileColor: 0xe67e22, attackCooldown: 1.5,
      weight: common, difficulty: 'normal',
    },
    prism_moth: {
      hpMul: 0.70, speedMul: 0.91, dmgMul: 0.85, radius: 13, color: 0xaf7ac5,
      attack: 'caster', spells: ['acid_bolt'],
      range: 220, preferRange: 145, projectileSpeed: 450, projectileRadius: 8, projectileColor: 0x88ff44, attackCooldown: 1.45,
      weight: common, difficulty: 'hard',
    },
    geyser_toad: {
      hpMul: 0.80, speedMul: 0.99, dmgMul: 1.25, radius: 14, color: 0x48c9b0,
      attack: 'melee',
      weight: common, difficulty: 'hard',
    },
    carrion_vulture: {
      hpMul: 1.20, speedMul: 1.47, dmgMul: 0.93, radius: 18, color: 0x6e4a2e,
      attack: 'melee',
      weight: common, difficulty: 'normal',
    },
    magma_grub: {
      hpMul: 0.70, speedMul: 1.47, dmgMul: 0.93, radius: 13, color: 0xcb4335,
      attack: 'melee',
      weight: common, difficulty: 'nightmare',
    },
    void_mote: {
      hpMul: 1.60, speedMul: 1.39, dmgMul: 1.09, radius: 12, color: 0x2c003e,
      attack: 'caster', spells: ['hex_bolt'],
      range: 230, preferRange: 150, attackCooldown: 1.4,
      weight: common, difficulty: 'hard',
    },
    salt_wraith: {
      hpMul: 0.80, speedMul: 1.15, dmgMul: 0.93, radius: 14, color: 0xf5e6c8,
      attack: 'melee',
      weight: common, difficulty: 'hard',
    },
    iron_tick: {
      hpMul: 1.60, speedMul: 1.15, dmgMul: 0.85, radius: 12, color: 0x566573,
      attack: 'melee',
      weight: common, difficulty: 'nightmare',
    },
    glacier_imp: {
      hpMul: 0.80, speedMul: 0.99, dmgMul: 0.85, radius: 14, color: 0x85c1e9,
      attack: 'caster', spells: ['ice_shard'],
      range: 215, preferRange: 140, projectileSpeed: 440, projectileRadius: 7, projectileColor: 0xaed6f1, attackCooldown: 1.5,
      weight: common, difficulty: 'hard',
    },
    thorn_imp: {
      hpMul: 1.60, speedMul: 1.23, dmgMul: 1.01, radius: 12, color: 0x27ae60,
      attack: 'ranged', projectile: 'arrow',
      range: 200, preferRange: 135, projectileSpeed: 340, projectileRadius: 4, projectileColor: 0x82e0aa, attackCooldown: 1.2,
      weight: common, difficulty: 'normal',
    },
    cave_bat_swarm: {
      hpMul: 1.10, speedMul: 1.47, dmgMul: 0.93, radius: 17, color: 0x2c3e50,
      attack: 'melee',
      weight: common, difficulty: 'normal',
    },
    scrap_wolf: {
      hpMul: 0.70, speedMul: 1.15, dmgMul: 1.09, radius: 13, color: 0x7f8c8d,
      attack: 'melee',
      weight: common, difficulty: 'hard',
    },
    coral_snake: {
      hpMul: 0.80, speedMul: 1.47, dmgMul: 1.09, radius: 14, color: 0xe74c3c,
      attack: 'melee',
      weight: common, difficulty: 'hard',
    },
    rune_imp: {
      hpMul: 1.50, speedMul: 1.07, dmgMul: 1.09, radius: 11, color: 0x5b2c6f,
      attack: 'caster', spells: ['arc_lightning'],
      range: 185, preferRange: 125, attackCooldown: 1.3,
      weight: common, difficulty: 'hard',
    },
    peat_slime: {
      hpMul: 0.70, speedMul: 0.91, dmgMul: 1.25, radius: 13, color: 0x4a5c3a,
      attack: 'melee',
      weight: common, difficulty: 'normal',
    },
    wind_razor: {
      hpMul: 0.70, speedMul: 1.47, dmgMul: 1.09, radius: 13, color: 0xaed6f1,
      attack: 'ranged', projectile: 'orb',
      range: 235, preferRange: 160, projectileSpeed: 400, projectileRadius: 5, projectileColor: 0xffffff, attackCooldown: 1.1,
      weight: common, difficulty: 'nightmare',
    },
    blood_leech: {
      hpMul: 0.80, speedMul: 1.39, dmgMul: 0.85, radius: 14, color: 0x922b21,
      attack: 'melee',
      weight: common, difficulty: 'hard',
    },
    frost_archer_novice: {
      hpMul: 1.60, speedMul: 0.91, dmgMul: 0.85, radius: 14, color: 0x5dade2,
      attack: 'ranged', projectile: 'arrow',
      range: 225, preferRange: 155, projectileSpeed: 350, projectileRadius: 4, projectileColor: 0xd6eaf8, attackCooldown: 1.3,
      weight: common, difficulty: 'hard',
    },
    shade_larva: {
      hpMul: 0.80, speedMul: 1.15, dmgMul: 1.01, radius: 14, color: 0x1a0a20,
      attack: 'melee',
      weight: common, difficulty: 'apocalypse',
    },
    pyre_cultist: {
      hpMul: 0.90, speedMul: 0.91, dmgMul: 0.93, radius: 15, color: 0xcb4335,
      attack: 'caster', spells: ['firebolt'],
      range: 220, preferRange: 145, projectileSpeed: 420, projectileRadius: 8, projectileColor: 0xff5533, attackCooldown: 1.45,
      weight: common, difficulty: 'hard',
    },
    quartz_beetle: {
      hpMul: 1.00, speedMul: 0.99, dmgMul: 1.09, radius: 16, color: 0xd5d8dc,
      attack: 'melee',
      weight: common, difficulty: 'hard',
    },

    // Elites (32)
    acid_alchemist: {
      hpMul: 2.01, speedMul: 0.62, dmgMul: 1.58, radius: 18, color: 0x1e8449,
      attack: 'caster', spells: ['acid_bolt', 'poison_cloud', 'firebolt'],
      range: 250, preferRange: 150, projectileSpeed: 430, projectileRadius: 8, projectileColor: 0x88ff44, attackCooldown: 1.15, novaRadius: 100, novaCooldown: 3.9,
      weight: elite, isElite: true, difficulty: 'hard',
    },
    frost_wyvern: {
      hpMul: 1.85, speedMul: 0.97, dmgMul: 1.40, radius: 16, color: 0x85c1e9,
      attack: 'caster', spells: ['frost_breath', 'ice_shard', 'arc_lightning'],
      range: 255, preferRange: 150, projectileSpeed: 450, projectileRadius: 9, projectileColor: 0xaed6f1, attackCooldown: 1.1,
      weight: elite, isElite: true, difficulty: 'nightmare',
    },
    bone_chanter: {
      hpMul: 1.85, speedMul: 0.69, dmgMul: 1.58, radius: 16, color: 0xece5d0,
      attack: 'caster', spells: ['bone_volley', 'skull_wave', 'ice_shard'],
      range: 245, preferRange: 145, projectileSpeed: 340, projectileRadius: 10, projectileColor: 0xd5d0c0, attackCooldown: 1.2, skullCount: 8,
      weight: elite, isElite: true, difficulty: 'nightmare',
    },
    hex_witch: {
      hpMul: 2.57, speedMul: 1.11, dmgMul: 1.70, radius: 23, color: 0x6c3483,
      attack: 'caster', spells: ['hex_bolt', 'arc_lightning', 'acid_bolt'],
      range: 260, preferRange: 155, attackCooldown: 1.1,
      weight: elite, isElite: true, difficulty: 'hard',
    },
    magma_brute: {
      hpMul: 2.73, speedMul: 0.62, dmgMul: 1.46, radius: 15, color: 0xa04000,
      attack: 'caster', spells: ['magma_surge', 'firebreath', 'firebolt'],
      range: 235, preferRange: 140, projectileSpeed: 420, projectileRadius: 9, projectileColor: 0xe67e22, attackCooldown: 1.15, novaRadius: 110, novaCooldown: 4,
      weight: elite, isElite: true, difficulty: 'nightmare',
    },
    storm_centurion: {
      hpMul: 2.09, speedMul: 1.04, dmgMul: 1.52, radius: 19, color: 0x5dade2,
      attack: 'caster', spells: ['electric_bolt', 'electric_storm', 'arc_lightning'],
      range: 250, preferRange: 150, attackCooldown: 1.1, novaRadius: 105, novaCooldown: 3.9,
      weight: elite, isElite: true, difficulty: 'hard',
    },
    obsidian_raptor: {
      hpMul: 2.09, speedMul: 0.76, dmgMul: 1.52, radius: 19, color: 0x1c2833,
      attack: 'melee', attackCooldown: 0.7,
      weight: elite, isElite: true, difficulty: 'nightmare',
    },
    venom_naga: {
      hpMul: 2.65, speedMul: 1.25, dmgMul: 1.70, radius: 14, color: 0x27ae60,
      attack: 'caster', spells: ['acid_bolt', 'poison_cloud', 'ice_shard'],
      range: 240, preferRange: 145, projectileSpeed: 410, projectileRadius: 8, projectileColor: 0x88ff44, attackCooldown: 1.15, novaRadius: 95, novaCooldown: 3.8,
      weight: elite, isElite: true, difficulty: 'hard',
    },
    crystal_guardian: {
      hpMul: 2.17, speedMul: 0.76, dmgMul: 1.40, radius: 20, color: 0xaed6f1,
      attack: 'melee', attackCooldown: 1.25,
      weight: elite, isElite: true, difficulty: 'nightmare',
    },
    shadow_duelist: {
      hpMul: 2.01, speedMul: 1.04, dmgMul: 1.52, radius: 18, color: 0x1c1c28,
      attack: 'melee', attackCooldown: 0.65,
      weight: elite, isElite: true, difficulty: 'apocalypse',
    },
    pyre_drake: {
      hpMul: 2.65, speedMul: 0.83, dmgMul: 1.46, radius: 14, color: 0xcb4335,
      attack: 'caster', spells: ['firebreath', 'magma_surge', 'firebolt'],
      range: 250, preferRange: 150, projectileSpeed: 440, projectileRadius: 9, projectileColor: 0xff5533, attackCooldown: 1.1, novaRadius: 108, novaCooldown: 4.1,
      weight: elite, isElite: true, difficulty: 'nightmare',
    },
    glacier_knight: {
      hpMul: 2.01, speedMul: 1.04, dmgMul: 1.40, radius: 18, color: 0x85c1e9,
      attack: 'melee', attackCooldown: 0.9,
      weight: elite, isElite: true, difficulty: 'hard',
    },
    plague_harpy: {
      hpMul: 1.85, speedMul: 0.83, dmgMul: 1.40, radius: 16, color: 0x196f3d,
      attack: 'caster', spells: ['poison_cloud', 'acid_bolt', 'arc_lightning'],
      range: 245, preferRange: 150, projectileSpeed: 400, projectileRadius: 8, projectileColor: 0x88ff44, attackCooldown: 1.15, novaRadius: 100, novaCooldown: 3.8,
      weight: elite, isElite: true, difficulty: 'hard',
    },
    rune_golem: {
      hpMul: 2.65, speedMul: 0.97, dmgMul: 1.58, radius: 14, color: 0x5b2c6f,
      attack: 'caster', spells: ['hex_bolt', 'arc_lightning', 'flame_nova'],
      range: 230, preferRange: 140, attackCooldown: 1.25, novaRadius: 100, novaCooldown: 4.2,
      weight: elite, isElite: true, difficulty: 'nightmare',
    },
    blood_panther: {
      hpMul: 1.93, speedMul: 0.69, dmgMul: 1.40, radius: 17, color: 0x922b21,
      attack: 'melee', attackCooldown: 0.68,
      weight: elite, isElite: true, difficulty: 'nightmare',
    },
    arcane_archer: {
      hpMul: 1.93, speedMul: 0.62, dmgMul: 1.40, radius: 17, color: 0xaf7ac5,
      attack: 'ranged', projectile: 'orb',
      range: 260, preferRange: 170, projectileSpeed: 410, projectileRadius: 6, projectileColor: 0xd2b4de, attackCooldown: 1,
      weight: elite, isElite: true, difficulty: 'hard',
    },
    furnace_golem: {
      hpMul: 1.93, speedMul: 0.97, dmgMul: 1.58, radius: 17, color: 0xe67e22,
      attack: 'caster', spells: ['magma_surge', 'flame_nova', 'firebolt'],
      range: 220, preferRange: 135, projectileSpeed: 400, projectileRadius: 9, projectileColor: 0xe67e22, attackCooldown: 1.2, novaRadius: 112, novaCooldown: 4,
      weight: elite, isElite: true, difficulty: 'nightmare',
    },
    void_serpent: {
      hpMul: 1.85, speedMul: 1.25, dmgMul: 1.58, radius: 16, color: 0x1a0033,
      attack: 'caster', spells: ['hex_bolt', 'skull_wave', 'ice_shard'],
      range: 245, preferRange: 145, projectileSpeed: 380, projectileRadius: 9, projectileColor: 0x8e44ad, attackCooldown: 1.15, skullCount: 7,
      weight: elite, isElite: true, difficulty: 'apocalypse',
    },
    jade_monk: {
      hpMul: 2.57, speedMul: 1.25, dmgMul: 1.46, radius: 23, color: 0x117a65,
      attack: 'melee', attackCooldown: 0.75,
      weight: elite, isElite: true, difficulty: 'hard',
    },
    thunder_drake: {
      hpMul: 1.93, speedMul: 1.11, dmgMul: 1.52, radius: 17, color: 0x5dade2,
      attack: 'caster', spells: ['electric_storm', 'electric_bolt', 'arc_lightning'],
      range: 255, preferRange: 150, attackCooldown: 1.1, novaRadius: 110, novaCooldown: 3.9,
      weight: elite, isElite: true, difficulty: 'nightmare',
    },
    mirror_knight: {
      hpMul: 1.93, speedMul: 0.62, dmgMul: 1.58, radius: 17, color: 0xd5d8dc,
      attack: 'melee', attackCooldown: 0.85,
      weight: elite, isElite: true, difficulty: 'hard',
    },
    blight_treant: {
      hpMul: 1.93, speedMul: 0.69, dmgMul: 1.40, radius: 17, color: 0x145a32,
      attack: 'caster', spells: ['poison_cloud', 'acid_bolt', 'flame_nova'],
      range: 230, preferRange: 140, projectileSpeed: 390, projectileRadius: 8, projectileColor: 0x88ff44, attackCooldown: 1.2, novaRadius: 105, novaCooldown: 4,
      weight: elite, isElite: true, difficulty: 'hard',
    },
    ash_assassin: {
      hpMul: 1.85, speedMul: 0.62, dmgMul: 1.46, radius: 16, color: 0x6e2c00,
      attack: 'melee', attackCooldown: 0.62,
      weight: elite, isElite: true, difficulty: 'apocalypse',
    },
    sapphire_witch: {
      hpMul: 2.01, speedMul: 1.04, dmgMul: 1.46, radius: 18, color: 0x1a5276,
      attack: 'caster', spells: ['frost_breath', 'ice_shard', 'hex_bolt'],
      range: 265, preferRange: 155, projectileSpeed: 460, projectileRadius: 9, projectileColor: 0x85c1e9, attackCooldown: 1.1,
      weight: elite, isElite: true, difficulty: 'hard',
    },
    iron_hydra: {
      hpMul: 2.65, speedMul: 1.18, dmgMul: 1.40, radius: 14, color: 0x566573,
      attack: 'melee', attackCooldown: 1,
      weight: elite, isElite: true, difficulty: 'nightmare',
    },
    soul_thief: {
      hpMul: 2.65, speedMul: 1.04, dmgMul: 1.58, radius: 14, color: 0x4a235a,
      attack: 'caster', spells: ['bone_volley', 'hex_bolt', 'ice_shard'],
      range: 250, preferRange: 150, projectileSpeed: 360, projectileRadius: 9, projectileColor: 0x8e44ad, attackCooldown: 1.15, skullCount: 7,
      weight: elite, isElite: true, difficulty: 'apocalypse',
    },
    cinder_titan_spawn: {
      hpMul: 2.33, speedMul: 0.76, dmgMul: 1.58, radius: 22, color: 0xcb4335,
      attack: 'caster', spells: ['magma_surge', 'firebreath', 'flame_nova'],
      range: 240, preferRange: 145, projectileSpeed: 430, projectileRadius: 9, projectileColor: 0xff5533, attackCooldown: 1.15, novaRadius: 110, novaCooldown: 4,
      weight: elite, isElite: true, difficulty: 'nightmare',
    },
    aurora_serpent: {
      hpMul: 2.01, speedMul: 0.62, dmgMul: 1.58, radius: 18, color: 0xaf7ac5,
      attack: 'caster', spells: ['arc_lightning', 'ice_shard', 'hex_bolt'],
      range: 255, preferRange: 150, projectileSpeed: 450, projectileRadius: 9, projectileColor: 0xd2b4de, attackCooldown: 1.1,
      weight: elite, isElite: true, difficulty: 'hard',
    },
    grave_sentinel: {
      hpMul: 2.01, speedMul: 1.04, dmgMul: 1.40, radius: 18, color: 0xd5d0c0,
      attack: 'melee', attackCooldown: 1.3,
      weight: elite, isElite: true, difficulty: 'nightmare',
    },
    night_reaver: {
      hpMul: 1.85, speedMul: 0.69, dmgMul: 1.58, radius: 16, color: 0x1a0a20,
      attack: 'melee', attackCooldown: 0.7,
      weight: elite, isElite: true, difficulty: 'apocalypse',
    },
    ember_witch: {
      hpMul: 2.73, speedMul: 0.90, dmgMul: 1.46, radius: 15, color: 0xe67e22,
      attack: 'caster', spells: ['firebreath', 'firebolt', 'magma_surge'],
      range: 250, preferRange: 150, projectileSpeed: 440, projectileRadius: 9, projectileColor: 0xff6622, attackCooldown: 1.1, novaRadius: 105, novaCooldown: 4,
      weight: elite, isElite: true, difficulty: 'hard',
    },
    toxin_archer: {
      hpMul: 1.85, speedMul: 1.11, dmgMul: 1.58, radius: 16, color: 0x1e8449,
      attack: 'ranged', projectile: 'arrow',
      range: 255, preferRange: 165, projectileSpeed: 390, projectileRadius: 5, projectileColor: 0x88ff44, attackCooldown: 1,
      weight: elite, isElite: true, difficulty: 'hard',
    },

    // Bosses (20)
    acid_sovereign: {
      hpMul: 4.80, speedMul: 0.68, dmgMul: 1.65, radius: 46, color: 0x1e8449,
      attack: 'caster', spells: ['plague_burst', 'acid_bolt', 'poison_cloud', 'soul_lance'],
      range: 270, preferRange: 155, projectileSpeed: 420, projectileRadius: 9, projectileColor: 0x88ff44, attackCooldown: 1.15, novaRadius: 125, novaCooldown: 4.5,
      weight: boss, isBoss: true, difficulty: 'nightmare',
    },
    frost_empress: {
      hpMul: 4.70, speedMul: 0.48, dmgMul: 1.60, radius: 45, color: 0x85c1e9,
      attack: 'caster', spells: ['frost_apocalypse', 'frost_breath', 'ice_shard', 'soul_lance'],
      range: 290, preferRange: 165, projectileSpeed: 460, projectileRadius: 9, projectileColor: 0xaed6f1, attackCooldown: 1.15, novaRadius: 135, novaCooldown: 5,
      weight: boss, isBoss: true, difficulty: 'apocalypse',
    },
    bone_overlord: {
      hpMul: 4.70, speedMul: 0.72, dmgMul: 1.85, radius: 45, color: 0xece5d0,
      attack: 'caster', spells: ['death_knell', 'bone_volley', 'skull_wave', 'soul_rend'],
      range: 275, preferRange: 155, projectileSpeed: 340, projectileRadius: 11, projectileColor: 0xd5d0c0, attackCooldown: 1.2, novaRadius: 130, novaCooldown: 5, skullCount: 12,
      weight: boss, isBoss: true, difficulty: 'nightmare',
    },
    hex_archon: {
      hpMul: 4.40, speedMul: 0.56, dmgMul: 1.75, radius: 42, color: 0x6c3483,
      attack: 'caster', spells: ['entropy_pulse', 'hex_bolt', 'void_collapse', 'soul_lance'],
      range: 300, preferRange: 170, attackCooldown: 1.15, novaRadius: 140, novaCooldown: 5,
      weight: boss, isBoss: true, difficulty: 'apocalypse',
    },
    magma_tyrant: {
      hpMul: 4.60, speedMul: 0.76, dmgMul: 1.55, radius: 44, color: 0xa04000,
      attack: 'caster', spells: ['infernal_judgment', 'magma_surge', 'firebreath', 'solar_judgment'],
      range: 280, preferRange: 160, projectileSpeed: 440, projectileRadius: 10, projectileColor: 0xe67e22, attackCooldown: 1.15, novaRadius: 145, novaCooldown: 4.6,
      weight: boss, isBoss: true, difficulty: 'apocalypse',
    },
    storm_colossus: {
      hpMul: 4.80, speedMul: 0.60, dmgMul: 1.70, radius: 46, color: 0x5d6d7e,
      attack: 'caster', spells: ['electric_storm', 'cataclysm_beam', 'electric_bolt', 'solar_judgment'],
      range: 285, preferRange: 160, attackCooldown: 1.15, novaRadius: 140, novaCooldown: 4.5,
      weight: boss, isBoss: true, difficulty: 'nightmare',
    },
    void_matriarch: {
      hpMul: 4.80, speedMul: 0.72, dmgMul: 1.85, radius: 46, color: 0x1a0033,
      attack: 'caster', spells: ['shadow_eclipse', 'entropy_pulse', 'hex_bolt', 'void_collapse'],
      range: 310, preferRange: 175, attackCooldown: 1.15, novaRadius: 150, novaCooldown: 5.2,
      weight: boss, isBoss: true, difficulty: 'apocalypse',
    },
    plague_sovereign: {
      hpMul: 5.00, speedMul: 0.48, dmgMul: 1.70, radius: 48, color: 0x196f3d,
      attack: 'caster', spells: ['plague_burst', 'poison_cloud', 'acid_bolt', 'blood_pact'],
      range: 270, preferRange: 155, projectileSpeed: 400, projectileRadius: 9, projectileColor: 0x88ff44, attackCooldown: 1.2, novaRadius: 130, novaCooldown: 4.6,
      weight: boss, isBoss: true, difficulty: 'nightmare',
    },
    solar_phoenix_lord: {
      hpMul: 5.20, speedMul: 0.60, dmgMul: 1.85, radius: 32, color: 0xff9f1c,
      attack: 'caster', spells: ['solar_judgment', 'infernal_judgment', 'magma_surge', 'firebreath'],
      range: 295, preferRange: 165, projectileSpeed: 460, projectileRadius: 10, projectileColor: 0xff6622, attackCooldown: 1.1, novaRadius: 140, novaCooldown: 4.5,
      weight: boss, isBoss: true, difficulty: 'apocalypse',
    },
    abyss_leviathan: {
      hpMul: 4.90, speedMul: 0.68, dmgMul: 1.60, radius: 47, color: 0x0e2f44,
      attack: 'caster', spells: ['abyss_nova', 'frost_breath', 'ice_shard', 'soul_lance'],
      range: 280, preferRange: 160, projectileSpeed: 430, projectileRadius: 9, projectileColor: 0x5dade2, attackCooldown: 1.2, novaRadius: 135, novaCooldown: 4.8,
      weight: boss, isBoss: true, difficulty: 'nightmare',
    },
    jade_emperor: {
      hpMul: 4.60, speedMul: 0.64, dmgMul: 1.55, radius: 44, color: 0x117a65,
      attack: 'caster', spells: ['soul_lance', 'cataclysm_beam', 'arc_lightning', 'hex_bolt'],
      range: 270, preferRange: 155, attackCooldown: 1.2, novaRadius: 125, novaCooldown: 5,
      weight: boss, isBoss: true, difficulty: 'hard',
    },
    crimson_warlord: {
      hpMul: 4.90, speedMul: 0.76, dmgMul: 1.60, radius: 47, color: 0xc0392b,
      attack: 'caster', spells: ['blood_pact', 'infernal_judgment', 'firebreath', 'magma_surge'],
      range: 275, preferRange: 155, projectileSpeed: 430, projectileRadius: 10, projectileColor: 0xe74c3c, attackCooldown: 1.1, novaRadius: 130, novaCooldown: 4.4,
      weight: boss, isBoss: true, difficulty: 'nightmare',
    },
    necrotic_queen: {
      hpMul: 4.80, speedMul: 0.40, dmgMul: 1.75, radius: 46, color: 0x7d3c98,
      attack: 'caster', spells: ['death_knell', 'bone_volley', 'shadow_eclipse', 'soul_rend'],
      range: 285, preferRange: 160, projectileSpeed: 360, projectileRadius: 11, projectileColor: 0xbb8fce, attackCooldown: 1.2, novaRadius: 140, novaCooldown: 5, skullCount: 12,
      weight: boss, isBoss: true, difficulty: 'apocalypse',
    },
    entropy_dragon: {
      hpMul: 4.80, speedMul: 0.44, dmgMul: 1.80, radius: 46, color: 0x6c3483,
      attack: 'caster', spells: ['entropy_pulse', 'void_collapse', 'hex_bolt', 'cataclysm_beam'],
      range: 310, preferRange: 175, attackCooldown: 1.15, novaRadius: 150, novaCooldown: 5,
      weight: boss, isBoss: true, difficulty: 'apocalypse',
    },
    iron_behemoth: {
      hpMul: 4.70, speedMul: 0.60, dmgMul: 1.60, radius: 45, color: 0x566573,
      attack: 'caster', spells: ['cataclysm_beam', 'electric_storm', 'soul_lance', 'electric_bolt'],
      range: 265, preferRange: 150, attackCooldown: 1.25, novaRadius: 135, novaCooldown: 4.8,
      weight: boss, isBoss: true, difficulty: 'nightmare',
    },
    mire_hydra_king: {
      hpMul: 4.90, speedMul: 0.76, dmgMul: 1.55, radius: 47, color: 0x145a32,
      attack: 'caster', spells: ['plague_burst', 'poison_cloud', 'acid_bolt', 'blood_pact'],
      range: 260, preferRange: 150, projectileSpeed: 400, projectileRadius: 9, projectileColor: 0x88ff44, attackCooldown: 1.15, novaRadius: 125, novaCooldown: 4.4,
      weight: boss, isBoss: true, difficulty: 'hard',
    },
    astral_tyrant: {
      hpMul: 4.70, speedMul: 0.68, dmgMul: 1.65, radius: 45, color: 0xaf7ac5,
      attack: 'caster', spells: ['entropy_pulse', 'soul_lance', 'shadow_eclipse', 'hex_bolt'],
      range: 305, preferRange: 175, attackCooldown: 1.15, novaRadius: 145, novaCooldown: 5.1,
      weight: boss, isBoss: true, difficulty: 'apocalypse',
    },
    forge_emperor: {
      hpMul: 4.70, speedMul: 0.48, dmgMul: 1.85, radius: 45, color: 0xb9770e,
      attack: 'caster', spells: ['solar_judgment', 'magma_surge', 'flame_nova', 'firebolt'],
      range: 280, preferRange: 160, projectileSpeed: 440, projectileRadius: 10, projectileColor: 0xf4d03f, attackCooldown: 1.15, novaRadius: 140, novaCooldown: 4.5,
      weight: boss, isBoss: true, difficulty: 'nightmare',
    },
    shadow_primordial: {
      hpMul: 5.10, speedMul: 0.60, dmgMul: 1.50, radius: 49, color: 0x1a0a20,
      attack: 'caster', spells: ['shadow_eclipse', 'death_knell', 'entropy_pulse', 'bone_volley', 'hex_bolt'],
      range: 320, preferRange: 180, projectileSpeed: 380, projectileRadius: 11, projectileColor: 0x4a0080, attackCooldown: 1.15, novaRadius: 155, novaCooldown: 5, skullCount: 14,
      weight: boss, isBoss: true, difficulty: 'apocalypse',
    },
    tide_kraken_lord: {
      hpMul: 5.00, speedMul: 0.64, dmgMul: 1.55, radius: 48, color: 0x1a5276,
      attack: 'caster', spells: ['abyss_nova', 'frost_apocalypse', 'ice_shard', 'soul_lance'],
      range: 285, preferRange: 160, projectileSpeed: 430, projectileRadius: 9, projectileColor: 0x5dade2, attackCooldown: 1.2, novaRadius: 140, novaCooldown: 4.8,
      weight: boss, isBoss: true, difficulty: 'hard',
    },
  };
}
