/**
 * Catálogo de tipos de monstro (normal / elite / boss).
 * Inspirado em fantasia clássica (D&D / WoW / Tibia) — nomes originais.
 */

export function createMonsterTypeDefs(CONFIG) {
  const common = CONFIG.MONSTER_WEIGHT_COMMON;
  const elite = CONFIG.MONSTER_WEIGHT_ELITE;
  const boss = CONFIG.MONSTER_WEIGHT_BOSS;

  return {
    // ─── Normal ───────────────────────────────────────────────
    imp: {
      hpMul: 1,
      speedMul: 1.2,
      dmgMul: 1,
      radius: 14,
      color: 0xff4422,
      attack: 'ranged',
      projectile: 'fireball',
      range: 190,
      preferRange: 130,
      projectileSpeed: 220,
      projectileRadius: 7,
      projectileColor: 0xff6622,
      attackCooldown: 1.45,
      weight: common,
      difficulty: 'normal',
    },
    slime: {
      hpMul: 1.5,
      speedMul: 0.8,
      dmgMul: 1,
      radius: 16,
      color: 0x44ff66,
      attack: 'melee',
      weight: common,
      difficulty: 'normal',
    },
    wraith: {
      hpMul: 1.3,
      speedMul: 1.1,
      dmgMul: 1,
      radius: 14,
      color: 0x8866ff,
      attack: 'melee',
      weight: common,
      difficulty: 'normal',
    },
    goblin: {
      hpMul: 0.7,
      speedMul: 1.35,
      dmgMul: 0.85,
      radius: 12,
      color: 0xa8c734,
      attack: 'ranged',
      projectile: 'arrow',
      range: 210,
      preferRange: 140,
      projectileSpeed: 340,
      projectileRadius: 4,
      projectileColor: 0xd4c4a0,
      attackCooldown: 1.15,
      weight: common,
      difficulty: 'normal',
    },
    skeleton: {
      hpMul: 1.1,
      speedMul: 1.05,
      dmgMul: 1.15,
      radius: 14,
      color: 0xe8e0d0,
      attack: 'melee',
      attackCooldown: 0.9,
      weight: common,
      difficulty: 'normal',
    },
    skeleton_archer: {
      hpMul: 0.85,
      speedMul: 0.95,
      dmgMul: 1.05,
      radius: 13,
      color: 0xd8d0c0,
      attack: 'ranged',
      projectile: 'arrow',
      range: 230,
      preferRange: 160,
      projectileSpeed: 360,
      projectileRadius: 4,
      projectileColor: 0xc8b8a0,
      attackCooldown: 1.35,
      weight: common,
      difficulty: 'normal',
    },
    wolf: {
      hpMul: 0.95,
      speedMul: 1.45,
      dmgMul: 1.2,
      radius: 14,
      color: 0x8b7355,
      attack: 'melee',
      attackCooldown: 0.75,
      weight: common,
      difficulty: 'normal',
    },
    bat: {
      hpMul: 0.5,
      speedMul: 1.65,
      dmgMul: 0.8,
      radius: 11,
      color: 0x4a3728,
      attack: 'melee',
      attackCooldown: 0.65,
      weight: common,
      difficulty: 'normal',
    },
    elf: {
      hpMul: 0.9,
      speedMul: 1.25,
      dmgMul: 1.1,
      radius: 13,
      color: 0x6bbf59,
      attack: 'ranged',
      projectile: 'arrow',
      range: 240,
      preferRange: 170,
      projectileSpeed: 380,
      projectileRadius: 4,
      projectileColor: 0xc8e6a0,
      attackCooldown: 1.05,
      weight: common,
      difficulty: 'normal',
    },
    cyclops: {
      hpMul: 1.6,
      speedMul: 0.75,
      dmgMul: 1.4,
      radius: 20,
      color: 0xc4a35a,
      attack: 'melee',
      attackCooldown: 1.15,
      weight: common,
      difficulty: 'normal',
    },
    minotaur: {
      hpMul: 1.8,
      speedMul: 0.9,
      dmgMul: 1.45,
      radius: 19,
      color: 0x8b4513,
      attack: 'melee',
      attackCooldown: 1.0,
      weight: common,
      difficulty: 'normal',
    },
    harpy: {
      hpMul: 0.85,
      speedMul: 1.4,
      dmgMul: 1.05,
      radius: 13,
      color: 0xd4a0c8,
      attack: 'ranged',
      projectile: 'arrow',
      range: 200,
      preferRange: 140,
      projectileSpeed: 320,
      projectileRadius: 4,
      projectileColor: 0xf0c0e0,
      attackCooldown: 1.2,
      weight: common,
      difficulty: 'normal',
    },
    kobold: {
      hpMul: 0.65,
      speedMul: 1.3,
      dmgMul: 0.9,
      radius: 11,
      color: 0xc97840,
      attack: 'ranged',
      projectile: 'arrow',
      range: 180,
      preferRange: 120,
      projectileSpeed: 300,
      projectileRadius: 4,
      projectileColor: 0xe8b080,
      attackCooldown: 1.1,
      weight: common,
      difficulty: 'normal',
    },
    zombie: {
      hpMul: 1.4,
      speedMul: 0.7,
      dmgMul: 1.1,
      radius: 15,
      color: 0x6b8f5a,
      attack: 'melee',
      attackCooldown: 1.25,
      weight: common,
      difficulty: 'normal',
    },
    mummy: {
      hpMul: 1.55,
      speedMul: 0.72,
      dmgMul: 1.2,
      radius: 15,
      color: 0xd4c48a,
      attack: 'melee',
      attackCooldown: 1.2,
      weight: common,
      difficulty: 'normal',
    },
    ghoul: {
      hpMul: 1.25,
      speedMul: 1.15,
      dmgMul: 1.25,
      radius: 14,
      color: 0x8fbc8f,
      attack: 'melee',
      attackCooldown: 0.85,
      weight: common,
      difficulty: 'normal',
    },
    ratman: {
      hpMul: 0.8,
      speedMul: 1.35,
      dmgMul: 0.95,
      radius: 12,
      color: 0x7a6a5a,
      attack: 'melee',
      attackCooldown: 0.8,
      weight: common,
      difficulty: 'normal',
    },
    scorpion: {
      hpMul: 1.15,
      speedMul: 1.05,
      dmgMul: 1.3,
      radius: 14,
      color: 0xc45c26,
      attack: 'melee',
      attackCooldown: 0.95,
      weight: common,
      difficulty: 'normal',
    },
    venom_snake: {
      hpMul: 0.75,
      speedMul: 1.25,
      dmgMul: 1.15,
      radius: 12,
      color: 0x3d8b40,
      attack: 'melee',
      attackCooldown: 0.85,
      weight: common,
      difficulty: 'normal',
    },
    cultist: {
      hpMul: 1.0,
      speedMul: 1.0,
      dmgMul: 1.1,
      radius: 14,
      color: 0x5c2d6e,
      attack: 'caster',
      spells: ['firebolt'],
      range: 220,
      preferRange: 140,
      projectileSpeed: 400,
      projectileRadius: 8,
      projectileColor: 0xaa44ff,
      attackCooldown: 1.3,
      weight: common,
      difficulty: 'normal',
    },
    gargoyle: {
      hpMul: 1.7,
      speedMul: 0.85,
      dmgMul: 1.35,
      radius: 17,
      color: 0x6e6e78,
      attack: 'melee',
      attackCooldown: 1.05,
      weight: common,
      difficulty: 'normal',
    },
    pixie: {
      hpMul: 0.55,
      speedMul: 1.55,
      dmgMul: 0.85,
      radius: 10,
      color: 0xff88cc,
      attack: 'ranged',
      projectile: 'arrow',
      range: 190,
      preferRange: 130,
      projectileSpeed: 360,
      projectileRadius: 4,
      projectileColor: 0xffaadd,
      attackCooldown: 1.0,
      weight: common,
      difficulty: 'normal',
    },
    dwarf_guard: {
      hpMul: 1.45,
      speedMul: 0.8,
      dmgMul: 1.35,
      radius: 14,
      color: 0xb87333,
      attack: 'melee',
      attackCooldown: 0.95,
      weight: common,
      difficulty: 'normal',
    },
    bandit: {
      hpMul: 1.0,
      speedMul: 1.2,
      dmgMul: 1.1,
      radius: 13,
      color: 0x8b5a2b,
      attack: 'ranged',
      projectile: 'arrow',
      range: 200,
      preferRange: 135,
      projectileSpeed: 330,
      projectileRadius: 4,
      projectileColor: 0xd2b48c,
      attackCooldown: 1.15,
      weight: common,
      difficulty: 'normal',
    },
    pirate: {
      hpMul: 1.2,
      speedMul: 1.1,
      dmgMul: 1.2,
      radius: 14,
      color: 0x2f4f6f,
      attack: 'melee',
      attackCooldown: 0.9,
      weight: common,
      difficulty: 'normal',
    },
    giant_toad: {
      hpMul: 1.65,
      speedMul: 0.7,
      dmgMul: 1.25,
      radius: 18,
      color: 0x4a7c59,
      attack: 'melee',
      attackCooldown: 1.2,
      weight: common,
      difficulty: 'normal',
    },
    wasp: {
      hpMul: 0.6,
      speedMul: 1.6,
      dmgMul: 0.9,
      radius: 10,
      color: 0xf0c040,
      attack: 'melee',
      attackCooldown: 0.7,
      weight: common,
      difficulty: 'normal',
    },
    crab: {
      hpMul: 1.5,
      speedMul: 0.75,
      dmgMul: 1.3,
      radius: 16,
      color: 0xd35400,
      attack: 'melee',
      attackCooldown: 1.1,
      weight: common,
      difficulty: 'normal',
    },
    yeti_cub: {
      hpMul: 1.35,
      speedMul: 0.95,
      dmgMul: 1.2,
      radius: 15,
      color: 0xe8eef5,
      attack: 'melee',
      attackCooldown: 1.0,
      weight: common,
      difficulty: 'normal',
    },
    shadow_wolf: {
      hpMul: 1.05,
      speedMul: 1.5,
      dmgMul: 1.25,
      radius: 14,
      color: 0x2c2c3a,
      attack: 'melee',
      attackCooldown: 0.7,
      weight: common,
      difficulty: 'normal',
    },
    cave_troll: {
      hpMul: 2.0,
      speedMul: 0.65,
      dmgMul: 1.5,
      radius: 22,
      color: 0x5a6e4a,
      attack: 'melee',
      attackCooldown: 1.3,
      weight: common,
      difficulty: 'normal',
    },
    swamp_slug: {
      hpMul: 1.8,
      speedMul: 0.55,
      dmgMul: 1.15,
      radius: 17,
      color: 0x556b2f,
      attack: 'melee',
      attackCooldown: 1.35,
      weight: common,
      difficulty: 'normal',
    },
    desert_scavenger: {
      hpMul: 0.9,
      speedMul: 1.3,
      dmgMul: 1.0,
      radius: 13,
      color: 0xc2a05a,
      attack: 'ranged',
      projectile: 'arrow',
      range: 195,
      preferRange: 130,
      projectileSpeed: 310,
      projectileRadius: 4,
      projectileColor: 0xe8d090,
      attackCooldown: 1.2,
      weight: common,
      difficulty: 'normal',
    },
    gnoll: {
      hpMul: 1.15,
      speedMul: 1.15,
      dmgMul: 1.2,
      radius: 15,
      color: 0xb8860b,
      attack: 'melee',
      attackCooldown: 0.9,
      weight: common,
      difficulty: 'normal',
    },
    ice_imp: {
      hpMul: 0.95,
      speedMul: 1.15,
      dmgMul: 1.05,
      radius: 13,
      color: 0x7ec8e3,
      attack: 'caster',
      spells: ['ice_shard'],
      range: 210,
      preferRange: 140,
      projectileSpeed: 420,
      projectileRadius: 8,
      projectileColor: 0x66ccff,
      attackCooldown: 1.35,
      weight: common,
      difficulty: 'normal',
    },

    // ─── Elite (mais forte) ───────────────────────────────────
    orc: {
      hpMul: 2.2,
      speedMul: 0.65,
      dmgMul: 1.6,
      radius: 20,
      color: 0x3d8b4a,
      attack: 'ranged',
      projectile: 'arrow',
      range: 175,
      preferRange: 110,
      projectileSpeed: 260,
      projectileRadius: 5,
      projectileColor: 0xb8956a,
      attackCooldown: 1.7,
      weight: elite,
      isElite: true,
      difficulty: 'hard',
    },
    giant_spider: {
      hpMul: 1.7,
      speedMul: 0.85,
      dmgMul: 1.35,
      radius: 18,
      color: 0x2d1b2e,
      attack: 'melee',
      attackCooldown: 1.1,
      weight: elite,
      isElite: true,
      difficulty: 'hard',
    },
    fire_elemental: {
      hpMul: 1.8,
      speedMul: 1.1,
      dmgMul: 1.3,
      radius: 16,
      color: 0xff6622,
      attack: 'caster',
      spells: ['firebreath', 'firebolt', 'flame_nova'],
      range: 250,
      preferRange: 145,
      projectileSpeed: 440,
      projectileRadius: 9,
      projectileColor: 0xff5533,
      attackCooldown: 1.15,
      novaRadius: 105,
      novaCooldown: 4.0,
      weight: elite,
      isElite: true,
      difficulty: 'hard',
    },
    bruxo: {
      hpMul: 1.9,
      speedMul: 1.05,
      dmgMul: 1.25,
      radius: 15,
      color: 0xff5522,
      attack: 'caster',
      spells: ['firebreath', 'firebolt'],
      range: 260,
      preferRange: 150,
      projectileSpeed: 450,
      projectileRadius: 9,
      projectileColor: 0xff5533,
      attackCooldown: 1.2,
      fireTrail: true,
      fireTrailInterval: 0.32,
      fireTrailRadius: 34,
      fireTrailLife: 2.6,
      fireTrailBurnDamage: 2,
      fireTrailBurnTick: 1,
      fireTrailBurnDuration: 3,
      weight: elite,
      isElite: true,
      difficulty: 'hard',
    },
    ancient_scarab: {
      hpMul: 2.4,
      speedMul: 0.8,
      dmgMul: 1.55,
      radius: 18,
      color: 0x1a5c3a,
      attack: 'melee',
      attackCooldown: 1.05,
      weight: elite,
      isElite: true,
      difficulty: 'hard',
    },
    death_knight: {
      hpMul: 2.6,
      speedMul: 0.85,
      dmgMul: 1.7,
      radius: 18,
      color: 0x3a3a5c,
      attack: 'melee',
      attackCooldown: 0.95,
      weight: elite,
      isElite: true,
      difficulty: 'nightmare',
    },
    frost_mage: {
      hpMul: 1.9,
      speedMul: 0.9,
      dmgMul: 1.4,
      radius: 15,
      color: 0x5dade2,
      attack: 'caster',
      spells: ['ice_shard'],
      range: 270,
      preferRange: 155,
      projectileSpeed: 460,
      projectileRadius: 9,
      projectileColor: 0x66ccff,
      attackCooldown: 1.15,
      weight: elite,
      isElite: true,
      difficulty: 'hard',
    },
    venom_hydra: {
      hpMul: 2.8,
      speedMul: 0.7,
      dmgMul: 1.65,
      radius: 22,
      color: 0x27ae60,
      attack: 'caster',
      spells: ['poison_cloud', 'firebolt'],
      range: 240,
      preferRange: 140,
      projectileSpeed: 380,
      projectileRadius: 9,
      projectileColor: 0x88ff44,
      attackCooldown: 1.25,
      novaRadius: 100,
      novaCooldown: 4.2,
      weight: elite,
      isElite: true,
      difficulty: 'nightmare',
    },
    stone_golem: {
      hpMul: 3.2,
      speedMul: 0.5,
      dmgMul: 1.8,
      radius: 24,
      color: 0x7f8c8d,
      attack: 'melee',
      attackCooldown: 1.4,
      weight: elite,
      isElite: true,
      difficulty: 'hard',
    },
    blood_succubus: {
      hpMul: 2.0,
      speedMul: 1.2,
      dmgMul: 1.5,
      radius: 15,
      color: 0xc0392b,
      attack: 'caster',
      spells: ['arc_lightning', 'firebolt'],
      range: 230,
      preferRange: 140,
      projectileSpeed: 420,
      projectileRadius: 8,
      projectileColor: 0xff4466,
      attackCooldown: 1.1,
      weight: elite,
      isElite: true,
      difficulty: 'nightmare',
    },
    nightmare_steed: {
      hpMul: 2.2,
      speedMul: 1.55,
      dmgMul: 1.55,
      radius: 17,
      color: 0x1a0a20,
      attack: 'melee',
      attackCooldown: 0.75,
      weight: elite,
      isElite: true,
      difficulty: 'hard',
    },
    bone_whelp: {
      hpMul: 2.1,
      speedMul: 1.0,
      dmgMul: 1.45,
      radius: 16,
      color: 0xd5d0c0,
      attack: 'caster',
      spells: ['firebolt', 'skull_wave'],
      range: 240,
      preferRange: 145,
      projectileSpeed: 400,
      projectileRadius: 9,
      projectileColor: 0xe8e0d0,
      attackCooldown: 1.2,
      skullCount: 6,
      weight: elite,
      isElite: true,
      difficulty: 'nightmare',
    },
    abyss_watcher: {
      hpMul: 2.3,
      speedMul: 0.95,
      dmgMul: 1.5,
      radius: 17,
      color: 0x4a0080,
      attack: 'caster',
      spells: ['arc_lightning', 'electric_bolt'],
      range: 250,
      preferRange: 150,
      attackCooldown: 1.15,
      weight: elite,
      isElite: true,
      difficulty: 'nightmare',
    },
    crystal_elemental: {
      hpMul: 2.5,
      speedMul: 0.75,
      dmgMul: 1.55,
      radius: 18,
      color: 0xaed6f1,
      attack: 'caster',
      spells: ['ice_shard', 'arc_lightning'],
      range: 260,
      preferRange: 150,
      projectileSpeed: 450,
      projectileRadius: 9,
      projectileColor: 0xd6eaf8,
      attackCooldown: 1.2,
      weight: elite,
      isElite: true,
      difficulty: 'hard',
    },
    plague_doctor: {
      hpMul: 2.0,
      speedMul: 0.95,
      dmgMul: 1.35,
      radius: 15,
      color: 0x2c3e2d,
      attack: 'caster',
      spells: ['poison_cloud', 'ice_shard'],
      range: 230,
      preferRange: 140,
      projectileSpeed: 400,
      projectileRadius: 8,
      projectileColor: 0x88ff44,
      attackCooldown: 1.25,
      novaRadius: 95,
      novaCooldown: 3.8,
      weight: elite,
      isElite: true,
      difficulty: 'hard',
    },
    war_troll: {
      hpMul: 3.0,
      speedMul: 0.6,
      dmgMul: 1.9,
      radius: 24,
      color: 0x4a6741,
      attack: 'melee',
      attackCooldown: 1.25,
      weight: elite,
      isElite: true,
      difficulty: 'nightmare',
    },
    shadow_assassin: {
      hpMul: 1.7,
      speedMul: 1.6,
      dmgMul: 1.7,
      radius: 13,
      color: 0x1c1c28,
      attack: 'melee',
      attackCooldown: 0.65,
      weight: elite,
      isElite: true,
      difficulty: 'nightmare',
    },
    storm_elemental: {
      hpMul: 2.2,
      speedMul: 1.1,
      dmgMul: 1.5,
      radius: 17,
      color: 0x5dade2,
      attack: 'caster',
      spells: ['electric_bolt', 'arc_lightning'],
      range: 260,
      preferRange: 150,
      attackCooldown: 1.1,
      weight: elite,
      isElite: true,
      difficulty: 'hard',
    },
    magma_golem: {
      hpMul: 3.0,
      speedMul: 0.55,
      dmgMul: 1.85,
      radius: 23,
      color: 0xe67e22,
      attack: 'caster',
      spells: ['firebreath', 'flame_nova'],
      range: 220,
      preferRange: 130,
      attackCooldown: 1.2,
      novaRadius: 110,
      novaCooldown: 4.0,
      weight: elite,
      isElite: true,
      difficulty: 'nightmare',
    },
    forest_guardian: {
      hpMul: 2.7,
      speedMul: 0.7,
      dmgMul: 1.6,
      radius: 22,
      color: 0x1e8449,
      attack: 'melee',
      attackCooldown: 1.15,
      weight: elite,
      isElite: true,
      difficulty: 'hard',
    },
    void_stalker: {
      hpMul: 2.1,
      speedMul: 1.35,
      dmgMul: 1.6,
      radius: 15,
      color: 0x2c003e,
      attack: 'caster',
      spells: ['skull_wave', 'arc_lightning'],
      range: 230,
      preferRange: 140,
      projectileSpeed: 320,
      projectileRadius: 10,
      projectileColor: 0x4a0080,
      attackCooldown: 1.3,
      skullCount: 7,
      weight: elite,
      isElite: true,
      difficulty: 'apocalypse',
    },
    ice_wyrm: {
      hpMul: 2.5,
      speedMul: 0.85,
      dmgMul: 1.55,
      radius: 20,
      color: 0xaed6f1,
      attack: 'caster',
      spells: ['ice_shard', 'firebreath'],
      range: 250,
      preferRange: 150,
      projectileSpeed: 440,
      projectileRadius: 9,
      projectileColor: 0x66ccff,
      attackCooldown: 1.15,
      weight: elite,
      isElite: true,
      difficulty: 'nightmare',
    },
    necromancer: {
      hpMul: 2.0,
      speedMul: 0.9,
      dmgMul: 1.4,
      radius: 15,
      color: 0x4a235a,
      attack: 'caster',
      spells: ['skull_wave', 'ice_shard'],
      range: 250,
      preferRange: 150,
      projectileSpeed: 420,
      projectileRadius: 9,
      projectileColor: 0x6c3483,
      attackCooldown: 1.25,
      skullCount: 8,
      weight: elite,
      isElite: true,
      difficulty: 'nightmare',
    },

    // ─── Boss ─────────────────────────────────────────────────
    beholder: {
      hpMul: 2.4,
      speedMul: 0.55,
      dmgMul: 1.25,
      radius: 30,
      color: 0x9b59b6,
      attack: 'caster',
      spells: ['arc_lightning', 'void_collapse'],
      range: 170,
      preferRange: 130,
      attackCooldown: 1.35,
      novaRadius: 120,
      novaCooldown: 5.5,
      weight: boss,
      isBoss: true,
      difficulty: 'hard',
    },
    dragon: {
      hpMul: 3.8,
      speedMul: 0.5,
      dmgMul: 1.55,
      radius: 42,
      color: 0xe74c3c,
      attack: 'caster',
      spells: ['firebreath', 'firebolt', 'flame_nova', 'infernal_judgment'],
      range: 300,
      preferRange: 170,
      projectileSpeed: 480,
      projectileRadius: 10,
      projectileColor: 0xff5533,
      attackCooldown: 1.1,
      novaRadius: 120,
      novaCooldown: 4.2,
      weight: boss,
      isBoss: true,
      difficulty: 'nightmare',
    },
    lich: {
      hpMul: 2.1,
      speedMul: 0.6,
      dmgMul: 1.15,
      radius: 24,
      color: 0x66ccff,
      attack: 'caster',
      spells: ['ice_shard', 'death_knell', 'frost_apocalypse'],
      range: 280,
      preferRange: 160,
      projectileSpeed: 460,
      projectileRadius: 9,
      projectileColor: 0x66ccff,
      attackCooldown: 1.25,
      novaRadius: 130,
      novaCooldown: 5.0,
      weight: boss,
      isBoss: true,
      difficulty: 'hard',
    },
    demon: {
      hpMul: 2.2,
      speedMul: 0.85,
      dmgMul: 1.4,
      radius: 42,
      color: 0x8b1a2b,
      attack: 'caster',
      spells: ['electric_bolt', 'electric_storm', 'infernal_judgment'],
      range: 260,
      preferRange: 150,
      attackCooldown: 1.2,
      novaRadius: 130,
      novaCooldown: 4.5,
      weight: boss,
      isBoss: true,
      difficulty: 'nightmare',
    },
    grim_reaper: {
      hpMul: 2.6,
      speedMul: 0.7,
      dmgMul: 1.35,
      radius: 27,
      color: 0x2a0044,
      attack: 'caster',
      spells: ['skull_wave', 'soul_rend', 'death_knell'],
      range: 220,
      preferRange: 140,
      projectileSpeed: 300,
      projectileRadius: 11,
      projectileColor: 0x4a0080,
      attackCooldown: 2.4,
      skullCount: 10,
      novaRadius: 110,
      novaCooldown: 5.2,
      weight: boss,
      isBoss: true,
      difficulty: 'apocalypse',
    },
    frost_dragon: {
      hpMul: 4.0,
      speedMul: 0.48,
      dmgMul: 1.6,
      radius: 40,
      color: 0x5dade2,
      attack: 'caster',
      spells: ['ice_shard', 'frost_apocalypse', 'cataclysm_beam'],
      range: 300,
      preferRange: 170,
      projectileSpeed: 470,
      projectileRadius: 10,
      projectileColor: 0xaed6f1,
      attackCooldown: 1.15,
      novaRadius: 135,
      novaCooldown: 4.8,
      weight: boss,
      isBoss: true,
      difficulty: 'nightmare',
    },
    bone_dragon: {
      hpMul: 3.6,
      speedMul: 0.52,
      dmgMul: 1.5,
      radius: 38,
      color: 0xece5d0,
      attack: 'caster',
      spells: ['skull_wave', 'soul_rend', 'abyss_nova'],
      range: 280,
      preferRange: 160,
      projectileSpeed: 340,
      projectileRadius: 11,
      projectileColor: 0xd5d0c0,
      attackCooldown: 1.3,
      skullCount: 12,
      novaRadius: 125,
      novaCooldown: 5.0,
      weight: boss,
      isBoss: true,
      difficulty: 'apocalypse',
    },
    kraken: {
      hpMul: 4.2,
      speedMul: 0.45,
      dmgMul: 1.7,
      radius: 44,
      color: 0x1a5276,
      attack: 'caster',
      spells: ['void_collapse', 'abyss_nova', 'electric_storm'],
      range: 260,
      preferRange: 150,
      attackCooldown: 1.25,
      novaRadius: 140,
      novaCooldown: 4.6,
      weight: boss,
      isBoss: true,
      difficulty: 'nightmare',
    },
    hydra_boss: {
      hpMul: 4.5,
      speedMul: 0.55,
      dmgMul: 1.65,
      radius: 40,
      color: 0x196f3d,
      attack: 'caster',
      spells: ['plague_burst', 'poison_cloud', 'firebreath'],
      range: 250,
      preferRange: 145,
      attackCooldown: 1.2,
      novaRadius: 120,
      novaCooldown: 4.4,
      weight: boss,
      isBoss: true,
      difficulty: 'hard',
    },
    medusa: {
      hpMul: 3.0,
      speedMul: 0.75,
      dmgMul: 1.45,
      radius: 28,
      color: 0x58d68d,
      attack: 'caster',
      spells: ['cataclysm_beam', 'poison_cloud', 'ice_shard'],
      range: 270,
      preferRange: 155,
      projectileSpeed: 450,
      projectileRadius: 9,
      projectileColor: 0x82e0aa,
      attackCooldown: 1.2,
      novaRadius: 115,
      novaCooldown: 5.0,
      weight: boss,
      isBoss: true,
      difficulty: 'hard',
    },
    phoenix: {
      hpMul: 3.4,
      speedMul: 1.05,
      dmgMul: 1.55,
      radius: 32,
      color: 0xff6b35,
      attack: 'caster',
      spells: ['infernal_judgment', 'flame_nova', 'firebreath'],
      range: 280,
      preferRange: 160,
      attackCooldown: 1.1,
      novaRadius: 125,
      novaCooldown: 4.0,
      weight: boss,
      isBoss: true,
      difficulty: 'nightmare',
    },
    titan: {
      hpMul: 5.0,
      speedMul: 0.4,
      dmgMul: 1.9,
      radius: 48,
      color: 0xf5cba7,
      attack: 'caster',
      spells: ['abyss_nova', 'cataclysm_beam', 'electric_storm'],
      range: 290,
      preferRange: 160,
      attackCooldown: 1.35,
      novaRadius: 150,
      novaCooldown: 5.5,
      weight: boss,
      isBoss: true,
      difficulty: 'apocalypse',
    },
    void_lord: {
      hpMul: 3.8,
      speedMul: 0.65,
      dmgMul: 1.6,
      radius: 36,
      color: 0x1a0033,
      attack: 'caster',
      spells: ['void_collapse', 'shadow_eclipse', 'soul_rend'],
      range: 270,
      preferRange: 155,
      attackCooldown: 1.2,
      novaRadius: 140,
      novaCooldown: 5.2,
      weight: boss,
      isBoss: true,
      difficulty: 'apocalypse',
    },
    ancient_treant: {
      hpMul: 4.4,
      speedMul: 0.42,
      dmgMul: 1.55,
      radius: 42,
      color: 0x145a32,
      attack: 'caster',
      spells: ['plague_burst', 'abyss_nova', 'flame_nova'],
      range: 240,
      preferRange: 140,
      attackCooldown: 1.3,
      novaRadius: 130,
      novaCooldown: 4.8,
      weight: boss,
      isBoss: true,
      difficulty: 'hard',
    },
    sand_worm: {
      hpMul: 4.0,
      speedMul: 0.6,
      dmgMul: 1.7,
      radius: 40,
      color: 0xd4a017,
      attack: 'caster',
      spells: ['void_collapse', 'cataclysm_beam', 'flame_nova'],
      range: 250,
      preferRange: 140,
      attackCooldown: 1.25,
      novaRadius: 125,
      novaCooldown: 4.5,
      weight: boss,
      isBoss: true,
      difficulty: 'nightmare',
    },
    flame_lord: {
      hpMul: 3.9,
      speedMul: 0.7,
      dmgMul: 1.75,
      radius: 38,
      color: 0xcb4335,
      attack: 'caster',
      spells: ['infernal_judgment', 'firebreath', 'flame_nova', 'blood_pact'],
      range: 280,
      preferRange: 160,
      attackCooldown: 1.15,
      novaRadius: 130,
      novaCooldown: 4.2,
      weight: boss,
      isBoss: true,
      difficulty: 'apocalypse',
    },
    frost_lich: {
      hpMul: 3.2,
      speedMul: 0.58,
      dmgMul: 1.4,
      radius: 26,
      color: 0x85c1e9,
      attack: 'caster',
      spells: ['frost_apocalypse', 'death_knell', 'ice_shard'],
      range: 290,
      preferRange: 165,
      projectileSpeed: 470,
      projectileRadius: 9,
      projectileColor: 0xd6eaf8,
      attackCooldown: 1.2,
      novaRadius: 135,
      novaCooldown: 5.0,
      weight: boss,
      isBoss: true,
      difficulty: 'nightmare',
    },
    plague_queen: {
      hpMul: 3.5,
      speedMul: 0.8,
      dmgMul: 1.5,
      radius: 30,
      color: 0x7d3c98,
      attack: 'caster',
      spells: ['plague_burst', 'poison_cloud', 'blood_pact'],
      range: 260,
      preferRange: 150,
      attackCooldown: 1.2,
      novaRadius: 120,
      novaCooldown: 4.3,
      weight: boss,
      isBoss: true,
      difficulty: 'nightmare',
    },
    storm_giant: {
      hpMul: 4.6,
      speedMul: 0.5,
      dmgMul: 1.8,
      radius: 46,
      color: 0x5d6d7e,
      attack: 'caster',
      spells: ['electric_storm', 'electric_bolt', 'cataclysm_beam'],
      range: 300,
      preferRange: 170,
      attackCooldown: 1.25,
      novaRadius: 145,
      novaCooldown: 4.6,
      weight: boss,
      isBoss: true,
      difficulty: 'apocalypse',
    },
    cerberus: {
      hpMul: 3.7,
      speedMul: 1.1,
      dmgMul: 1.7,
      radius: 34,
      color: 0x641e16,
      attack: 'caster',
      spells: ['infernal_judgment', 'firebreath', 'soul_rend'],
      range: 240,
      preferRange: 130,
      attackCooldown: 1.05,
      novaRadius: 110,
      novaCooldown: 4.5,
      weight: boss,
      isBoss: true,
      difficulty: 'hard',
    },
    basilisk: {
      hpMul: 3.3,
      speedMul: 0.7,
      dmgMul: 1.55,
      radius: 32,
      color: 0x117a65,
      attack: 'caster',
      spells: ['cataclysm_beam', 'plague_burst', 'poison_cloud'],
      range: 250,
      preferRange: 145,
      attackCooldown: 1.2,
      novaRadius: 115,
      novaCooldown: 4.8,
      weight: boss,
      isBoss: true,
      difficulty: 'hard',
    },
    djinn: {
      hpMul: 3.1,
      speedMul: 1.0,
      dmgMul: 1.5,
      radius: 28,
      color: 0xf4d03f,
      attack: 'caster',
      spells: ['shadow_eclipse', 'electric_bolt', 'void_collapse'],
      range: 270,
      preferRange: 155,
      attackCooldown: 1.15,
      novaRadius: 130,
      novaCooldown: 5.0,
      weight: boss,
      isBoss: true,
      difficulty: 'nightmare',
    },
    archdemon: {
      hpMul: 4.3,
      speedMul: 0.75,
      dmgMul: 1.85,
      radius: 40,
      color: 0x7b241c,
      attack: 'caster',
      spells: ['blood_pact', 'infernal_judgment', 'shadow_eclipse', 'electric_storm'],
      range: 280,
      preferRange: 160,
      attackCooldown: 1.15,
      novaRadius: 140,
      novaCooldown: 4.4,
      weight: boss,
      isBoss: true,
      difficulty: 'apocalypse',
    },
    world_serpent: {
      hpMul: 5.2,
      speedMul: 0.5,
      dmgMul: 1.95,
      radius: 50,
      color: 0x0e6655,
      attack: 'caster',
      spells: ['abyss_nova', 'void_collapse', 'plague_burst', 'death_knell'],
      range: 310,
      preferRange: 175,
      attackCooldown: 1.3,
      novaRadius: 155,
      novaCooldown: 5.5,
      weight: boss,
      isBoss: true,
      difficulty: 'apocalypse',
    },
  };
}
