/** Habitats RPG: em quais terrenos cada monstro pode spawnar. */
export const MONSTER_FLOORS = {
  imp: ['volcano', 'hell', 'lava_field', 'dungeon', 'blood'],
  slime: ['sewer', 'dungeon', 'cave', 'swamp', 'mushroom', 'marsh'],
  wraith: ['graveyard', 'shadow', 'ruins', 'ice', 'blood', 'glacier', 'battlefield', 'catacomb'],
  goblin: ['dirt', 'grass', 'cave', 'dungeon', 'mountain', 'wood', 'canyon', 'library'],
  skeleton: ['graveyard', 'dungeon', 'ruins', 'temple', 'wood', 'blood', 'sandstone', 'battlefield', 'library', 'catacomb'],
  skeleton_archer: ['graveyard', 'dungeon', 'ruins', 'battlefield', 'catacomb'],
  wolf: ['grass', 'meadow', 'tundra', 'snow', 'mountain', 'canyon', 'garden'],
  bat: ['cave', 'dungeon', 'graveyard', 'shadow', 'wood', 'blood', 'library', 'catacomb'],
  elf: ['grass', 'enchanted', 'jungle', 'meadow', 'garden', 'bramble'],
  cyclops: ['mountain', 'cave', 'ruins', 'canyon', 'battlefield'],
  minotaur: ['dungeon', 'ruins', 'temple', 'sandstone', 'battlefield'],
  harpy: ['sky', 'mountain', 'ruins', 'canyon', 'aurora', 'storm', 'battlefield'],
  kobold: ['dungeon', 'wood', 'ruins', 'temple', 'dirt', 'sandstone', 'battlefield', 'library'],
  zombie: ['graveyard', 'swamp', 'dungeon', 'sewer', 'blood', 'marsh', 'catacomb'],
  mummy: ['desert', 'temple', 'ruins', 'graveyard', 'oasis', 'sandstone', 'battlefield', 'catacomb', 'saltflat'],
  ghoul: ['graveyard', 'dungeon', 'sewer', 'ruins', 'blood', 'battlefield', 'catacomb'],
  ratman: ['dungeon', 'wood', 'ruins', 'temple', 'dirt', 'blood', 'sandstone', 'battlefield', 'library'],
  scorpion: ['desert', 'beach', 'ashland', 'oasis', 'obsidian', 'saltflat'],
  venom_snake: ['swamp', 'sewer', 'mushroom', 'jungle', 'marsh', 'bramble'],
  cultist: ['dungeon', 'ruins', 'temple', 'shadow', 'blood', 'wood', 'sandstone', 'battlefield', 'library'],
  gargoyle: ['ruins', 'temple', 'dungeon', 'sky', 'aurora', 'sandstone', 'storm', 'battlefield'],
  pixie: ['enchanted', 'grass', 'meadow', 'mushroom', 'garden'],
  dwarf_guard: ['dungeon', 'wood', 'ruins', 'temple', 'dirt', 'sandstone', 'battlefield', 'library'],
  bandit: ['dungeon', 'wood', 'ruins', 'temple', 'dirt', 'desert', 'blood', 'oasis', 'sandstone', 'battlefield', 'library', 'saltflat'],
  pirate: ['sea', 'beach', 'wood', 'coral', 'library', 'abyss'],
  giant_toad: ['swamp', 'sewer', 'mushroom', 'jungle', 'mountain', 'canyon', 'marsh', 'bramble'],
  wasp: ['grass', 'jungle', 'meadow', 'enchanted', 'mushroom', 'beach', 'garden', 'bramble'],
  crab: ['beach', 'sea', 'coral', 'abyss'],
  yeti_cub: ['snow', 'tundra', 'mountain', 'ice', 'glacier', 'canyon'],
  shadow_wolf: ['shadow', 'graveyard', 'ruins', 'crystal', 'dungeon', 'battlefield', 'catacomb'],
  cave_troll: ['cave', 'mountain', 'dungeon', 'ruins', 'tundra', 'canyon', 'battlefield'],
  swamp_slug: ['swamp', 'sewer', 'mushroom', 'jungle', 'marsh', 'bramble'],
  desert_scavenger: ['desert', 'beach', 'ashland', 'cave', 'mountain', 'oasis', 'canyon', 'obsidian', 'saltflat'],
  gnoll: ['dirt', 'grass', 'meadow', 'ruins', 'dungeon', 'desert', 'oasis', 'garden', 'battlefield', 'saltflat'],
  ice_imp: ['ice', 'snow', 'tundra', 'mountain', 'hell', 'glacier', 'canyon'],
  orc: ['dirt', 'grass', 'mountain', 'ashland', 'meadow', 'desert', 'blood', 'oasis', 'canyon', 'obsidian', 'garden', 'saltflat'],
  giant_spider: ['cave', 'dungeon', 'jungle', 'mushroom', 'wood', 'library', 'bramble'],
  fire_elemental: ['volcano', 'hell', 'lava_field', 'ashland', 'obsidian'],
  bruxo: ['hell', 'volcano', 'ruins', 'shadow', 'blood', 'battlefield'],
  ancient_scarab: ['desert', 'beach', 'ashland', 'oasis', 'obsidian', 'saltflat'],
  death_knight: ['graveyard', 'ruins', 'dungeon', 'temple', 'shadow', 'blood', 'sandstone', 'battlefield', 'catacomb'],
  frost_mage: ['ice', 'snow', 'tundra', 'mountain', 'dungeon', 'glacier', 'canyon'],
  venom_hydra: ['swamp', 'sewer', 'mushroom', 'jungle', 'sea', 'coral', 'marsh', 'abyss', 'bramble'],
  stone_golem: ['cave', 'mountain', 'dungeon', 'ruins', 'canyon', 'battlefield'],
  blood_succubus: ['blood', 'hell', 'graveyard', 'ruins', 'battlefield', 'catacomb'],
  nightmare_steed: ['shadow', 'graveyard', 'ruins', 'crystal', 'dungeon', 'battlefield', 'catacomb'],
  bone_whelp: ['graveyard', 'ruins', 'dungeon', 'temple', 'shadow', 'sandstone', 'battlefield', 'catacomb'],
  abyss_watcher: ['shadow', 'graveyard', 'ruins', 'crystal', 'dungeon', 'coral', 'battlefield', 'catacomb', 'abyss'],
  crystal_elemental: ['crystal', 'cave', 'enchanted', 'temple', 'coral', 'sandstone', 'abyss'],
  plague_doctor: ['swamp', 'sewer', 'mushroom', 'jungle', 'wood', 'blood', 'marsh', 'library', 'bramble'],
  war_troll: ['mountain', 'tundra', 'cave', 'meadow', 'canyon', 'garden'],
  shadow_assassin: ['shadow', 'graveyard', 'ruins', 'crystal', 'dungeon', 'wood', 'blood', 'battlefield', 'library', 'catacomb'],
  storm_elemental: ['sky', 'mountain', 'grass', 'meadow', 'coral', 'canyon', 'aurora', 'storm', 'garden', 'abyss'],
  magma_golem: ['volcano', 'hell', 'lava_field', 'ashland', 'cave', 'obsidian'],
  forest_guardian: ['grass', 'jungle', 'enchanted', 'meadow', 'garden', 'bramble'],
  void_stalker: ['shadow', 'graveyard', 'ruins', 'crystal', 'dungeon', 'battlefield', 'catacomb'],
  ice_wyrm: ['ice', 'snow', 'tundra', 'mountain', 'glacier', 'canyon'],
  necromancer: ['graveyard', 'ruins', 'dungeon', 'temple', 'shadow', 'wood', 'sandstone', 'battlefield', 'library', 'catacomb'],
  beholder: ['dungeon', 'cave', 'ruins', 'crystal', 'wood', 'battlefield', 'library'],
  dragon: ['mountain', 'volcano', 'sky', 'lava_field', 'canyon', 'aurora', 'storm'],
  lich: ['graveyard', 'ruins', 'dungeon', 'shadow', 'temple', 'wood', 'sandstone', 'battlefield', 'library', 'catacomb'],
  demon: ['hell', 'volcano', 'lava_field', 'blood'],
  grim_reaper: ['graveyard', 'shadow', 'ruins', 'blood', 'battlefield', 'catacomb'],
  frost_dragon: ['ice', 'snow', 'tundra', 'mountain', 'sky', 'glacier', 'canyon', 'aurora', 'storm'],
  bone_dragon: ['graveyard', 'ruins', 'dungeon', 'temple', 'shadow', 'sandstone', 'battlefield', 'catacomb'],
  kraken: ['sea', 'coral', 'abyss'],
  hydra_boss: ['sea', 'beach', 'coral', 'abyss'],
  medusa: ['ruins', 'temple', 'dungeon', 'jungle', 'coral', 'sandstone', 'battlefield', 'abyss', 'bramble'],
  phoenix: ['volcano', 'sky', 'lava_field', 'ashland', 'desert', 'oasis', 'aurora', 'obsidian', 'storm', 'saltflat'],
  titan: ['mountain', 'temple', 'ruins', 'sky', 'canyon', 'aurora', 'sandstone', 'storm', 'battlefield'],
  void_lord: ['shadow', 'crystal', 'ruins', 'battlefield'],
  ancient_treant: ['grass', 'jungle', 'enchanted', 'meadow', 'garden', 'bramble'],
  sand_worm: ['desert', 'ashland', 'oasis', 'obsidian', 'saltflat'],
  flame_lord: ['volcano', 'hell', 'lava_field', 'ashland', 'desert', 'oasis', 'obsidian', 'saltflat'],
  frost_lich: ['ice', 'snow', 'tundra', 'mountain', 'graveyard', 'glacier', 'canyon', 'catacomb'],
  plague_queen: ['swamp', 'sewer', 'mushroom', 'jungle', 'marsh', 'bramble'],
  storm_giant: ['sky', 'mountain', 'grass', 'meadow', 'tundra', 'canyon', 'aurora', 'storm', 'garden'],
  cerberus: ['hell', 'graveyard', 'lava_field', 'blood', 'catacomb'],
  basilisk: ['desert', 'ruins', 'cave', 'temple', 'coral', 'oasis', 'sandstone', 'battlefield', 'abyss', 'saltflat'],
  djinn: ['desert', 'sky', 'enchanted', 'oasis', 'aurora', 'storm', 'saltflat'],
  archdemon: ['hell', 'volcano', 'lava_field', 'blood'],
  world_serpent: ['swamp', 'jungle', 'sea', 'shadow', 'coral', 'marsh', 'abyss', 'bramble'],
  frogman: ['swamp', 'sewer', 'mushroom', 'jungle', 'coral', 'beach', 'marsh', 'abyss', 'bramble'],
  porcupine: ['grass', 'jungle', 'meadow', 'enchanted', 'mushroom', 'garden', 'bramble'],
  dune_viper: ['desert', 'beach', 'ashland', 'oasis', 'obsidian', 'saltflat'],
  moss_sprite: ['grass', 'jungle', 'meadow', 'enchanted', 'mushroom', 'garden', 'bramble'],
  scrap_golem: ['cave', 'mountain', 'dungeon', 'ruins', 'canyon', 'battlefield'],
  raven_scout: ['sky', 'mountain', 'grass', 'meadow', 'beach', 'canyon', 'aurora', 'storm', 'garden'],
  bog_witch_apprentice: ['ice', 'snow', 'tundra', 'mountain', 'swamp', 'wood', 'glacier', 'canyon', 'marsh', 'library'],
  crystal_bat: ['crystal', 'cave', 'enchanted', 'temple', 'sky', 'aurora', 'sandstone', 'storm'],
  iron_boar: ['cave', 'mountain', 'dungeon', 'ruins', 'grass', 'canyon', 'battlefield'],
  sand_archer: ['desert', 'beach', 'ashland', 'dungeon', 'wood', 'oasis', 'obsidian', 'library', 'saltflat'],
  frost_sprite: ['ice', 'snow', 'tundra', 'mountain', 'grass', 'glacier', 'canyon'],
  cave_crawler: ['cave', 'mountain', 'dungeon', 'ruins', 'canyon', 'battlefield'],
  marsh_lurker: ['swamp', 'sewer', 'mushroom', 'jungle', 'marsh', 'bramble'],
  ember_whelp: ['volcano', 'hell', 'lava_field', 'ashland', 'obsidian'],
  bone_picker: ['graveyard', 'ruins', 'dungeon', 'temple', 'shadow', 'sandstone', 'battlefield', 'catacomb'],
  thorn_bush: ['grass', 'jungle', 'meadow', 'enchanted', 'mushroom', 'garden', 'bramble'],
  ash_rat: ['volcano', 'hell', 'lava_field', 'ashland', 'dungeon', 'obsidian'],
  coral_crab: ['sea', 'beach', 'coral', 'abyss'],
  wind_sylph: ['sky', 'mountain', 'grass', 'meadow', 'enchanted', 'canyon', 'aurora', 'storm', 'garden'],
  tomb_guard: ['graveyard', 'ruins', 'dungeon', 'temple', 'shadow', 'sandstone', 'battlefield', 'catacomb'],
  spore_fungus: ['swamp', 'sewer', 'mushroom', 'jungle', 'marsh', 'bramble'],
  glacier_cub: ['ice', 'snow', 'tundra', 'mountain', 'glacier', 'canyon'],
  night_owl: ['shadow', 'graveyard', 'ruins', 'crystal', 'dungeon', 'battlefield', 'catacomb'],
  brimstone_imp: ['volcano', 'hell', 'lava_field', 'ashland', 'cave', 'obsidian'],
  reed_stalker: ['dirt', 'grass', 'meadow', 'ruins', 'dungeon', 'garden', 'battlefield'],
  thunder_hawk: ['sky', 'mountain', 'grass', 'meadow', 'canyon', 'aurora', 'storm', 'garden'],
  blood_ogre: ['blood', 'hell', 'graveyard', 'ruins', 'battlefield', 'catacomb'],
  mirage_dancer: ['desert', 'beach', 'ashland', 'oasis', 'obsidian', 'saltflat'],
  frost_berserker: ['ice', 'snow', 'tundra', 'mountain', 'glacier', 'canyon'],
  venom_alchemist: ['swamp', 'sewer', 'mushroom', 'jungle', 'dungeon', 'marsh', 'bramble'],
  obsidian_guardian: ['volcano', 'hell', 'lava_field', 'ashland', 'dungeon', 'obsidian'],
  soul_harvester: ['shadow', 'graveyard', 'ruins', 'crystal', 'dungeon', 'blood', 'battlefield', 'catacomb'],
  lava_serpent: ['volcano', 'hell', 'lava_field', 'ashland', 'obsidian'],
  mirror_wraith: ['shadow', 'graveyard', 'ruins', 'crystal', 'dungeon', 'battlefield', 'catacomb'],
  plague_rat_king: ['swamp', 'sewer', 'mushroom', 'jungle', 'dungeon', 'wood', 'marsh', 'library', 'bramble'],
  storm_rider: ['sky', 'mountain', 'grass', 'meadow', 'canyon', 'aurora', 'storm', 'garden'],
  ironbark_treant: ['grass', 'jungle', 'meadow', 'enchanted', 'mushroom', 'garden', 'bramble'],
  crimson_cultist: ['blood', 'hell', 'graveyard', 'ruins', 'dungeon', 'battlefield', 'catacomb'],
  void_imp_lord: ['shadow', 'graveyard', 'ruins', 'crystal', 'dungeon', 'blood', 'battlefield', 'catacomb'],
  sapphire_drake: ['crystal', 'cave', 'enchanted', 'temple', 'sky', 'aurora', 'sandstone', 'storm'],
  eclipse_sphinx: ['dirt', 'grass', 'meadow', 'ruins', 'dungeon', 'desert', 'oasis', 'garden', 'battlefield', 'saltflat'],
  magma_colossus: ['volcano', 'hell', 'lava_field', 'ashland', 'mountain', 'canyon', 'obsidian'],
  arctic_leviathan: ['ice', 'snow', 'tundra', 'mountain', 'sea', 'glacier', 'canyon'],
  blight_emperor: ['dirt', 'grass', 'meadow', 'ruins', 'dungeon', 'garden', 'battlefield'],
  chronomancer: ['enchanted', 'crystal', 'sky', 'meadow', 'aurora', 'storm', 'garden'],
  dread_naga: ['sea', 'beach', 'coral', 'abyss'],
  solar_phoenix: ['volcano', 'hell', 'lava_field', 'ashland', 'sky', 'desert', 'oasis', 'aurora', 'obsidian', 'storm', 'saltflat'],
  abyssal_kraken: ['sea', 'beach', 'coral', 'abyss'],
  bone_emperor: ['graveyard', 'ruins', 'dungeon', 'temple', 'shadow', 'wood', 'sandstone', 'battlefield', 'library', 'catacomb'],
  world_ender: ['shadow', 'hell', 'crystal', 'ruins', 'battlefield'],
  mushroom_brute: ['swamp', 'sewer', 'mushroom', 'jungle', 'marsh', 'bramble'],
  salt_golem: ['desert', 'beach', 'ashland', 'cave', 'mountain', 'oasis', 'canyon', 'obsidian', 'saltflat'],
  fox_trickster: ['grass', 'jungle', 'meadow', 'enchanted', 'mushroom', 'desert', 'oasis', 'garden', 'bramble', 'saltflat'],
  quill_hunter: ['grass', 'jungle', 'meadow', 'enchanted', 'mushroom', 'desert', 'oasis', 'garden', 'bramble', 'saltflat'],
  peat_zombie: ['swamp', 'sewer', 'mushroom', 'jungle', 'graveyard', 'marsh', 'catacomb', 'bramble'],
  lantern_spirit: ['enchanted', 'crystal', 'sky', 'meadow', 'aurora', 'storm', 'garden'],
  cliff_goat: ['mountain', 'tundra', 'cave', 'meadow', 'canyon', 'garden'],
  reef_shark: ['sea', 'beach', 'coral', 'abyss'],
  dust_mephit: ['dirt', 'grass', 'meadow', 'ruins', 'dungeon', 'desert', 'beach', 'oasis', 'garden', 'battlefield', 'saltflat'],
  bark_spider: ['grass', 'jungle', 'meadow', 'enchanted', 'mushroom', 'garden', 'bramble'],
  snow_hare: ['ice', 'snow', 'tundra', 'mountain', 'glacier', 'canyon'],
  torch_bearer: ['dungeon', 'wood', 'ruins', 'temple', 'dirt', 'sandstone', 'battlefield', 'library'],
  bog_mosquito: ['swamp', 'sewer', 'mushroom', 'jungle', 'marsh', 'bramble'],
  rune_scribe: ['crystal', 'cave', 'enchanted', 'temple', 'dungeon', 'wood', 'sandstone', 'library'],
  clay_soldier: ['dungeon', 'wood', 'ruins', 'temple', 'dirt', 'sandstone', 'battlefield', 'library'],
  pearl_diver: ['sea', 'beach', 'coral', 'abyss'],
  night_panther: ['shadow', 'graveyard', 'ruins', 'crystal', 'dungeon', 'battlefield', 'catacomb'],
  hive_drone: ['grass', 'jungle', 'meadow', 'enchanted', 'mushroom', 'garden', 'bramble'],
  frost_toad: ['ice', 'snow', 'tundra', 'mountain', 'swamp', 'glacier', 'canyon', 'marsh'],
  scrap_bandit: ['cave', 'mountain', 'dungeon', 'ruins', 'wood', 'canyon', 'battlefield', 'library'],
  vine_creeper: ['grass', 'jungle', 'meadow', 'enchanted', 'mushroom', 'garden', 'bramble'],
  cinder_sprite: ['volcano', 'hell', 'lava_field', 'ashland', 'grass', 'obsidian'],
  tunnel_mole: ['cave', 'mountain', 'dungeon', 'ruins', 'canyon', 'battlefield'],
  glass_imp: ['crystal', 'cave', 'enchanted', 'temple', 'hell', 'ice', 'glacier', 'sandstone'],
  thunder_boar: ['sky', 'mountain', 'grass', 'meadow', 'jungle', 'canyon', 'aurora', 'storm', 'garden', 'bramble'],
  blood_knight: ['blood', 'hell', 'graveyard', 'ruins', 'dungeon', 'battlefield', 'catacomb'],
  sand_djinni: ['desert', 'beach', 'ashland', 'oasis', 'obsidian', 'saltflat'],
  poison_archer: ['swamp', 'sewer', 'mushroom', 'jungle', 'dungeon', 'marsh', 'bramble'],
  jade_golem: ['crystal', 'cave', 'enchanted', 'temple', 'mountain', 'canyon', 'sandstone'],
  shadow_priest: ['shadow', 'graveyard', 'ruins', 'crystal', 'dungeon', 'wood', 'battlefield', 'library', 'catacomb'],
  bladed_mantis: ['grass', 'jungle', 'meadow', 'enchanted', 'mushroom', 'garden', 'bramble'],
  storm_witch: ['sky', 'mountain', 'grass', 'meadow', 'dungeon', 'canyon', 'aurora', 'storm', 'garden'],
  furnace_beast: ['volcano', 'hell', 'lava_field', 'ashland', 'obsidian'],
  crystal_archer: ['crystal', 'cave', 'enchanted', 'temple', 'dungeon', 'sandstone'],
  void_hound: ['shadow', 'graveyard', 'ruins', 'crystal', 'dungeon', 'blood', 'battlefield', 'catacomb'],
  plague_swarm: ['swamp', 'sewer', 'mushroom', 'jungle', 'blood', 'marsh', 'bramble'],
  iron_sentinel: ['cave', 'mountain', 'dungeon', 'ruins', 'wood', 'canyon', 'battlefield', 'library'],
  aurora_mage: ['ice', 'snow', 'tundra', 'mountain', 'dungeon', 'glacier', 'canyon'],
  ash_wyvern: ['volcano', 'hell', 'lava_field', 'ashland', 'sky', 'aurora', 'obsidian', 'storm'],
  bone_reaver: ['graveyard', 'ruins', 'dungeon', 'temple', 'shadow', 'blood', 'sandstone', 'battlefield', 'catacomb'],
  tempest_queen: ['sky', 'mountain', 'grass', 'meadow', 'sea', 'canyon', 'aurora', 'storm', 'garden'],
  forge_titan: ['volcano', 'hell', 'lava_field', 'ashland', 'mountain', 'canyon', 'obsidian'],
  coral_empress: ['sea', 'beach', 'coral', 'abyss'],
  nightmare_king: ['shadow', 'graveyard', 'ruins', 'crystal', 'dungeon', 'wood', 'battlefield', 'library', 'catacomb'],
  elder_beholder: ['dirt', 'grass', 'meadow', 'ruins', 'dungeon', 'wood', 'garden', 'battlefield', 'library'],
  doom_hydra: ['sea', 'beach', 'coral', 'abyss'],
  astral_serpent: ['enchanted', 'crystal', 'sky', 'meadow', 'aurora', 'storm', 'garden'],
  war_god_avatar: ['dirt', 'grass', 'meadow', 'ruins', 'dungeon', 'desert', 'oasis', 'garden', 'battlefield', 'saltflat'],
  necrotic_colossus: ['graveyard', 'ruins', 'dungeon', 'temple', 'shadow', 'sandstone', 'battlefield', 'catacomb'],
  chaos_primordial: ['shadow', 'crystal', 'hell', 'ruins', 'battlefield'],
  pebble_sprite: ['cave', 'mountain', 'dungeon', 'ruins', 'grass', 'canyon', 'battlefield'],
  reed_rat: ['dungeon', 'wood', 'ruins', 'temple', 'dirt', 'sandstone', 'battlefield', 'library'],
  tide_urchin: ['sea', 'beach', 'coral', 'abyss'],
  cinder_moth: ['volcano', 'hell', 'lava_field', 'ashland', 'obsidian'],
  pine_sprite: ['grass', 'jungle', 'meadow', 'enchanted', 'mushroom', 'garden', 'bramble'],
  copper_goblin: ['dungeon', 'wood', 'ruins', 'temple', 'dirt', 'sandstone', 'battlefield', 'library'],
  mist_wisp: ['enchanted', 'crystal', 'sky', 'meadow', 'ice', 'glacier', 'aurora', 'storm', 'garden'],
  brine_crab: ['sea', 'beach', 'coral', 'abyss'],
  soot_imp: ['hell', 'volcano', 'lava_field', 'blood'],
  thistle_boar: ['grass', 'jungle', 'meadow', 'enchanted', 'mushroom', 'garden', 'bramble'],
  kelp_strider: ['sea', 'beach', 'coral', 'abyss'],
  ember_gnat: ['volcano', 'hell', 'lava_field', 'ashland', 'obsidian'],
  chalk_golem_cub: ['cave', 'mountain', 'dungeon', 'ruins', 'canyon', 'battlefield'],
  dusk_ferret: ['shadow', 'graveyard', 'ruins', 'crystal', 'dungeon', 'battlefield', 'catacomb'],
  bog_newt: ['swamp', 'sewer', 'mushroom', 'jungle', 'marsh', 'bramble'],
  crystal_mite: ['crystal', 'cave', 'enchanted', 'temple', 'mountain', 'canyon', 'sandstone'],
  rust_scorpion: ['desert', 'beach', 'ashland', 'oasis', 'obsidian', 'saltflat'],
  pollen_pixie: ['grass', 'jungle', 'meadow', 'enchanted', 'mushroom', 'garden', 'bramble'],
  shale_basher: ['cave', 'mountain', 'dungeon', 'ruins', 'canyon', 'battlefield'],
  frost_vole: ['ice', 'snow', 'tundra', 'mountain', 'glacier', 'canyon'],
  tar_slug: ['swamp', 'sewer', 'mushroom', 'jungle', 'marsh', 'bramble'],
  spark_sprite: ['grass', 'jungle', 'meadow', 'enchanted', 'mushroom', 'garden', 'bramble'],
  dune_jackal: ['desert', 'beach', 'ashland', 'oasis', 'obsidian', 'saltflat'],
  lichen_troll_cub: ['graveyard', 'ruins', 'dungeon', 'temple', 'shadow', 'sandstone', 'battlefield', 'catacomb'],
  ivory_skeleton: ['graveyard', 'ruins', 'dungeon', 'temple', 'shadow', 'sandstone', 'battlefield', 'catacomb'],
  mangrove_croco: ['dirt', 'grass', 'meadow', 'ruins', 'dungeon', 'garden', 'battlefield'],
  storm_finch: ['sky', 'mountain', 'grass', 'meadow', 'canyon', 'aurora', 'storm', 'garden'],
  ash_cult_initiate: ['volcano', 'hell', 'lava_field', 'ashland', 'dungeon', 'obsidian'],
  prism_moth: ['crystal', 'cave', 'enchanted', 'temple', 'sandstone'],
  geyser_toad: ['swamp', 'sewer', 'mushroom', 'jungle', 'coral', 'marsh', 'abyss', 'bramble'],
  carrion_vulture: ['graveyard', 'ruins', 'dungeon', 'temple', 'shadow', 'sandstone', 'battlefield', 'catacomb'],
  magma_grub: ['volcano', 'hell', 'lava_field', 'ashland', 'obsidian'],
  void_mote: ['shadow', 'graveyard', 'ruins', 'crystal', 'dungeon', 'battlefield', 'catacomb'],
  salt_wraith: ['shadow', 'graveyard', 'ruins', 'crystal', 'dungeon', 'battlefield', 'catacomb'],
  iron_tick: ['cave', 'mountain', 'dungeon', 'ruins', 'canyon', 'battlefield'],
  glacier_imp: ['ice', 'snow', 'tundra', 'mountain', 'hell', 'glacier', 'canyon'],
  thorn_imp: ['grass', 'jungle', 'meadow', 'enchanted', 'mushroom', 'garden', 'bramble'],
  cave_bat_swarm: ['sky', 'mountain', 'grass', 'meadow', 'cave', 'canyon', 'aurora', 'storm', 'garden'],
  scrap_wolf: ['cave', 'mountain', 'dungeon', 'ruins', 'grass', 'canyon', 'battlefield'],
  coral_snake: ['sea', 'beach', 'coral', 'abyss'],
  rune_imp: ['crystal', 'cave', 'enchanted', 'temple', 'hell', 'sandstone'],
  peat_slime: ['swamp', 'sewer', 'mushroom', 'jungle', 'marsh', 'bramble'],
  wind_razor: ['sky', 'mountain', 'grass', 'meadow', 'canyon', 'aurora', 'storm', 'garden'],
  blood_leech: ['swamp', 'sewer', 'mushroom', 'jungle', 'blood', 'marsh', 'bramble'],
  frost_archer_novice: ['ice', 'snow', 'tundra', 'mountain', 'dungeon', 'glacier', 'canyon'],
  shade_larva: ['shadow', 'graveyard', 'ruins', 'crystal', 'dungeon', 'battlefield', 'catacomb'],
  pyre_cultist: ['volcano', 'hell', 'lava_field', 'ashland', 'dungeon', 'obsidian'],
  quartz_beetle: ['crystal', 'cave', 'enchanted', 'temple', 'sandstone'],
  acid_alchemist: ['dungeon', 'wood', 'ruins', 'temple', 'dirt', 'sandstone', 'battlefield', 'library'],
  frost_wyvern: ['ice', 'snow', 'tundra', 'mountain', 'sky', 'glacier', 'canyon', 'aurora', 'storm'],
  bone_chanter: ['graveyard', 'ruins', 'dungeon', 'temple', 'shadow', 'sandstone', 'battlefield', 'catacomb'],
  hex_witch: ['shadow', 'graveyard', 'ruins', 'crystal', 'dungeon', 'battlefield', 'catacomb'],
  magma_brute: ['volcano', 'hell', 'lava_field', 'ashland', 'obsidian'],
  storm_centurion: ['sky', 'mountain', 'grass', 'meadow', 'dungeon', 'canyon', 'aurora', 'storm', 'garden'],
  obsidian_raptor: ['volcano', 'hell', 'lava_field', 'ashland', 'obsidian'],
  venom_naga: ['swamp', 'sewer', 'mushroom', 'jungle', 'sea', 'coral', 'marsh', 'abyss', 'bramble'],
  crystal_guardian: ['crystal', 'cave', 'enchanted', 'temple', 'dungeon', 'sandstone'],
  shadow_duelist: ['shadow', 'graveyard', 'ruins', 'crystal', 'dungeon', 'battlefield', 'catacomb'],
  pyre_drake: ['volcano', 'hell', 'lava_field', 'ashland', 'sky', 'aurora', 'obsidian', 'storm'],
  glacier_knight: ['ice', 'snow', 'tundra', 'mountain', 'dungeon', 'glacier', 'canyon'],
  plague_harpy: ['swamp', 'sewer', 'mushroom', 'jungle', 'sky', 'marsh', 'aurora', 'storm', 'bramble'],
  rune_golem: ['crystal', 'cave', 'enchanted', 'temple', 'mountain', 'canyon', 'sandstone'],
  blood_panther: ['blood', 'hell', 'graveyard', 'ruins', 'grass', 'battlefield', 'catacomb'],
  arcane_archer: ['dungeon', 'wood', 'ruins', 'temple', 'dirt', 'sandstone', 'battlefield', 'library'],
  furnace_golem: ['volcano', 'hell', 'lava_field', 'ashland', 'cave', 'obsidian'],
  void_serpent: ['shadow', 'graveyard', 'ruins', 'crystal', 'dungeon', 'battlefield', 'catacomb'],
  jade_monk: ['crystal', 'cave', 'enchanted', 'temple', 'dungeon', 'sandstone'],
  thunder_drake: ['sky', 'mountain', 'grass', 'meadow', 'canyon', 'aurora', 'storm', 'garden'],
  mirror_knight: ['dungeon', 'wood', 'ruins', 'temple', 'dirt', 'sandstone', 'battlefield', 'library'],
  blight_treant: ['grass', 'jungle', 'meadow', 'enchanted', 'mushroom', 'garden', 'bramble'],
  ash_assassin: ['volcano', 'hell', 'lava_field', 'ashland', 'dungeon', 'obsidian'],
  sapphire_witch: ['crystal', 'cave', 'enchanted', 'temple', 'dungeon', 'sandstone'],
  iron_hydra: ['sea', 'beach', 'coral', 'cave', 'mountain', 'canyon', 'abyss'],
  soul_thief: ['shadow', 'graveyard', 'ruins', 'crystal', 'dungeon', 'blood', 'battlefield', 'catacomb'],
  cinder_titan_spawn: ['volcano', 'hell', 'lava_field', 'ashland', 'mountain', 'canyon', 'obsidian'],
  aurora_serpent: ['ice', 'snow', 'tundra', 'mountain', 'enchanted', 'glacier', 'canyon'],
  grave_sentinel: ['graveyard', 'ruins', 'dungeon', 'temple', 'shadow', 'sandstone', 'battlefield', 'catacomb'],
  night_reaver: ['shadow', 'graveyard', 'ruins', 'crystal', 'dungeon', 'blood', 'battlefield', 'catacomb'],
  ember_witch: ['volcano', 'hell', 'lava_field', 'ashland', 'dungeon', 'obsidian'],
  toxin_archer: ['swamp', 'sewer', 'mushroom', 'jungle', 'dungeon', 'marsh', 'bramble'],
  acid_sovereign: ['dirt', 'grass', 'meadow', 'ruins', 'dungeon', 'garden', 'battlefield'],
  frost_empress: ['ice', 'snow', 'tundra', 'mountain', 'glacier', 'canyon'],
  bone_overlord: ['graveyard', 'ruins', 'dungeon', 'temple', 'shadow', 'sandstone', 'battlefield', 'catacomb'],
  hex_archon: ['shadow', 'graveyard', 'ruins', 'crystal', 'dungeon', 'battlefield', 'catacomb'],
  magma_tyrant: ['volcano', 'hell', 'lava_field', 'ashland', 'obsidian'],
  storm_colossus: ['sky', 'mountain', 'grass', 'meadow', 'tundra', 'sea', 'canyon', 'aurora', 'storm', 'garden'],
  void_matriarch: ['shadow', 'graveyard', 'ruins', 'crystal', 'dungeon', 'battlefield', 'catacomb'],
  plague_sovereign: ['swamp', 'sewer', 'mushroom', 'jungle', 'wood', 'marsh', 'library', 'bramble'],
  solar_phoenix_lord: ['volcano', 'hell', 'lava_field', 'ashland', 'sky', 'aurora', 'obsidian', 'storm'],
  abyss_leviathan: ['shadow', 'graveyard', 'ruins', 'crystal', 'dungeon', 'coral', 'battlefield', 'catacomb', 'abyss'],
  jade_emperor: ['crystal', 'cave', 'enchanted', 'temple', 'sandstone'],
  crimson_warlord: ['blood', 'hell', 'graveyard', 'ruins', 'battlefield', 'catacomb'],
  necrotic_queen: ['graveyard', 'ruins', 'dungeon', 'temple', 'shadow', 'wood', 'sandstone', 'battlefield', 'library', 'catacomb'],
  entropy_dragon: ['shadow', 'graveyard', 'ruins', 'crystal', 'dungeon', 'battlefield', 'catacomb'],
  iron_behemoth: ['cave', 'mountain', 'dungeon', 'ruins', 'tundra', 'canyon', 'battlefield'],
  mire_hydra_king: ['swamp', 'sewer', 'mushroom', 'jungle', 'sea', 'coral', 'marsh', 'abyss', 'bramble'],
  astral_tyrant: ['enchanted', 'crystal', 'sky', 'meadow', 'aurora', 'storm', 'garden'],
  forge_emperor: ['volcano', 'hell', 'lava_field', 'ashland', 'obsidian'],
  shadow_primordial: ['shadow', 'graveyard', 'ruins', 'crystal', 'dungeon', 'battlefield', 'catacomb'],
  tide_kraken_lord: ['sea', 'beach', 'coral', 'abyss'],
  amber_mite: ['desert', 'oasis', 'ashland', 'saltflat', 'beach', 'obsidian'],
  fog_hare: ['grass', 'jungle', 'meadow', 'enchanted', 'garden', 'bramble'],
  driftwood_crab: ['sea', 'beach', 'coral', 'abyss'],
  pollen_moth: ['grass', 'jungle', 'meadow', 'enchanted', 'garden', 'bramble'],
  basalt_cub: ['cave', 'mountain', 'dungeon', 'ruins', 'canyon', 'battlefield'],
  reed_imp: ['swamp', 'sewer', 'mushroom', 'marsh', 'bramble', 'jungle'],
  snow_finch: ['ice', 'snow', 'tundra', 'glacier', 'mountain', 'canyon'],
  salt_scorpion: ['desert', 'oasis', 'ashland', 'saltflat', 'beach', 'obsidian'],
  moss_newt: ['swamp', 'sewer', 'mushroom', 'marsh', 'bramble', 'jungle'],
  copper_tick: ['cave', 'mountain', 'dungeon', 'ruins', 'canyon', 'battlefield'],
  tide_sprite: ['sea', 'beach', 'coral', 'abyss'],
  ash_vole: ['volcano', 'hell', 'lava_field', 'ashland', 'obsidian'],
  bramble_boar: ['grass', 'jungle', 'meadow', 'enchanted', 'garden', 'bramble'],
  chalk_imp: ['temple', 'ruins', 'dungeon', 'sandstone', 'library', 'battlefield'],
  mire_slug: ['swamp', 'sewer', 'mushroom', 'marsh', 'bramble', 'jungle'],
  gust_sylph: ['sky', 'mountain', 'aurora', 'storm', 'canyon', 'meadow'],
  onyx_beetle: ['cave', 'mountain', 'dungeon', 'ruins', 'canyon', 'battlefield'],
  peat_rat: ['swamp', 'sewer', 'mushroom', 'marsh', 'bramble', 'jungle'],
  glint_pixie: ['crystal', 'cave', 'enchanted', 'temple', 'sandstone', 'abyss'],
  dune_scarab: ['desert', 'oasis', 'ashland', 'saltflat', 'beach', 'obsidian'],
  frost_gnat: ['ice', 'snow', 'tundra', 'glacier', 'mountain', 'canyon'],
  root_crawler: ['grass', 'jungle', 'meadow', 'enchanted', 'garden', 'bramble'],
  cinder_toad: ['volcano', 'hell', 'lava_field', 'ashland', 'obsidian'],
  pearl_slug: ['sea', 'beach', 'coral', 'abyss'],
  rune_mite: ['temple', 'ruins', 'dungeon', 'sandstone', 'library', 'battlefield'],
  shadow_vole: ['shadow', 'graveyard', 'ruins', 'crystal', 'dungeon', 'catacomb'],
  coral_urchin: ['sea', 'beach', 'coral', 'abyss'],
  pine_imp: ['grass', 'jungle', 'meadow', 'enchanted', 'garden', 'bramble'],
  slag_imp: ['volcano', 'hell', 'lava_field', 'ashland', 'obsidian'],
  ice_tick: ['ice', 'snow', 'tundra', 'glacier', 'mountain', 'canyon'],
  bog_finch: ['swamp', 'sewer', 'mushroom', 'marsh', 'bramble', 'jungle'],
  quartz_mite: ['crystal', 'cave', 'enchanted', 'temple', 'sandstone', 'abyss'],
  dust_jackal: ['desert', 'oasis', 'ashland', 'saltflat', 'beach', 'obsidian'],
  kelp_newt: ['sea', 'beach', 'coral', 'abyss'],
  ember_vole: ['volcano', 'hell', 'lava_field', 'ashland', 'obsidian'],
  thorn_mite: ['grass', 'jungle', 'meadow', 'enchanted', 'garden', 'bramble'],
  mist_imp: ['shadow', 'graveyard', 'ruins', 'crystal', 'dungeon', 'catacomb'],
  shale_tick: ['cave', 'mountain', 'dungeon', 'ruins', 'canyon', 'battlefield'],
  aurora_moth: ['sky', 'mountain', 'aurora', 'storm', 'canyon', 'meadow'],
  blood_mite: ['graveyard', 'ruins', 'dungeon', 'shadow', 'catacomb', 'battlefield', 'blood'],
  salt_newt: ['desert', 'oasis', 'ashland', 'saltflat', 'beach', 'obsidian'],
  vine_imp: ['grass', 'jungle', 'meadow', 'enchanted', 'garden', 'bramble'],
  glacier_mite: ['ice', 'snow', 'tundra', 'glacier', 'mountain', 'canyon'],
  scrap_tick: ['cave', 'mountain', 'dungeon', 'ruins', 'canyon', 'battlefield'],
  void_gnat: ['shadow', 'graveyard', 'ruins', 'crystal', 'dungeon', 'catacomb'],
  marsh_imp: ['swamp', 'sewer', 'mushroom', 'marsh', 'bramble', 'jungle'],
  crystal_finch: ['crystal', 'cave', 'enchanted', 'temple', 'sandstone', 'abyss'],
  pyre_mite: ['hell', 'volcano', 'lava_field', 'blood'],
  amber_golem: ['desert', 'oasis', 'ashland', 'saltflat', 'beach', 'obsidian'],
  fog_wraith: ['shadow', 'graveyard', 'ruins', 'crystal', 'dungeon', 'catacomb'],
  drift_krakenling: ['sea', 'beach', 'coral', 'abyss'],
  pollen_witch: ['grass', 'jungle', 'meadow', 'enchanted', 'garden', 'bramble'],
  basalt_guardian: ['cave', 'mountain', 'dungeon', 'ruins', 'canyon', 'battlefield'],
  reed_naga: ['swamp', 'sewer', 'mushroom', 'marsh', 'bramble', 'jungle'],
  snow_berserker: ['ice', 'snow', 'tundra', 'glacier', 'mountain', 'canyon'],
  salt_goliath: ['desert', 'oasis', 'ashland', 'saltflat', 'beach', 'obsidian'],
  moss_treant: ['swamp', 'sewer', 'mushroom', 'marsh', 'bramble', 'jungle'],
  copper_sentinel: ['cave', 'mountain', 'dungeon', 'ruins', 'canyon', 'battlefield'],
  tide_witch: ['sea', 'beach', 'coral', 'abyss'],
  ash_assassin_adept: ['volcano', 'hell', 'lava_field', 'ashland', 'obsidian'],
  bramble_hydra: ['grass', 'jungle', 'meadow', 'enchanted', 'garden', 'bramble'],
  chalk_mage: ['temple', 'ruins', 'dungeon', 'sandstone', 'library', 'battlefield'],
  mire_hydra: ['swamp', 'sewer', 'mushroom', 'marsh', 'bramble', 'jungle'],
  gust_djinn: ['sky', 'mountain', 'aurora', 'storm', 'canyon', 'meadow'],
  onyx_knight: ['cave', 'mountain', 'dungeon', 'ruins', 'canyon', 'battlefield'],
  peat_necromancer: ['graveyard', 'ruins', 'dungeon', 'shadow', 'catacomb', 'battlefield', 'blood'],
  glint_sphinx: ['crystal', 'cave', 'enchanted', 'temple', 'sandstone', 'abyss'],
  dune_wyrm: ['desert', 'oasis', 'ashland', 'saltflat', 'beach', 'obsidian'],
  frost_centurion: ['ice', 'snow', 'tundra', 'glacier', 'mountain', 'canyon'],
  root_guardian: ['grass', 'jungle', 'meadow', 'enchanted', 'garden', 'bramble'],
  cinder_drake: ['volcano', 'hell', 'lava_field', 'ashland', 'obsidian'],
  pearl_siren: ['sea', 'beach', 'coral', 'abyss'],
  rune_archon_adept: ['temple', 'ruins', 'dungeon', 'sandstone', 'library', 'battlefield'],
  shadow_duelist_elite: ['shadow', 'graveyard', 'ruins', 'crystal', 'dungeon', 'catacomb'],
  coral_hydra: ['sea', 'beach', 'coral', 'abyss'],
  pine_treant: ['grass', 'jungle', 'meadow', 'enchanted', 'garden', 'bramble'],
  slag_golem: ['volcano', 'hell', 'lava_field', 'ashland', 'obsidian'],
  ice_wyvern_adept: ['ice', 'snow', 'tundra', 'glacier', 'mountain', 'canyon'],
  bog_alchemist: ['swamp', 'sewer', 'mushroom', 'marsh', 'bramble', 'jungle'],
  quartz_guardian: ['crystal', 'cave', 'enchanted', 'temple', 'sandstone', 'abyss'],
  amber_sovereign: ['desert', 'oasis', 'ashland', 'saltflat', 'beach', 'obsidian'],
  fog_matriarch: ['shadow', 'graveyard', 'ruins', 'crystal', 'dungeon', 'catacomb'],
  drift_kraken_king: ['sea', 'beach', 'coral', 'abyss'],
  pollen_empress: ['grass', 'jungle', 'meadow', 'enchanted', 'garden', 'bramble'],
  basalt_colossus: ['cave', 'mountain', 'dungeon', 'ruins', 'canyon', 'battlefield'],
  reed_hydra_queen: ['swamp', 'sewer', 'mushroom', 'marsh', 'bramble', 'jungle'],
  snow_emperor: ['ice', 'snow', 'tundra', 'glacier', 'mountain', 'canyon'],
  salt_tyrant: ['desert', 'oasis', 'ashland', 'saltflat', 'beach', 'obsidian'],
  moss_world_tree: ['grass', 'jungle', 'meadow', 'enchanted', 'garden', 'bramble'],
  copper_behemoth: ['cave', 'mountain', 'dungeon', 'ruins', 'canyon', 'battlefield'],
  tide_leviathan: ['sea', 'beach', 'coral', 'abyss'],
  ash_warlord: ['volcano', 'hell', 'lava_field', 'ashland', 'obsidian'],
  bramble_primordial: ['grass', 'jungle', 'meadow', 'enchanted', 'garden', 'bramble'],
  chalk_archon: ['temple', 'ruins', 'dungeon', 'sandstone', 'library', 'battlefield'],
  mire_sovereign: ['swamp', 'sewer', 'mushroom', 'marsh', 'bramble', 'jungle'],
  gust_storm_lord: ['sky', 'mountain', 'aurora', 'storm', 'canyon', 'meadow'],
  onyx_overlord: ['cave', 'mountain', 'dungeon', 'ruins', 'canyon', 'battlefield'],
  peat_bone_king: ['graveyard', 'ruins', 'dungeon', 'shadow', 'catacomb', 'battlefield', 'blood'],
  glint_astral_lord: ['crystal', 'cave', 'enchanted', 'temple', 'sandstone', 'abyss'],
  dune_sand_emperor: ['desert', 'oasis', 'ashland', 'saltflat', 'beach', 'obsidian'],
  orc_recruit: ['dirt', 'grass', 'mountain', 'ashland', 'meadow', 'desert', 'blood', 'oasis', 'canyon', 'obsidian', 'garden', 'saltflat'],
  goblin_scout: ['dirt', 'grass', 'cave', 'dungeon', 'mountain', 'wood', 'canyon', 'library'],
  slime_spawn: ['sewer', 'dungeon', 'cave', 'swamp', 'mushroom', 'marsh'],
  wolf_pup: ['grass', 'meadow', 'tundra', 'snow', 'mountain', 'canyon', 'garden'],
  skeleton_recruit: ['graveyard', 'dungeon', 'ruins', 'temple', 'wood', 'blood', 'sandstone', 'battlefield', 'library', 'catacomb'],
  bat_hatchling: ['cave', 'dungeon', 'graveyard', 'shadow', 'wood', 'blood', 'library', 'catacomb'],
  imp_whelp: ['volcano', 'hell', 'lava_field', 'dungeon', 'blood'],
  elf_apprentice: ['grass', 'enchanted', 'jungle', 'meadow', 'garden', 'bramble'],
  zombie_thrall: ['graveyard', 'swamp', 'dungeon', 'sewer', 'blood', 'marsh', 'catacomb'],
  mummy_servant: ['desert', 'temple', 'ruins', 'graveyard', 'oasis', 'sandstone', 'battlefield', 'catacomb', 'saltflat'],
  ghoul_scavenger: ['graveyard', 'dungeon', 'sewer', 'ruins', 'blood', 'battlefield', 'catacomb'],
  kobold_miner: ['dungeon', 'wood', 'ruins', 'temple', 'dirt', 'sandstone', 'battlefield', 'library'],
  bandit_thug: ['dungeon', 'wood', 'ruins', 'temple', 'dirt', 'desert', 'blood', 'oasis', 'sandstone', 'battlefield', 'library', 'saltflat'],
  pirate_deckhand: ['sea', 'beach', 'wood', 'coral', 'library', 'abyss'],
  cyclops_youth: ['mountain', 'cave', 'ruins', 'canyon', 'battlefield'],
  minotaur_calf: ['dungeon', 'ruins', 'temple', 'sandstone', 'battlefield'],
  harpy_fledgling: ['sky', 'mountain', 'ruins', 'canyon', 'aurora', 'storm', 'battlefield'],
  scorpion_nymph: ['desert', 'beach', 'ashland', 'oasis', 'obsidian', 'saltflat'],
  cultist_initiate: ['dungeon', 'ruins', 'temple', 'shadow', 'blood', 'wood', 'sandstone', 'battlefield', 'library'],
  gargoyle_shard: ['ruins', 'temple', 'dungeon', 'sky', 'aurora', 'sandstone', 'storm', 'battlefield'],
  pixie_spark: ['enchanted', 'grass', 'meadow', 'mushroom', 'garden'],
  gnoll_pup: ['dirt', 'grass', 'meadow', 'ruins', 'dungeon', 'desert', 'oasis', 'garden', 'battlefield', 'saltflat'],
  ratman_squeaker: ['dungeon', 'wood', 'ruins', 'temple', 'dirt', 'blood', 'sandstone', 'battlefield', 'library'],
  crab_hatchling: ['beach', 'sea', 'coral', 'abyss'],
  wasp_drone: ['grass', 'jungle', 'meadow', 'enchanted', 'mushroom', 'beach', 'garden', 'bramble'],
  toad_tadpole: ['swamp', 'sewer', 'mushroom', 'jungle', 'mountain', 'canyon', 'marsh', 'bramble'],
  dwarf_squire: ['dungeon', 'wood', 'ruins', 'temple', 'dirt', 'sandstone', 'battlefield', 'library'],
  wraith_shade: ['graveyard', 'shadow', 'ruins', 'ice', 'blood', 'glacier', 'battlefield', 'catacomb'],
  frogman_poliwog: ['swamp', 'sewer', 'mushroom', 'jungle', 'coral', 'beach', 'marsh', 'abyss', 'bramble'],
  porcupine_kit: ['grass', 'jungle', 'meadow', 'enchanted', 'mushroom', 'garden', 'bramble'],
  raven_chick: ['sky', 'mountain', 'grass', 'meadow', 'beach', 'canyon', 'aurora', 'storm', 'garden'],
  boar_piglet: ['cave', 'mountain', 'dungeon', 'ruins', 'grass', 'canyon', 'battlefield'],
  owl_fledgling: ['shadow', 'graveyard', 'ruins', 'crystal', 'dungeon', 'battlefield', 'catacomb'],
  fox_kit: ['grass', 'jungle', 'meadow', 'enchanted', 'mushroom', 'desert', 'oasis', 'garden', 'bramble', 'saltflat'],
  shark_pup: ['sea', 'beach', 'coral', 'abyss'],
  hive_larva: ['grass', 'jungle', 'meadow', 'enchanted', 'mushroom', 'garden', 'bramble'],
  yeti_whelp: ['snow', 'tundra', 'mountain', 'ice', 'glacier', 'canyon'],
  spiderling: ['cave', 'dungeon', 'jungle', 'mushroom', 'wood', 'library', 'bramble'],
  snake_hatchling: ['swamp', 'sewer', 'mushroom', 'jungle', 'marsh', 'bramble'],
  desert_jackal_pup: ['desert', 'beach', 'ashland', 'cave', 'mountain', 'oasis', 'canyon', 'obsidian', 'saltflat'],
  troll_runt: ['cave', 'mountain', 'dungeon', 'ruins', 'tundra', 'canyon', 'battlefield'],
  slug_nymph: ['swamp', 'sewer', 'mushroom', 'jungle', 'marsh', 'bramble'],
  ice_imp_spark: ['ice', 'snow', 'tundra', 'mountain', 'hell', 'glacier', 'canyon'],
  scarab_larva: ['desert', 'beach', 'ashland', 'oasis', 'obsidian', 'saltflat'],
  bone_shardling: ['graveyard', 'ruins', 'dungeon', 'temple', 'shadow', 'sandstone', 'battlefield', 'catacomb'],
  ember_spark: ['volcano', 'hell', 'lava_field', 'ashland', 'obsidian'],
  ash_rat_pup: ['volcano', 'hell', 'lava_field', 'ashland', 'dungeon', 'obsidian'],
  coral_crab_hatch: ['sea', 'beach', 'coral', 'abyss'],
  orc_war_chief: ['dirt', 'grass', 'mountain', 'ashland', 'meadow', 'desert', 'blood', 'oasis', 'canyon', 'obsidian', 'garden', 'saltflat'],
  goblin_raid_captain: ['dirt', 'grass', 'cave', 'dungeon', 'mountain', 'wood', 'canyon', 'library'],
  slime_overseer: ['sewer', 'dungeon', 'cave', 'swamp', 'mushroom', 'marsh'],
  wolf_alpha: ['grass', 'meadow', 'tundra', 'snow', 'mountain', 'canyon', 'garden'],
  skeleton_captain: ['graveyard', 'dungeon', 'ruins', 'temple', 'wood', 'blood', 'sandstone', 'battlefield', 'library', 'catacomb'],
  bat_matriarch: ['cave', 'dungeon', 'graveyard', 'shadow', 'wood', 'blood', 'library', 'catacomb'],
  imp_taskmaster: ['volcano', 'hell', 'lava_field', 'dungeon', 'blood'],
  elf_blademaster: ['grass', 'enchanted', 'jungle', 'meadow', 'garden', 'bramble'],
  zombie_warlord: ['graveyard', 'swamp', 'dungeon', 'sewer', 'blood', 'marsh', 'catacomb'],
  mummy_pharaoh_guard: ['desert', 'temple', 'ruins', 'graveyard', 'oasis', 'sandstone', 'battlefield', 'catacomb', 'saltflat'],
  ghoul_packleader: ['graveyard', 'dungeon', 'sewer', 'ruins', 'blood', 'battlefield', 'catacomb'],
  kobold_trapmaster: ['dungeon', 'wood', 'ruins', 'temple', 'dirt', 'sandstone', 'battlefield', 'library'],
  bandit_kingpin: ['dungeon', 'wood', 'ruins', 'temple', 'dirt', 'desert', 'blood', 'oasis', 'sandstone', 'battlefield', 'library', 'saltflat'],
  pirate_captain: ['sea', 'beach', 'wood', 'coral', 'library', 'abyss'],
  cyclops_champion: ['mountain', 'cave', 'ruins', 'canyon', 'battlefield'],
  minotaur_arena_lord: ['dungeon', 'ruins', 'temple', 'sandstone', 'battlefield'],
  harpy_stormcaller: ['sky', 'mountain', 'ruins', 'canyon', 'aurora', 'storm', 'battlefield'],
  scorpion_broodmother: ['desert', 'beach', 'ashland', 'oasis', 'obsidian', 'saltflat'],
  cultist_hierophant: ['dungeon', 'ruins', 'temple', 'shadow', 'blood', 'wood', 'sandstone', 'battlefield', 'library'],
  gargoyle_sentinel: ['ruins', 'temple', 'dungeon', 'sky', 'aurora', 'sandstone', 'storm', 'battlefield'],
  pixie_queen_guard: ['enchanted', 'grass', 'meadow', 'mushroom', 'garden'],
  gnoll_packlord: ['dirt', 'grass', 'meadow', 'ruins', 'dungeon', 'desert', 'oasis', 'garden', 'battlefield', 'saltflat'],
  ratman_warlord: ['dungeon', 'wood', 'ruins', 'temple', 'dirt', 'blood', 'sandstone', 'battlefield', 'library'],
  crab_shellbreaker: ['beach', 'sea', 'coral', 'abyss'],
  wasp_hivequeen_guard: ['grass', 'jungle', 'meadow', 'enchanted', 'mushroom', 'beach', 'garden', 'bramble'],
  toad_bog_king: ['swamp', 'sewer', 'mushroom', 'jungle', 'mountain', 'canyon', 'marsh', 'bramble'],
  dwarf_warcaptain: ['dungeon', 'wood', 'ruins', 'temple', 'dirt', 'sandstone', 'battlefield', 'library'],
  wraith_reaper: ['graveyard', 'shadow', 'ruins', 'ice', 'blood', 'glacier', 'battlefield', 'catacomb'],
  frost_mage_adept: ['ice', 'snow', 'tundra', 'mountain', 'dungeon', 'glacier', 'canyon'],
  death_knight_vanguard: ['graveyard', 'ruins', 'dungeon', 'temple', 'shadow', 'blood', 'sandstone', 'battlefield', 'catacomb'],
  shadow_assassin_master: ['shadow', 'graveyard', 'ruins', 'crystal', 'dungeon', 'wood', 'blood', 'battlefield', 'library', 'catacomb'],
  stone_golem_warden: ['cave', 'mountain', 'dungeon', 'ruins', 'canyon', 'battlefield'],
  orc_warchief_king: ['dirt', 'grass', 'mountain', 'ashland', 'meadow', 'desert', 'blood', 'oasis', 'canyon', 'obsidian', 'garden', 'saltflat'],
  goblin_warlord_king: ['dirt', 'grass', 'cave', 'dungeon', 'mountain', 'wood', 'canyon', 'library'],
  slime_emperor: ['sewer', 'dungeon', 'cave', 'swamp', 'mushroom', 'marsh'],
  wolf_dire_king: ['grass', 'meadow', 'tundra', 'snow', 'mountain', 'canyon', 'garden'],
  skeleton_bone_king: ['graveyard', 'dungeon', 'ruins', 'temple', 'wood', 'blood', 'sandstone', 'battlefield', 'library', 'catacomb'],
  imp_hell_overlord: ['volcano', 'hell', 'lava_field', 'dungeon', 'blood'],
  elf_forest_sovereign: ['grass', 'enchanted', 'jungle', 'meadow', 'garden', 'bramble'],
  zombie_plague_king: ['graveyard', 'swamp', 'dungeon', 'sewer', 'blood', 'marsh', 'catacomb'],
  mummy_pharaoh: ['desert', 'temple', 'ruins', 'graveyard', 'oasis', 'sandstone', 'battlefield', 'catacomb', 'saltflat'],
  cyclops_mountain_king: ['mountain', 'cave', 'ruins', 'canyon', 'battlefield'],
  minotaur_labyrinth_king: ['dungeon', 'ruins', 'temple', 'sandstone', 'battlefield'],
  harpy_sky_empress: ['sky', 'mountain', 'ruins', 'canyon', 'aurora', 'storm', 'battlefield'],
  cultist_dark_messiah: ['dungeon', 'ruins', 'temple', 'shadow', 'blood', 'wood', 'sandstone', 'battlefield', 'library'],
  gargoyle_cathedral_lord: ['ruins', 'temple', 'dungeon', 'sky', 'aurora', 'sandstone', 'storm', 'battlefield'],
  gnoll_war_khan: ['dirt', 'grass', 'meadow', 'ruins', 'dungeon', 'desert', 'oasis', 'garden', 'battlefield', 'saltflat'],
  pirate_sea_emperor: ['sea', 'beach', 'wood', 'coral', 'library', 'abyss'],
  bandit_crime_emperor: ['dungeon', 'wood', 'ruins', 'temple', 'dirt', 'desert', 'blood', 'oasis', 'sandstone', 'battlefield', 'library', 'saltflat'],
  dwarf_forge_king: ['dungeon', 'wood', 'ruins', 'temple', 'dirt', 'sandstone', 'battlefield', 'library'],
  ratman_underking: ['dungeon', 'wood', 'ruins', 'temple', 'dirt', 'blood', 'sandstone', 'battlefield', 'library'],
  scorpion_dune_emperor: ['desert', 'beach', 'ashland', 'oasis', 'obsidian', 'saltflat'],
  amber_mite_junior: ["desert","oasis","ashland","saltflat","beach","obsidian"],
  ash_rat_runt: ["volcano","hell","lava_field","ashland","dungeon","obsidian"],
  ash_vole_cadet: ["volcano","hell","lava_field","ashland","obsidian"],
  aurora_moth_rookie: ["sky","mountain","aurora","storm","canyon","meadow"],
  bandit_page: ["dungeon","wood","ruins","temple","dirt","desert","blood","oasis","sandstone","battlefield","library","saltflat"],
  bark_spider_acolyte: ["grass","jungle","meadow","enchanted","mushroom","garden","bramble"],
  bat_squire: ["cave","dungeon","graveyard","shadow","wood","blood","library","catacomb"],
  blood_leech_larva: ["swamp","sewer","mushroom","jungle","blood","marsh","bramble"],
  blood_mite_junior: ["graveyard","ruins","dungeon","shadow","catacomb","battlefield","blood"],
  boar_piglet_runt: ["cave","mountain","dungeon","ruins","grass","canyon","battlefield"],
  bog_finch_cadet: ["swamp","sewer","mushroom","marsh","bramble","jungle"],
  bog_mosquito_rookie: ["swamp","sewer","mushroom","jungle","marsh","bramble"],
  bog_newt_page: ["swamp","sewer","mushroom","jungle","marsh","bramble"],
  bone_picker_acolyte: ["graveyard","ruins","dungeon","temple","shadow","sandstone","battlefield","catacomb"],
  bone_shardling_squire: ["graveyard","ruins","dungeon","temple","shadow","sandstone","battlefield","catacomb"],
  bramble_boar_larva: ["grass","jungle","meadow","enchanted","garden","bramble"],
  brimstone_imp_junior: ["volcano","hell","lava_field","ashland","cave","obsidian"],
  brine_crab_runt: ["sea","beach","coral","abyss"],
  carrion_vulture_cadet: ["graveyard","ruins","dungeon","temple","shadow","sandstone","battlefield","catacomb"],
  cave_bat_swarm_rookie: ["sky","mountain","grass","meadow","cave","canyon","aurora","storm","garden"],
  cave_crawler_page: ["cave","mountain","dungeon","ruins","canyon","battlefield"],
  cave_troll_acolyte: ["cave","mountain","dungeon","ruins","tundra","canyon","battlefield"],
  chalk_imp_squire: ["temple","ruins","dungeon","sandstone","library","battlefield"],
  cinder_moth_larva: ["volcano","hell","lava_field","ashland","obsidian"],
  cinder_sprite_junior: ["volcano","hell","lava_field","ashland","grass","obsidian"],
  cinder_toad_runt: ["volcano","hell","lava_field","ashland","obsidian"],
  clay_soldier_cadet: ["dungeon","wood","ruins","temple","dirt","sandstone","battlefield","library"],
  cliff_goat_rookie: ["mountain","tundra","cave","meadow","canyon","garden"],
  copper_goblin_page: ["dungeon","wood","ruins","temple","dirt","sandstone","battlefield","library"],
  copper_tick_acolyte: ["cave","mountain","dungeon","ruins","canyon","battlefield"],
  coral_crab_squire: ["sea","beach","coral","abyss"],
  coral_crab_hatch_larva: ["sea","beach","coral","abyss"],
  coral_snake_junior: ["sea","beach","coral","abyss"],
  coral_urchin_runt: ["sea","beach","coral","abyss"],
  crab_cadet: ["beach","sea","coral","abyss"],
  crystal_bat_rookie: ["crystal","cave","enchanted","temple","sky","aurora","sandstone","storm"],
  crystal_finch_page: ["crystal","cave","enchanted","temple","sandstone","abyss"],
  crystal_mite_acolyte: ["crystal","cave","enchanted","temple","mountain","canyon","sandstone"],
  cultist_squire: ["dungeon","ruins","temple","shadow","blood","wood","sandstone","battlefield","library"],
  cyclops_larva: ["mountain","cave","ruins","canyon","battlefield"],
  driftwood_crab_junior: ["sea","beach","coral","abyss"],
  dune_jackal_runt: ["desert","beach","ashland","oasis","obsidian","saltflat"],
  dune_scarab_cadet: ["desert","oasis","ashland","saltflat","beach","obsidian"],
  dune_viper_rookie: ["desert","beach","ashland","oasis","obsidian","saltflat"],
  dusk_ferret_page: ["shadow","graveyard","ruins","crystal","dungeon","battlefield","catacomb"],
  dust_jackal_acolyte: ["desert","oasis","ashland","saltflat","beach","obsidian"],
  dust_mephit_squire: ["dirt","grass","meadow","ruins","dungeon","desert","beach","oasis","garden","battlefield","saltflat"],
  dwarf_guard_larva: ["dungeon","wood","ruins","temple","dirt","sandstone","battlefield","library"],
  elf_junior: ["grass","enchanted","jungle","meadow","garden","bramble"],
  ember_gnat_runt: ["volcano","hell","lava_field","ashland","obsidian"],
  ember_vole_cadet: ["volcano","hell","lava_field","ashland","obsidian"],
  fog_hare_rookie: ["grass","jungle","meadow","enchanted","garden","bramble"],
  fox_trickster_page: ["grass","jungle","meadow","enchanted","mushroom","desert","oasis","garden","bramble","saltflat"],
  frogman_acolyte: ["swamp","sewer","mushroom","jungle","coral","beach","marsh","abyss","bramble"],
  frogman_poliwog_squire: ["swamp","sewer","mushroom","jungle","coral","beach","marsh","abyss","bramble"],
  frost_gnat_larva: ["ice","snow","tundra","glacier","mountain","canyon"],
  frost_sprite_junior: ["ice","snow","tundra","mountain","grass","glacier","canyon"],
  frost_toad_runt: ["ice","snow","tundra","mountain","swamp","glacier","canyon","marsh"],
  frost_vole_cadet: ["ice","snow","tundra","mountain","glacier","canyon"],
  gargoyle_rookie: ["ruins","temple","dungeon","sky","aurora","sandstone","storm","battlefield"],
  geyser_toad_page: ["swamp","sewer","mushroom","jungle","coral","marsh","abyss","bramble"],
  ghoul_acolyte: ["graveyard","dungeon","sewer","ruins","blood","battlefield","catacomb"],
  giant_toad_squire: ["swamp","sewer","mushroom","jungle","mountain","canyon","marsh","bramble"],
  glacier_imp_larva: ["ice","snow","tundra","mountain","hell","glacier","canyon"],
  glacier_mite_junior: ["ice","snow","tundra","glacier","mountain","canyon"],
  glass_imp_runt: ["crystal","cave","enchanted","temple","hell","ice","glacier","sandstone"],
  glint_pixie_cadet: ["crystal","cave","enchanted","temple","sandstone","abyss"],
  gnoll_rookie: ["dirt","grass","meadow","ruins","dungeon","desert","oasis","garden","battlefield","saltflat"],
  goblin_page: ["dirt","grass","cave","dungeon","mountain","wood","canyon","library"],
  gust_sylph_acolyte: ["sky","mountain","aurora","storm","canyon","meadow"],
  harpy_squire: ["sky","mountain","ruins","canyon","aurora","storm","battlefield"],
  ice_imp_larva: ["ice","snow","tundra","mountain","hell","glacier","canyon"],
  ice_tick_junior: ["ice","snow","tundra","glacier","mountain","canyon"],
  imp_runt: ["volcano","hell","lava_field","dungeon","blood"],
  iron_boar_cadet: ["cave","mountain","dungeon","ruins","grass","canyon","battlefield"],
  iron_tick_rookie: ["cave","mountain","dungeon","ruins","canyon","battlefield"],
  ivory_skeleton_page: ["graveyard","ruins","dungeon","temple","shadow","sandstone","battlefield","catacomb"],
  kelp_newt_acolyte: ["sea","beach","coral","abyss"],
  kelp_strider_squire: ["sea","beach","coral","abyss"],
  kobold_larva: ["dungeon","wood","ruins","temple","dirt","sandstone","battlefield","library"],
  lantern_spirit_junior: ["enchanted","crystal","sky","meadow","aurora","storm","garden"],
  magma_grub_runt: ["volcano","hell","lava_field","ashland","obsidian"],
  mangrove_croco_cadet: ["dirt","grass","meadow","ruins","dungeon","garden","battlefield"],
  marsh_imp_rookie: ["swamp","sewer","mushroom","marsh","bramble","jungle"],
  marsh_lurker_page: ["swamp","sewer","mushroom","jungle","marsh","bramble"],
  minotaur_acolyte: ["dungeon","ruins","temple","sandstone","battlefield"],
  mire_slug_squire: ["swamp","sewer","mushroom","marsh","bramble","jungle"],
  mist_imp_larva: ["shadow","graveyard","ruins","crystal","dungeon","catacomb"],
  mist_wisp_junior: ["enchanted","crystal","sky","meadow","ice","glacier","aurora","storm","garden"],
  moss_newt_runt: ["swamp","sewer","mushroom","marsh","bramble","jungle"],
  moss_sprite_cadet: ["grass","jungle","meadow","enchanted","mushroom","garden","bramble"],
  mummy_rookie: ["desert","temple","ruins","graveyard","oasis","sandstone","battlefield","catacomb","saltflat"],
  mushroom_brute_page: ["swamp","sewer","mushroom","jungle","marsh","bramble"],
  night_owl_acolyte: ["shadow","graveyard","ruins","crystal","dungeon","battlefield","catacomb"],
  night_panther_squire: ["shadow","graveyard","ruins","crystal","dungeon","battlefield","catacomb"],
  onyx_beetle_larva: ["cave","mountain","dungeon","ruins","canyon","battlefield"],
  aurora_moth_veteran: ["sky","mountain","aurora","storm","canyon","meadow"],
  bandit_champion: ["dungeon","wood","ruins","temple","dirt","desert","blood","oasis","sandstone","battlefield","library","saltflat"],
  bark_spider_sentinel: ["grass","jungle","meadow","enchanted","mushroom","garden","bramble"],
  bat_raider: ["cave","dungeon","graveyard","shadow","wood","blood","library","catacomb"],
  blood_leech_marshal: ["swamp","sewer","mushroom","jungle","blood","marsh","bramble"],
  blood_mite_prime: ["graveyard","ruins","dungeon","shadow","catacomb","battlefield","blood"],
  boar_piglet_guardian: ["cave","mountain","dungeon","ruins","grass","canyon","battlefield"],
  bog_finch_warder: ["swamp","sewer","mushroom","marsh","bramble","jungle"],
  bog_mosquito_veteran: ["swamp","sewer","mushroom","jungle","marsh","bramble"],
  bog_newt_champion: ["swamp","sewer","mushroom","jungle","marsh","bramble"],
  bone_picker_sentinel: ["graveyard","ruins","dungeon","temple","shadow","sandstone","battlefield","catacomb"],
  bone_shardling_raider: ["graveyard","ruins","dungeon","temple","shadow","sandstone","battlefield","catacomb"],
  bramble_boar_marshal: ["grass","jungle","meadow","enchanted","garden","bramble"],
  brimstone_imp_prime: ["volcano","hell","lava_field","ashland","cave","obsidian"],
  brine_crab_guardian: ["sea","beach","coral","abyss"],
  carrion_vulture_warder: ["graveyard","ruins","dungeon","temple","shadow","sandstone","battlefield","catacomb"],
  cave_bat_swarm_veteran: ["sky","mountain","grass","meadow","cave","canyon","aurora","storm","garden"],
  cave_crawler_champion: ["cave","mountain","dungeon","ruins","canyon","battlefield"],
  cave_troll_sentinel: ["cave","mountain","dungeon","ruins","tundra","canyon","battlefield"],
  chalk_imp_raider: ["temple","ruins","dungeon","sandstone","library","battlefield"],
  cinder_moth_marshal: ["volcano","hell","lava_field","ashland","obsidian"],
  cinder_sprite_prime: ["volcano","hell","lava_field","ashland","grass","obsidian"],
  cinder_toad_guardian: ["volcano","hell","lava_field","ashland","obsidian"],
  clay_soldier_warder: ["dungeon","wood","ruins","temple","dirt","sandstone","battlefield","library"],
  cliff_goat_veteran: ["mountain","tundra","cave","meadow","canyon","garden"],
  copper_goblin_champion: ["dungeon","wood","ruins","temple","dirt","sandstone","battlefield","library"],
  copper_tick_sentinel: ["cave","mountain","dungeon","ruins","canyon","battlefield"],
  coral_crab_raider: ["sea","beach","coral","abyss"],
  coral_crab_hatch_marshal: ["sea","beach","coral","abyss"],
  coral_snake_prime: ["sea","beach","coral","abyss"],
  coral_urchin_guardian: ["sea","beach","coral","abyss"],
  crab_warder: ["beach","sea","coral","abyss"],
  crystal_bat_veteran: ["crystal","cave","enchanted","temple","sky","aurora","sandstone","storm"],
  crystal_finch_champion: ["crystal","cave","enchanted","temple","sandstone","abyss"],
  crystal_mite_sentinel: ["crystal","cave","enchanted","temple","mountain","canyon","sandstone"],
  cultist_raider: ["dungeon","ruins","temple","shadow","blood","wood","sandstone","battlefield","library"],
  cyclops_marshal: ["mountain","cave","ruins","canyon","battlefield"],
  driftwood_crab_prime: ["sea","beach","coral","abyss"],
  dune_jackal_guardian: ["desert","beach","ashland","oasis","obsidian","saltflat"],
  dune_scarab_warder: ["desert","oasis","ashland","saltflat","beach","obsidian"],
  dune_viper_veteran: ["desert","beach","ashland","oasis","obsidian","saltflat"],
  dusk_ferret_champion: ["shadow","graveyard","ruins","crystal","dungeon","battlefield","catacomb"],
  dust_jackal_sentinel: ["desert","oasis","ashland","saltflat","beach","obsidian"],
  dust_mephit_raider: ["dirt","grass","meadow","ruins","dungeon","desert","beach","oasis","garden","battlefield","saltflat"],
  dwarf_guard_marshal: ["dungeon","wood","ruins","temple","dirt","sandstone","battlefield","library"],
  elf_prime: ["grass","enchanted","jungle","meadow","garden","bramble"],
  ember_gnat_guardian: ["volcano","hell","lava_field","ashland","obsidian"],
  ember_vole_warder: ["volcano","hell","lava_field","ashland","obsidian"],
  fog_hare_veteran: ["grass","jungle","meadow","enchanted","garden","bramble"],
  fox_trickster_champion: ["grass","jungle","meadow","enchanted","mushroom","desert","oasis","garden","bramble","saltflat"],
  frogman_sentinel: ["swamp","sewer","mushroom","jungle","coral","beach","marsh","abyss","bramble"],
  frogman_poliwog_raider: ["swamp","sewer","mushroom","jungle","coral","beach","marsh","abyss","bramble"],
  frost_gnat_marshal: ["ice","snow","tundra","glacier","mountain","canyon"],
  frost_sprite_prime: ["ice","snow","tundra","mountain","grass","glacier","canyon"],
  frost_toad_guardian: ["ice","snow","tundra","mountain","swamp","glacier","canyon","marsh"],
  frost_vole_warder: ["ice","snow","tundra","mountain","glacier","canyon"],
  gargoyle_veteran: ["ruins","temple","dungeon","sky","aurora","sandstone","storm","battlefield"],
  geyser_toad_champion: ["swamp","sewer","mushroom","jungle","coral","marsh","abyss","bramble"],
  ghoul_sentinel: ["graveyard","dungeon","sewer","ruins","blood","battlefield","catacomb"],
  giant_toad_raider: ["swamp","sewer","mushroom","jungle","mountain","canyon","marsh","bramble"],
  glacier_imp_marshal: ["ice","snow","tundra","mountain","hell","glacier","canyon"],
  glacier_mite_prime: ["ice","snow","tundra","glacier","mountain","canyon"],
  glass_imp_guardian: ["crystal","cave","enchanted","temple","hell","ice","glacier","sandstone"],
  glint_pixie_warder: ["crystal","cave","enchanted","temple","sandstone","abyss"],
  blood_leech_tyrant: ["swamp","sewer","mushroom","jungle","blood","marsh","bramble"],
  blood_mite_colossus: ["graveyard","ruins","dungeon","shadow","catacomb","battlefield","blood"],
  boar_piglet_patriarch: ["cave","mountain","dungeon","ruins","grass","canyon","battlefield"],
  bog_finch_matriarch: ["swamp","sewer","mushroom","marsh","bramble","jungle"],
  bog_mosquito_duke: ["swamp","sewer","mushroom","jungle","marsh","bramble"],
  bog_newt_baron: ["swamp","sewer","mushroom","jungle","marsh","bramble"],
  bone_picker_ascendant: ["graveyard","ruins","dungeon","temple","shadow","sandstone","battlefield","catacomb"],
  bone_shardling_paragon: ["graveyard","ruins","dungeon","temple","shadow","sandstone","battlefield","catacomb"],
  bramble_boar_tyrant: ["grass","jungle","meadow","enchanted","garden","bramble"],
  brimstone_imp_colossus: ["volcano","hell","lava_field","ashland","cave","obsidian"],
  brine_crab_patriarch: ["sea","beach","coral","abyss"],
  carrion_vulture_matriarch: ["graveyard","ruins","dungeon","temple","shadow","sandstone","battlefield","catacomb"],
  cave_bat_swarm_duke: ["sky","mountain","grass","meadow","cave","canyon","aurora","storm","garden"],
  cave_crawler_baron: ["cave","mountain","dungeon","ruins","canyon","battlefield"],
  cave_troll_ascendant: ["cave","mountain","dungeon","ruins","tundra","canyon","battlefield"],
  chalk_imp_paragon: ["temple","ruins","dungeon","sandstone","library","battlefield"],
  cinder_moth_tyrant: ["volcano","hell","lava_field","ashland","obsidian"],
  cinder_sprite_colossus: ["volcano","hell","lava_field","ashland","grass","obsidian"],
  cinder_toad_patriarch: ["volcano","hell","lava_field","ashland","obsidian"],
  clay_soldier_matriarch: ["dungeon","wood","ruins","temple","dirt","sandstone","battlefield","library"],
  cliff_goat_duke: ["mountain","tundra","cave","meadow","canyon","garden"],
  copper_goblin_baron: ["dungeon","wood","ruins","temple","dirt","sandstone","battlefield","library"],
  copper_tick_ascendant: ["cave","mountain","dungeon","ruins","canyon","battlefield"],
  coral_crab_paragon: ["sea","beach","coral","abyss"],
  coral_crab_hatch_tyrant: ["sea","beach","coral","abyss"],
  coral_snake_colossus: ["sea","beach","coral","abyss"],
  coral_urchin_patriarch: ["sea","beach","coral","abyss"],
  crab_matriarch: ["beach","sea","coral","abyss"],
  crystal_bat_duke: ["crystal","cave","enchanted","temple","sky","aurora","sandstone","storm"],
  crystal_finch_baron: ["crystal","cave","enchanted","temple","sandstone","abyss"],
  crystal_mite_ascendant: ["crystal","cave","enchanted","temple","mountain","canyon","sandstone"],
  cultist_paragon: ["dungeon","ruins","temple","shadow","blood","wood","sandstone","battlefield","library"],
  cyclops_tyrant: ["mountain","cave","ruins","canyon","battlefield"],
  driftwood_crab_colossus: ["sea","beach","coral","abyss"],
  dune_jackal_patriarch: ["desert","beach","ashland","oasis","obsidian","saltflat"],
  dune_scarab_matriarch: ["desert","oasis","ashland","saltflat","beach","obsidian"],
  dune_viper_duke: ["desert","beach","ashland","oasis","obsidian","saltflat"],
  dusk_ferret_baron: ["shadow","graveyard","ruins","crystal","dungeon","battlefield","catacomb"],
  dust_jackal_ascendant: ["desert","oasis","ashland","saltflat","beach","obsidian"],
  dust_mephit_paragon: ["dirt","grass","meadow","ruins","dungeon","desert","beach","oasis","garden","battlefield","saltflat"],
  // Expansão 7 +18
  glass_wisp: ["crystal", "aurora", "glacier", "snow", "enchanted", "sky", "library"],
  peat_boar: ["swamp", "marsh", "bramble", "mushroom", "jungle", "grass", "meadow"],
  rust_golem: ["ruins", "battlefield", "dungeon", "ashland", "obsidian", "cave", "sandstone"],
  lantern_moth: ["garden", "meadow", "enchanted", "mushroom", "jungle", "grass", "temple"],
  brine_eel: ["sea", "coral", "beach", "marsh", "swamp", "sewer", "oasis"],
  spore_toad: ["mushroom", "swamp", "marsh", "jungle", "bramble", "garden"],
  flint_imp: ["volcano", "lava_field", "ashland", "cave", "mountain", "obsidian", "hell"],
  hail_raven: ["snow", "tundra", "glacier", "mountain", "sky", "aurora", "storm"],
  root_hound: ["grass", "meadow", "bramble", "jungle", "garden", "dirt", "canyon"],
  mirror_sprite: ["crystal", "enchanted", "aurora", "library", "temple", "ruins", "shadow"],
  kiln_scarab: ["volcano", "lava_field", "ashland", "desert", "obsidian", "hell", "saltflat"],
  void_newt: ["shadow", "abyss", "catacomb", "graveyard", "dungeon", "blood", "sewer"],
  thunder_ibex: ["mountain", "canyon", "storm", "sky", "tundra", "meadow", "battlefield"],
  coral_medusa: ["coral", "sea", "beach", "marsh", "ruins", "abyss", "temple"],
  ember_knight: ["hell", "volcano", "battlefield", "ruins", "obsidian", "lava_field", "temple"],
  frost_colossus: ["glacier", "snow", "tundra", "aurora", "mountain", "crystal", "cave"],
  nightbloom_hydra: ["shadow", "graveyard", "mushroom", "bramble", "abyss", "blood", "enchanted"],
  starfall_oracle: ["sky", "aurora", "enchanted", "temple", "library", "crystal", "storm"],
};

export function floorsForMonster(type) {
  return MONSTER_FLOORS[type] || null;
}

/** Todos os IDs de terreno da arena (legado + expansão). */
export const ALL_FLOOR_TYPES = [
  "dirt",
  "grass",
  "ice",
  "wood",
  "sea",
  "desert",
  "swamp",
  "volcano",
  "ruins",
  "crystal",
  "snow",
  "tundra",
  "cave",
  "dungeon",
  "graveyard",
  "hell",
  "sky",
  "mushroom",
  "jungle",
  "mountain",
  "beach",
  "coral",
  "ashland",
  "enchanted",
  "blood",
  "shadow",
  "temple",
  "sewer",
  "meadow",
  "lava_field",
  "glacier",
  "oasis",
  "canyon",
  "marsh",
  "aurora",
  "obsidian",
  "sandstone",
  "storm",
  "garden",
  "battlefield",
  "library",
  "catacomb",
  "abyss",
  "bramble",
  "saltflat"
];
