  // Expansão 8 +300
  furnace_snake: 'serpente fornalha',
  hail_crab: 'caranguejo granizo',
  blizzard_vole: 'arganaz nevasca',
  peat_jackal: 'chacal turfa',
  reed_ibex: 'íbex junco',
  sand_ape: 'macaco areia',
  mirage_finch: 'tentilhão miragem',
  vine_fly: 'mosca cipó',
  pine_sprite_2: 'sprite pinheiro',
  cave_gremlin: 'gremlin caverna',
  quartz_troll: 'troll quartzo',
  grave_construct: 'constructo túmulo',
  ghoul_mage: 'mago carniçal',
  tide_assassin: 'assassino maré',
  kelp_raider: 'saqueador alga',
  storm_mummy: 'múmia tempestade',
  cloud_whelp: 'filhote nuvem',
  prism_sphinx: 'esfinge prisma',
  jade_krakenling: 'krakenzinho jade',
  shadow_dryad: 'dríade sombra',
  night_cyclops_cub: 'ciclope filhote noite',
  rune_familiar: 'familiar runa',
  oracle_chanter: 'cantor oráculo',
  iron_berserker: 'berserker ferro',
  bronze_swarmer: 'enxame bronze',
  ivory_cub: 'filhote marfim',
  violet_brute: 'bruto violeta',
  scarlet_stinger: 'ferrão escarlate',
  gloom_haunter: 'assombrador treva',
  feral_piercer: 'perfurador feroz',
  fallen_freezer: 'congelador caído',
  rot_weaver: 'tecelão podridão',
  lava_diver: 'mergulhador lava',
  marble_glider: 'planador mármore',
  mist_prophet: 'profeta névoa',
  plasma_savant: 'erudito plasma',
  stellar_jailer: 'carcereiro estelar',
  blood_zealot: 'fanático sangue',
  dream_exile: 'exilado sonho',
  warp_tick: 'carrapato distorção',
  nether_slug: 'lesma nether',
  sharp_snake: 'serpente afiado',
  howling_crab: 'caranguejo uivante',
  echo_vole: 'arganaz eco',
  surge_jackal: 'chacal surto',
  rusted_ibex: 'íbex enferrujado',
  burning_ape: 'macaco ardente',
  twisted_finch: 'tentilhão torcido',
  shard_fly: 'mosca fragmento',
  fang_sprite: 'sprite presa',
  scale_gremlin: 'gremlin escama',
  crown_troll: 'troll coroa',
  torch_construct: 'constructo tocha',
  drum_mage: 'mago tambor',
  cinder_assassin: 'assassino cinza',
  magma_raider: 'saqueador magma',
  kiln_mummy: 'múmia forno',
  glacier_whelp: 'filhote geleira',
  arctic_sphinx: 'esfinge ártico',
  bog_krakenling: 'krakenzinho pântano',
  fungal_dryad: 'dríade fúngico',
  dune_cyclops_cub: 'ciclope filhote duna',
  dust_familiar: 'familiar pó',
  thorn_chanter: 'cantor espinho',
  bark_berserker: 'berserker casca',
  root_swarmer: 'enxame raiz',
  granite_cub: 'filhote granito',
  tunnel_brute: 'bruto túnel',
  crypt_stinger: 'ferrão cripta',
  plague_haunter: 'assombrador praga',
  coral_piercer: 'perfurador coral',
  reef_freezer: 'congelador recife',
  thunder_weaver: 'tecelão trovão',
  zephyr_diver: 'mergulhador zéfiro',
  glass_glider: 'planador vidro',
  ruby_prophet: 'profeta rubi',
  dusk_savant: 'erudito crepúsculo',
  hex_jailer: 'carcereiro hex',
  idol_zealot: 'fanático ídolo',
  arcane_exile: 'exilado arcano',
  copper_tick_2: 'carrapato cobre',
  crimson_slug: 'lesma carmesim',
  amber_snake: 'serpente âmbar',
  verdant_crab: 'caranguejo verdejante',
  hollow_vole: 'arganaz oco',
  wild_jackal: 'chacal selvagem',
  elder_ibex: 'íbex ancião',
  blight_ape: 'macaco praga',
  venom_finch: 'tentilhão veneno',
  slate_fly: 'mosca ardósia',
  ink_sprite: 'sprite tinta',
  spark_gremlin: 'gremlin faísca',
  lunar_troll: 'troll lunar',
  doom_construct: 'constructo perdição',
  spirit_mage: 'mago espírito',
  rift_assassin: 'assassino fenda',
  aether_raider: 'saqueador éter',
  raw_mummy: 'múmia bruto',
  silent_whelp: 'filhote silencioso',
  whisper_sphinx: 'esfinge sussurro',
  flux_krakenling: 'krakenzinho fluxo',
  gilded_dryad: 'dríade dourado',
  frozen_cyclops_cub: 'ciclope filhote congelado',
  laughing_familiar: 'familiar ríspido',
  splinter_chanter: 'cantor estilhaço',
  claw_berserker: 'berserker garra',
  wing_swarmer: 'enxame asa',
  mask_cub: 'filhote máscara',
  blade_brute: 'bruto lâmina',
  bell_stinger: 'ferrão sino',
  dirge_haunter: 'assombrador réquiem',
  pyre_piercer: 'perfurador pira',
  soot_freezer: 'congelador fuligem',
  frost_weaver: 'tecelão geada',
  rime_diver: 'mergulhador geada',
  mire_glider: 'planador lodo',
  spore_prophet: 'profeta esporo',
  marsh_savant: 'erudito charco',
  salt_jailer: 'carcereiro sal',
  oasis_zealot: 'fanático oásis',
  moss_exile: 'exilado musgo',
  bloom_tick: 'carrapato flor',
  shale_slug: 'lesma folhelho',
  obsidian_snake: 'serpente obsidiana',
  bone_crab: 'caranguejo osso',
  wraith_vole: 'arganaz espectro',
  brine_jackal: 'chacal salmoura',
  abyss_ibex: 'íbex abismo',
  gale_ape: 'macaco vendaval',
  aurora_finch: 'tentilhão aurora',
  crystal_fly: 'mosca cristal',
  sapphire_sprite: 'sprite safira',
  void_gremlin: 'gremlin vazio',
  eclipse_troll: 'troll eclipse',
  temple_construct: 'constructo templo',
  sacred_mage: 'mago sagrado',
  scrap_assassin: 'assassino sucata',
  ashen_raider: 'saqueador acinzentado',
  onyx_mummy: 'múmia ônix',
  azure_whelp: 'filhote azul',
  pale_sphinx: 'esfinge pálido',
  bright_krakenling: 'krakenzinho luminoso',
  ancient_dryad: 'dríade ancestral',
  cursed_cyclops_cub: 'ciclope filhote amaldiçoado',
  blizzard_scarab_chief: 'escaravelho nevasca chefe',
  marsh_fish_overseer: 'peixe charco supervisor',
  thorn_fox_raider: 'raposa espinho saqueador',
  cave_ape_enraged: 'macaco caverna enraivecido',
  bone_spider_savage: 'aranha osso selvagem',
  coral_kobold_dawn: 'kobold coral alvorada',
  cloud_knight_venomous: 'cavaleiro nuvem venenoso',
  sapphire_scout_frozen: 'batedor safira congelado',
  hex_whelp_necrotic: 'filhote hex necrótico',
  iron_leviathan_cub_raid: 'leviatã filhote ferro de raid',
  onyx_efreet_matron: 'efreet ônix matrona',
  hollow_monk_broodmother: 'monge oco mãe da ninhada',
  fallen_hatchling_hexer: 'filhote caído amaldiçoador',
  coal_stinger_prime: 'ferrão carvão primordial',
  spark_bombardier_blessed: 'bombardeiro faísca abençoado',
  blood_smith_ironbound: 'ferreiro sangue preso em ferro',
  chrono_trickster_runic: 'trapaceiro crono rúnico',
  silent_keeper_abyssal: 'guarda silencioso abissal',
  surge_exile_war: 'exilado surto de guerra',
  weeping_snail_captain: 'caracol choroso capitão',
  claw_jellyfish_champion: 'água-viva garra campeão',
  crown_panther_sentinel: 'pantera coroa sentinela',
  choir_hawk_armored: 'falcão coro blindado',
  soot_sprite_dire: 'sprite fuligem terrível',
  arctic_ogre_midnight: 'ogro ártico meia-noite',
  reed_priest_blooded: 'sacerdote junco sangrento',
  oasis_skeleton_ashen: 'esqueleto oásis acinzentado',
  root_naga_infernal: 'naga raiz infernal',
  grave_dryad_siege: 'dríade túmulo de cerco',
  brine_puppet_alpha: 'marionete salmoura alfa',
  thunder_stalker_packlord: 'perseguidor trovão senhor da matilha',
  jade_fledgling_stalker: 'filhote jade perseguidor',
  eclipse_whisperer_ascendant: 'sussurrador eclipse ascendente',
  arcane_freezer_cursed: 'congelador arcano amaldiçoado',
  ivory_sailor_stormforged: 'marinheiro marfim forjado na tempestade',
  pale_acolyte_arcane: 'acólito pálido arcano',
  elder_judge_molten: 'juiz ancião fundido',
  lava_mite_primal: 'ácaro lava primitivo',
  fog_snake_veteran: 'serpente neblina veterano',
  doom_ferret_warden: 'furão perdição guardião',
  warp_ram_hierophant: 'carneiro distorção hierofante',
  jagged_drone_blighted: 'zangão serrilhado corrompido',
  flux_mephit_greater: 'mefite fluxo maior',
  burning_construct_twilight: 'constructo ardente crepuscular',
  spike_duelist_soulbound: 'duelista espeto preso à alma',
  mask_specter_crystalbound: 'fantasma máscara cristalino',
  drum_chimera_celestial: 'quimera tambor celestial',
  brimstone_minotaurling_battle: 'minotauro jovem enxofre de batalha',
  rime_chanter_chief: 'cantor geada chefe',
  fungal_swarm_overseer: 'enxame fúngico supervisor',
  mirage_smasher_raider: 'destruidor miragem saqueador',
  bloom_ripper_enraged: 'rasgador flor enraivecido',
  tunnel_binder_savage: 'amarrador túnel selvagem',
  tide_glider_dawn: 'planador maré alvorada',
  gale_archivist_venomous: 'arquivista vendaval venenoso',
  glass_martyr_frozen: 'mártir vidro congelado',
  night_grub_necrotic: 'larva noite necrótico',
  sacred_shark_raid: 'tubarão sagrado de raid',
  crimson_jackal_matron: 'chacal carmesim matrona',
  scarlet_bat_broodmother: 'morcego escarlate mãe da ninhada',
  ancient_mantis_hexer: 'louva-a-deus ancestral amaldiçoador',
  venom_gnoll_prime: 'gnoll veneno primordial',
  mist_archer_blessed: 'arqueiro névoa abençoado',
  chaos_raider_ironbound: 'saqueador caos preso em ferro',
  rift_drake_runic: 'draco fenda rúnico',
  sharp_phoenixling_abyssal: 'fênix filhote afiado abissal',
  pulse_marid_war: 'marid pulso de guerra',
  frozen_paladin_captain: 'paladino congelado capitão',
  shard_cub_champion: 'filhote fragmento campeão',
  shell_biter_sentinel: 'mordedor concha sentinela',
  bell_spitter_armored: 'cuspidor sino blindado',
  magma_forger_dire: 'forjador magma terrível',
  hail_oracle_midnight: 'oráculo granizo meia-noite',
  spore_jailer_blooded: 'carcereiro esporo sangrento',
  dust_outcast_ashen: 'pária pó acinzentado',
  pine_newt_infernal: 'tritão pinheiro infernal',
  obsidian_ray_siege: 'arraia obsidiana de cerco',
  plague_boar_alpha: 'javali praga alfa',
  storm_finch_packlord: 'tentilhão tempestade senhor da matilha',
  crystal_pixie_stalker: 'pixie cristal perseguidor',
  dusk_giant_ascendant: 'gigante crepúsculo ascendente',
  oracle_cultist_cursed: 'cultista oráculo amaldiçoado',
  ashen_zombie_stormforged: 'zumbi acinzentado forjado na tempestade',
  verdant_sphinx_arcane: 'esfinge verdejante arcano',
  feral_nymph_molten: 'ninfa feroz fundido',
  toxic_doll_primal: 'boneca tóxico primitivo',
  ink_lurker_veteran: 'espreitador tinta veterano',
  stellar_juvenile_warden: 'jovem estelar guardião',
  nightmare_haunter_hierophant: 'assombrador pesadelo hierofante',
  raw_burner_blighted: 'queimador bruto corrompido',
  echo_rider_greater: 'cavaleiro eco maior',
  molten_initiate_twilight: 'iniciado fundido crepuscular',
  splinter_inquisitor_soulbound: 'inquisidor estilhaço preso à alma',
  scale_tick_crystalbound: 'carrapato escama cristalino',
  lantern_viper_celestial: 'víbora lanterna celestial',
  pyre_weasel_battle: 'doninha pira de batalha',
  reed_urchin_emperor: 'ouriço junco imperador',
  vine_boar_overlord: 'javali cipó suserano',
  quartz_wasp_colossus: 'vespa quartzo colosso',
  tide_gremlin_primordial: 'gremlin maré primordial',
  cloud_knight_harbinger: 'cavaleiro nuvem presságio',
  shadow_bandit_eternal: 'bandido sombra eterno',
  oracle_naga_voidborn: 'naga oráculo nascido do vazio',
  ivory_satyr_deathlord: 'sátiro marfim senhor da morte',
  gloom_chanter_stormqueen: 'cantor treva rainha da tempestade',
  rot_spawn_boneking: 'cria podridão rei dos ossos',
  mist_biter_skymother: 'mordedor névoa mãe dos céus',
  blood_shocker_sunscorch: 'eletrizante sangue queimadura solar',
  nether_rider_entropy: 'cavaleiro nether entropia',
  echo_savant_worldbreaker: 'erudito eco quebrador de mundos',
  burning_pilgrim_hellcrown: 'peregrino ardente coroa do inferno',
  fang_snail_ironthrone: 'caracol presa trono de ferro',
  torch_rat_paragon: 'rato tocha paragão',
  magma_ram_alpha_prime: 'carneiro magma alfa primordial',
  arctic_fly_mythic: 'mosca ártico mítico',
  dune_gnoll_profane: 'gnoll duna profano',
  bark_witch_empress: 'bruxa casca imperatriz',
  tunnel_zombie_matriarch: 'zumbi túnel matriarca',
  coral_harpy_behemoth: 'harpía coral beemote',
  zephyr_cyclops_cub_avatar: 'ciclope filhote zéfiro avatar',
  dusk_monk_apocalypse: 'monge crepúsculo apocalipse',
  arcane_pup_infinite: 'filhote arcano infinito',
  amber_whisperer_starborn: 'sussurrador âmbar nascido das estrelas',
  wild_poisoner_flametyrant: 'envenenador selvagem tirano das chamas',
  venom_glider_plagueking: 'planador veneno rei da praga',
  spark_ward_ashenlord: 'guardião faísca senhor das cinzas',
  spirit_outcast_crystalheart: 'pária espírito coração de cristal',
  raw_frog_moonfall: 'rã bruto queda lunar',
  flux_weasel_chaosborn: 'doninha fluxo nascido do caos',
  laughing_ape_soulreaper: 'macaco ríspido ceifador de almas',
  wing_scorpion_abysscrown: 'escorpião asa coroa do abismo',
  bell_ogre_forgemaster: 'ogro sino mestre da forja',
  soot_alchemist_apex: 'alquimista fuligem ápice',
  mire_specter_final: 'fantasma lodo final',
  salt_krakenling_legendary: 'krakenzinho sal lendário',
  bloom_marid_sovereign: 'marid flor soberano',
  bone_reaver_tyrant: 'devastador osso tirano',
  abyss_juvenile_patriarch: 'jovem abismo patriarca',
  crystal_mangler_leviathan: 'dilacerador cristal leviatã',
  eclipse_weaver_herald: 'tecelão eclipse arauto',
  scrap_trickster_cataclysm: 'trapaceiro sucata cataclismo',
  azure_torturer_world: 'torturador azul do mundo',
  ancient_mite_doomlord: 'ácaro ancestral senhor da perdição',
  coal_eel_frostking: 'enguia carvão rei da geada',
  solar_jackal_bloodqueen: 'chacal solar rainha do sangue',
  nightmare_raven_tidefather: 'corvo pesadelo pai das marés',
  jagged_pixie_nightcrown: 'pixie serrilhado coroa da noite',
  rifted_elemental_riftwalker: 'elemental rachado caminhante da fenda',
  gnarled_warden_endbringer: 'guardião retorcido trazedor do fim',
  shell_whelp_graveking: 'filhote concha rei das tumbas',
  choir_treantling_jadeempire: 'treantzinho coro império de jade',
  furnace_puppet_archon: 'marionete fornalha arconte',
  peat_crawler_omega: 'rastejante turfa ômega',
  mirage_smasher_ultimate: 'destruidor miragem supremo',
  cave_piercer_divine: 'perfurador caverna divino',
  ghoul_forger_emperor: 'forjador carniçal imperador',
